#ifdef ENG
#define MainWindowTitle1 L"Piano-FX Pro"
#define MainWindowTitle2 L"Developed by: happy_mimimix"
#define MainWindowTitle3 L"Now playing: "
#define MainWindowTitle4 L"Now rendering: "
#define MainWindowTitle5 L"None"
#define MainWindowTitle6 L"Splash MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (Enforced Software Rendering)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"Welcome to Piano-FX Pro"
#define StartupStage1Text L"Preparing..."
#define StartupStage2Text L"Loading splash midi..."
#define StartupStage3Text L"Let's go!"
#define DigitSeparate 3
#define StatisticsText1 "Piano-FX Pro"
#define StatisticsText2 "Developed by: happy_mimimix"
#define StatisticsText3 "Time:"
#define StatisticsText4 "Tick:"
#define StatisticsText5 "Microseconds:"
#define StatisticsText6 "FPS:"
#define StatisticsText7 "Tempo:"
#define StatisticsText8 "Combo:"
#define StatisticsText9 "ClicksPerSecond:"
#define StatisticsText10 "Simultaneity:"
#define StatisticsText11 "Notes:"
#define StatisticsText12 "NotesPerSecond:"
#define StatisticsText13 "Polyphony:"
#define StatisticsText14 "Rendered:"
#define StatisticsText15 "Volume:"
#define StatisticsText16 "MUTED"
#define StatisticsText17 "PlaybackSpeed:"
#define StatisticsText18 "NoteSpeed:"
#define StatisticsText19 "Offset-X:"
#define StatisticsText20 "Offset-Y:"
#define StatisticsText21 "Zoom:"
#define StatisticsText22 "WindowSize:"
#define StatisticsText23 "KeyRange:"
#define StatisticsText24 "Score:"
#define StatisticsText25 "Level:"
#define StatisticsText26 "AutoPlay:"
#define StatisticsText27 "ON "
#define StatisticsText28 "FULL COMBO!!! "
#define StatisticsText29 "Deomonstration in progress... "
#define StatisticsText30 "Game paused... "
#define StatisticsText31 "ERROR: Score overflow! "
#define PropertyWindowTitle L"Preferences"
#define Property1Title L"Visual"
#define Property1Text1 L"Keys to display"
#define Property1Text2 L"Show all 128 keys"
#define Property1Text3 L"Show song keys"
#define Property1Text4 L"Show keys:"
#define Property1Text5 L"through"
#define Property1Text6 L"Don't hide controls toolbar in full screen mode"
#define Property1Text7 L"Same width notes"
#define Property1Text8 L"Track colors:"
#define Property1Text9 L"Background color:"
#define Property1Text10 L"Bar color:"
#define Property1Text11 L"Restore Defaults Colors"
#define Property2Title L"Audio"
#define Property2Text1 L"Standard WinMM output:"
#define Property2Text2 L"Use more efficient KDMAPI instead of WinMM (Requires OmniMIDI)"
#define Property3Title L"Render"
#define Property3Text1 L"Render options"
#define Property3Text2 L"Show debug information"
#define Property3Text3 L"Lock FPS to 60"
#define Property4Title L"Control"
#define Property4Text1 L"Control options"
#define Property4Text2 L"Left and right arrows skips the song by:"
#define Property4Text3 L"seconds"
#define Property4Text4 L"Up and down arrows speeds up the playback by:"
#define Property4Text5 L"percent"
#define Property5Title L"Other"
#define Property5Text1 L"Other options"
#define Property5Text2 L"Tick-based rendering"
#define Property5Text3 L"Visualize pitch bends"
#define Property5Text4 L"Phigros style scoring system"
#define Property5Text5 L"Show markers"
#define Property5Text6 L"Marker text encoding:"
#define Property5Text7 L"Splash MIDI:"
#define Property5Text8 L"Background:"
#define Property5Text9 L"Browse"
#define Property5Text10 L"Reset"
#define Property5Text11 L"Color loop"
#define Property5Text12 L"Video output"
#define Property5Text13 L"Hide statistics"
#define TrackWindowTitle L"Track Settings"
#define TrackText1 L"File:"
#define TrackText2 L"Folder:"
#define TrackText3 L"Notes:"
#define TrackText4 L"Length:"
#define TrackText5 L"Slow down instead of lag"
#define TrackText6 L"Override instruments with piano"
#define TrackText7 L"Play"
#define TrackText8 L"Abort"
#define AboutWindowTitle L"About"
#define AboutText1 L"Piano-FX Pro v3.06 | Forked from Piano From Above v1.1.0\n\nContributors list: \nHappy_mimimix(25 %) <-Funny special effects && Final optimization\nanon64(5 %) <-Color events support\nKhangaroo(30 %) <-Performance boost\nBrianPantano(40 %) <-Main program"
#define AboutText2 L"OK"
#define LoadWindowTitle L"Loading..."
#define ResolutionWindowTitle L"Set Resolution"
#define ResolutionText1 L"Width:"
#define ResolutionText2 L"Height:"
#define ResolutionText3 L"Confirm"
#define ResolutionText4 L"Cancel"
#define MenuText1 L"Open"
#define MenuText2 L"Close"
#define MenuText3 L"Play"
#define MenuText4 L"Play/Pause\tSpace"
#define MenuText5 L"Stop\tEsc"
#define MenuText6 L"Skip Fwd\tRight"
#define MenuText7 L"Skip Back\tLeft"
#define MenuText8 L"Faster Playback\tCtrl+Down"
#define MenuText9 L"Slower Playback\tCtrl+Up"
#define MenuText10 L"Reset Playback\tCtrl+R"
#define MenuText11 L"Faster Notes\tShift+Up"
#define MenuText12 L"Slower Notes\tShift+Down"
#define MenuText13 L"Reset Notes\tShift+R"
#define MenuText14 L"Volume Up\tUp"
#define MenuText15 L"Volume Down\tDown"
#define MenuText16 L"Mute\tCtrl+M"
#define MenuText17 L"View"
#define MenuText18 L"Playback Toolbar"
#define MenuText19 L"Keyboard"
#define MenuText20 L"Always On Top"
#define MenuText21 L"Full Screen\tAlt+Enter"
#define MenuText22 L"Set Window Size\tCtrl+W"
#define MenuText23 L"Move And Zoom"
#define MenuText24 L"Reset Move And Zoom"
#define MenuText25 L"Preferences"
#define MenuText26 L"About"
#define MenuText27 L"Open Piano-FX Studio"
#endif
#ifdef CHN
#define MainWindowTitle1 L"专业の钢琴特效"
#define MainWindowTitle2 L"开发者：happy_mimimix"
#define MainWindowTitle3 L"正在播放："
#define MainWindowTitle4 L"正在渲染："
#define MainWindowTitle5 L"无"
#define MainWindowTitle6 L"欢迎MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (强制软件渲染)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"欢迎使用 专业の钢琴特效"
#define StartupStage1Text L"准备中……"
#define StartupStage2Text L"加载欢迎MIDI……"
#define StartupStage3Text L"让我们开始吧！"
#define DigitSeparate 4
#define StatisticsText1 "专业の钢琴特效"
#define StatisticsText2 "开发者: happy_mimimix"
#define StatisticsText3 "时长"
#define StatisticsText4 "Tick:"
#define StatisticsText5 "微秒:"
#define StatisticsText6 "帧率:"
#define StatisticsText7 "BPM:"
#define StatisticsText8 "连击:"
#define StatisticsText9 "每秒手速:"
#define StatisticsText10 "手指个数:"
#define StatisticsText11 "音符数:"
#define StatisticsText12 "每秒演奏:"
#define StatisticsText13 "同时演奏:"
#define StatisticsText14 "已渲染:"
#define StatisticsText15 "音量:"
#define StatisticsText16 "静音"
#define StatisticsText17 "播放速度:"
#define StatisticsText18 "音符速度:"
#define StatisticsText19 "X偏移:"
#define StatisticsText20 "Y偏移:"
#define StatisticsText21 "缩放:"
#define StatisticsText22 "窗口大小:"
#define StatisticsText23 "琴键范围:"
#define StatisticsText24 "分数:"
#define StatisticsText25 "难度:"
#define StatisticsText26 "自动播放:"
#define StatisticsText27 "开启 "
#define StatisticsText28 "恭喜全连!!! "
#define StatisticsText29 "奥托普雷演示中... "
#define StatisticsText30 "游戏暂停... "
#define StatisticsText31 "错误: 分数溢出! "
#define PropertyWindowTitle L"属性"
#define Property1Title L"视频"
#define Property1Text1 L"琴键显示"
#define Property1Text2 L"全部128键"
#define Property1Text3 L"自适应"
#define Property1Text4 L"指定范围:"
#define Property1Text5 L"至"
#define Property1Text6 L"全屏模式下不隐藏工具条  "
#define Property1Text7 L"等宽音符"
#define Property1Text8 L"音轨颜色:  "
#define Property1Text9 L"背景颜色:  "
#define Property1Text10 L"横条颜色:  "
#define Property1Text11 L"重置默认颜色"
#define Property2Title L"音频"
#define Property2Text1 L"标准WinMM输出:  "
#define Property2Text2 L"使用更高效的KDMAPI代替WinMM (需要 OmniMIDI)  "
#define Property3Title L"渲染"
#define Property3Text1 L"渲染选项"
#define Property3Text2 L"显示调试信息"
#define Property3Text3 L"锁定帧率至60"
#define Property4Title L"控制"
#define Property4Text1 L"控制选项"
#define Property4Text2 L"左右箭头跳过：  "
#define Property4Text3 L"秒"
#define Property4Text4 L"上下箭头加速：  "
#define Property4Text5 L"%"
#define Property5Title L"其他"
#define Property5Text1 L"其他选项"
#define Property5Text2 L"基于Tick渲染"
#define Property5Text3 L"可视化弯音"
#define Property5Text4 L"仿Phigros计分系统"
#define Property5Text5 L"显示标记"
#define Property5Text6 L"标记文本编码方式：   "
#define Property5Text7 L"欢迎MIDI:  "
#define Property5Text8 L"背景图片:  "
#define Property5Text9 L"浏览"
#define Property5Text10 L"重置"
#define Property5Text11 L"循环音轨颜色"
#define Property5Text12 L"导出视频"
#define Property5Text13 L"隐藏统计数据"
#define TrackWindowTitle L"音轨设置"
#define TrackText1 L"文件名:"
#define TrackText2 L"路径:"
#define TrackText3 L"音符数:"
#define TrackText4 L"时长:"
#define TrackText5 L"减速而不是卡顿"
#define TrackText6 L"将所有乐器替换为钢琴"
#define TrackText7 L"播放"
#define TrackText8 L"终止"
#define AboutWindowTitle L"关于"
#define AboutText1 L"专业の钢琴特效 v3.06 (中文版) | 改编自Piano From Above v1.1.0\n\n贡献者列表: \nHappy_mimimix(25 %) <-Funny special effects && Final optimization\nanon64(5 %) <-Color events support\nKhangaroo(30 %) <-Performance boost\nBrianPantano(40 %) <-Main program"
#define AboutText2 L"好"
#define LoadWindowTitle L"加载中..."
#define ResolutionWindowTitle L"设置分辨率"
#define ResolutionText1 L"宽度:"
#define ResolutionText2 L"高度:"
#define ResolutionText3 L"确认"
#define ResolutionText4 L"取消"
#define MenuText1 L"打开"
#define MenuText2 L"关闭"
#define MenuText3 L"播放"
#define MenuText4 L"播放/暂停\tSpace"
#define MenuText5 L"停止\tEsc"
#define MenuText6 L"快进\tRight"
#define MenuText7 L"快退\tLeft"
#define MenuText8 L"播放加速\tCtrl+Down"
#define MenuText9 L"播放减速\tCtrl+Up"
#define MenuText10 L"播放重置\tCtrl+R"
#define MenuText11 L"音符加速\tShift+Up"
#define MenuText12 L"音符减速\tShift+Down"
#define MenuText13 L"音符重置\tShift+R"
#define MenuText14 L"音量加\tUp"
#define MenuText15 L"音量减\tDown"
#define MenuText16 L"静音\tCtrl+M"
#define MenuText17 L"查看"
#define MenuText18 L"工具条"
#define MenuText19 L"键盘"
#define MenuText20 L"置顶"
#define MenuText21 L"全屏\tAlt+Enter"
#define MenuText22 L"设置窗口大小\tCtrl+W"
#define MenuText23 L"移动和缩放"
#define MenuText24 L"重置移动和缩放"
#define MenuText25 L"设置"
#define MenuText26 L"关于"
#define MenuText27 L"钢琴特效编辑器"
#endif
#ifdef ARN
#define MainWindowTitle1 L"专业の钢琴特效"
#define MainWindowTitle2 L"开发者：happy_mimimix"
#define MainWindowTitle3 L"正在播放："
#define MainWindowTitle4 L"正在渲染："
#define MainWindowTitle5 L"无"
#define MainWindowTitle6 L"欢迎MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (强制软件渲染)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"欢迎使用 专业の钢琴特效"
#define StartupStage1Text L"准备中……"
#define StartupStage2Text L"加载欢迎MIDI……"
#define StartupStage3Text L"让我们开始吧！"
#define DigitSeparate 3
#define StatisticsText1 "专业の钢琴特效"
#define StatisticsText2 "开发者: happy_mimimix"
#define StatisticsText3 "时长"
#define StatisticsText4 "Tick:"
#define StatisticsText5 "微秒:"
#define StatisticsText6 "帧率:"
#define StatisticsText7 "BPM:"
#define StatisticsText8 "连击:"
#define StatisticsText9 "每秒手速:"
#define StatisticsText10 "手指个数:"
#define StatisticsText11 "音符数:"
#define StatisticsText12 "每秒演奏:"
#define StatisticsText13 "同时演奏:"
#define StatisticsText14 "已渲染:"
#define StatisticsText15 "音量:"
#define StatisticsText16 "静音"
#define StatisticsText17 "播放速度:"
#define StatisticsText18 "音符速度:"
#define StatisticsText19 "X偏移:"
#define StatisticsText20 "Y偏移:"
#define StatisticsText21 "缩放:"
#define StatisticsText22 "窗口大小:"
#define StatisticsText23 "琴键范围:"
#define StatisticsText24 "分数:"
#define StatisticsText25 "难度:"
#define StatisticsText26 "自动播放:"
#define StatisticsText27 "开启 "
#define StatisticsText28 "恭喜全连!!! "
#define StatisticsText29 "奥托普雷演示中... "
#define StatisticsText30 "游戏暂停... "
#define StatisticsText31 "错误: 分数溢出! "
#define PropertyWindowTitle L"属性"
#define Property1Title L"视频"
#define Property1Text1 L"琴键显示"
#define Property1Text2 L"全部128键"
#define Property1Text3 L"自适应"
#define Property1Text4 L"指定范围:"
#define Property1Text5 L"至"
#define Property1Text6 L"全屏模式下不隐藏工具条  "
#define Property1Text7 L"等宽音符"
#define Property1Text8 L"音轨颜色:  "
#define Property1Text9 L"背景颜色:  "
#define Property1Text10 L"横条颜色:  "
#define Property1Text11 L"重置默认颜色"
#define Property2Title L"Audio"
#define Property2Text1 L"Standard WinMM output:"
#define Property2Text2 L"Use more efficient KDMAPI instead of WinMM (Requires OmniMIDI)"
#define Property3Title L"Render"
#define Property3Text1 L"Render options"
#define Property3Text2 L"Show debug information"
#define Property3Text3 L"Lock FPS to 60"
#define Property4Title L"Control"
#define Property4Text1 L"Control options"
#define Property4Text2 L"Left and right arrows skips the song by:"
#define Property4Text3 L"seconds"
#define Property4Text4 L"Up and down arrows speeds up the playback by:"
#define Property4Text5 L"percent"
#define Property5Title L"Other"
#define Property5Text1 L"Other options"
#define Property5Text2 L"Tick-based rendering"
#define Property5Text3 L"Visualize pitch bends"
#define Property5Text4 L"Phigros style scoring system"
#define Property5Text5 L"Show markers"
#define Property5Text6 L"Marker text encoding:"
#define Property5Text7 L"Splash MIDI:"
#define Property5Text8 L"Background:"
#define Property5Text9 L"Browse"
#define Property5Text10 L"Reset"
#define Property5Text11 L"Color loop"
#define Property5Text12 L"Video output"
#define Property5Text13 L"Hide statistics"
#define TrackWindowTitle L"Track Settings"
#define TrackText1 L"File:"
#define TrackText2 L"Folder:"
#define TrackText3 L"Notes:"
#define TrackText4 L"Length:"
#define TrackText5 L"Slow down instead of lag"
#define TrackText6 L"Override instruments with piano"
#define TrackText7 L"Play"
#define TrackText8 L"Abort"
#define AboutWindowTitle L"About"
#define AboutText1 L"Piano-FX Pro v3.06 | Forked from Piano From Above v1.1.0\n\nContributors list: \nHappy_mimimix(25 %) <-Funny special effects && Final optimization\nanon64(5 %) <-Color events support\nKhangaroo(30 %) <-Performance boost\nBrianPantano(40 %) <-Main program"
#define AboutText2 L"OK"
#define LoadWindowTitle L"Loading..."
#define ResolutionWindowTitle L"Set Resolution"
#define ResolutionText1 L"Width:"
#define ResolutionText2 L"Height:"
#define ResolutionText3 L"Confirm"
#define ResolutionText4 L"Cancel"
#define MenuText1 L"Open"
#define MenuText2 L"Close"
#define MenuText3 L"Play"
#define MenuText4 L"Play/Pause\tSpace"
#define MenuText5 L"Stop\tEsc"
#define MenuText6 L"Skip Fwd\tRight"
#define MenuText7 L"Skip Back\tLeft"
#define MenuText8 L"Faster Playback\tCtrl+Down"
#define MenuText9 L"Slower Playback\tCtrl+Up"
#define MenuText10 L"Reset Playback\tCtrl+R"
#define MenuText11 L"Faster Notes\tShift+Up"
#define MenuText12 L"Slower Notes\tShift+Down"
#define MenuText13 L"Reset Notes\tShift+R"
#define MenuText14 L"Volume Up\tUp"
#define MenuText15 L"Volume Down\tDown"
#define MenuText16 L"Mute\tCtrl+M"
#define MenuText17 L"View"
#define MenuText18 L"Playback Toolbar"
#define MenuText19 L"Keyboard"
#define MenuText20 L"Always On Top"
#define MenuText21 L"Full Screen\tAlt+Enter"
#define MenuText22 L"Set Window Size\tCtrl+W"
#define MenuText23 L"Move And Zoom"
#define MenuText24 L"Reset Move And Zoom"
#define MenuText25 L"Preferences"
#define MenuText26 L"About"
#define MenuText27 L"Open Piano-FX Studio"
#endif

