#define AboutText1 L"Piano-FX Pro v4.2 | Forked from Piano From Above v1.1.0\n\nContributors list: \nHappy_mimimix(25 %) <-Funny special effects && Final optimization\nanon64(5 %) <-Color events support\nKhangaroo(30 %) <-Performance boost\nBrianPantano(40 %) <-Main program"
#ifdef ENG
#define MainWindowTitle1 L"Piano-FX Pro"
#define MainWindowTitle2 L"Developed by: happy_mimimix"
#define MainWindowTitle3 L"Now playing: "
#define MainWindowTitle4 L"Now rendering: "
#define MainWindowTitle5 L"None"
#define MainWindowTitle6 L"Splash MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (Enforced Software Rendering)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"Welcome to Piano-FX Pro"
#define StartupStage1Text L"Preparing..."
#define StartupStage2Text L"Loading splash midi..."
#define StartupStage3Text L"Let's go!"
#define OpenFileTitle L"Please select the file you want to play: "
#define OpenSplashFileTitle L"Please select your desired splash screen MIDI: "
#define OpenBackgroundFileTitle L"Please select your desired background image: "
#define DigitSeparate 3
#define StatisticsText1 "Piano-FX Pro"
#define StatisticsText2 "Developed by: happy_mimimix"
#define StatisticsText3 "Time:"
#define StatisticsText4 "Tick:"
#define StatisticsText5 "Microseconds:"
#define StatisticsText6 "FPS:"
#define StatisticsText7 "Tempo:"
#define StatisticsText8 "Combo:"
#define StatisticsText9 "ClicksPerSecond:"
#define StatisticsText10 "SimultaneousPresses:"
#define StatisticsText11 "Notes:"
#define StatisticsText12 "NotesPerSecond:"
#define StatisticsText13 "Polyphony:"
#define StatisticsText14 "Rendered:"
#define StatisticsText15 "Volume:"
#define StatisticsText16 "MUTED"
#define StatisticsText17 "PlaybackSpeed:"
#define StatisticsText18 "NoteSpeed:"
#define StatisticsText19 "Offset-X:"
#define StatisticsText20 "Offset-Y:"
#define StatisticsText21 "Zoom:"
#define StatisticsText22 "WindowSize:"
#define StatisticsText23 "KeyRange:"
#define StatisticsText24 "VelocityThreshold:"
#define StatisticsText25 "Score:"
#define StatisticsText26 "Level:"
#define StatisticsText27 "AutoPlay:"
#define StatisticsText28 "ON "
#define StatisticsText29 "FULL COMBO!!! "
#define StatisticsText30 "Demonstration in progress... "
#define StatisticsText31 "Game paused... "
#define StatisticsText32 "ERROR: Score overflow! "
#define ZoomMoveMsg "- Left-click and drag to move the screen\n- Right-click and drag to zoom horizontally\n- Click 'View -> Move And Zoom' again to apply changes\n- Click 'View -> Reset Move And Zoom' to revert changes"
#define PropertyWindowTitle L"Preferences"
#define Property1Title "Visual"
#define Property1Text1 "Keys to display:"
#define Property1Text2 "Show all 128 keys"
#define Property1Text3 "Show song keys"
#define Property1Text4 "Show keys:"
#define Property1Text5 "through"
#define Property1Text6 "Track colors:"
#define Property1Text7 "Randomize"
#define Property1Text8 "Background color:"
#define Property1Text9 "Bar color:"
#define Property1Text10 "Restore Defaults Colors"
#define Property1Text11 "Background image:"
#define Property1Text12 "Browse"
#define Property1Text13 "Reset"
#define Property1Text14 "Hint: Visit the 'Render' category for more advanced graphics rendering options. "
#define Property2Title L"Audio"
#define Property2Text1 "Standard WinMM output:"
#define Property2Text2 "Use more efficient KDMAPI instead of WinMM (Requires OmniMIDI)"
#define Property3Title L"Render"
#define Property3Text1 "Advanced graphics rendering config:"
#define Property3Text2 "Tick-based rendering"
#define Property3Text3 "Visualize pitch bends"
#define Property3Text4 "Same width notes"
#define Property3Text5 "Show markers"
#define Property3Text6 "Marker text encoding:"
#define Property3Text7 "Lock FPS to 60"
#define Property3Text8 "Video output"
#define Property3Text9 "Show debug information"
#define Property3Text10 "Hide statistics"
#define Property3Text11 "Hide overlapping notes"
#define Property4Title L"Control"
#define Property4Text1 "Controls' behavior:"
#define Property4Text2 "Left and right arrows skip the song by:"
#define Property4Text3 "seconds"
#define Property4Text4 "Up and down arrows speed up the song by:"
#define Property4Text5 "percent"
#define Property4Text6 "Don't hide playback toolbar in full screen mode"
#define Property4Text7 "Phigros style scoring system"
#define Property4Text8 "Splash MIDI:"
#define Property4Text9 "Velocity threshold:"
#define TrackWindowTitle "Track Settings"
#define TrackText1 "File:"
#define TrackText2 "Folder:"
#define TrackText3 "Notes:"
#define TrackText4 "Length:"
#define TrackText5 "Slow down instead of lag"
#define TrackText6 "Override instruments with piano"
#define TrackText7 "Play"
#define TrackText8 "Abort"
#define AboutWindowTitle "About"
#define AboutText2 "OK"
#define LoadWindowTitle L"Loading..."
#define LoadingText "Loading"
#define LoadingStage1 L"Copying MIDI into memory..."
#define LoadingStage2 L"Decompressing..."
#define LoadingStage3 L"Parsing tracks..."
#define LoadingStage4 L"Connecting notes..."
#define LoadingStage5 L"Sorting events..."
#define LoadingStage6 L"Preparing note count lookup table..."
#define ResolutionWindowTitle "Set Resolution"
#define ResolutionText1 "Width:"
#define ResolutionText2 "Height:"
#define ResolutionText3 "Confirm"
#define ResolutionText4 "Cancel"
#define MenuText1 "Open"
#define MenuText2 "Close"
#define MenuText3 "Play"
#define MenuText4 "Play/Pause\tSpace"
#define MenuText5 "Stop\tEsc"
#define MenuText6 "Skip Fwd\tRight"
#define MenuText7 "Skip Back\tLeft"
#define MenuText8 "Faster Playback\tCtrl+Down"
#define MenuText9 "Slower Playback\tCtrl+Up"
#define MenuText10 "Reset Playback\tCtrl+R"
#define MenuText11 "Faster Notes\tShift+Up"
#define MenuText12 "Slower Notes\tShift+Down"
#define MenuText13 "Reset Notes\tShift+R"
#define MenuText14 "Volume Up\tUp"
#define MenuText15 "Volume Down\tDown"
#define MenuText16 "Mute\tCtrl+M"
#define MenuText17 "View"
#define MenuText18 "Playback Toolbar"
#define MenuText19 "Keyboard"
#define MenuText20 "Always On Top"
#define MenuText21 "Full Screen\tAlt+Enter"
#define MenuText22 "Set Window Size\tCtrl+W"
#define MenuText23 "Move And Zoom"
#define MenuText24 "Reset Move And Zoom"
#define MenuText25 "Preferences"
#define MenuText26 "About"
#define MenuText27 "Open Piano-FX Studio"
#endif
#ifdef CHN
#define MainWindowTitle1 L"专业の钢琴特效"
#define MainWindowTitle2 L"开发者：happy_mimimix"
#define MainWindowTitle3 L"正在播放："
#define MainWindowTitle4 L"正在渲染："
#define MainWindowTitle5 L"无"
#define MainWindowTitle6 L"欢迎MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (强制软件渲染)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"欢迎使用 专业の钢琴特效"
#define StartupStage1Text L"准备中……"
#define StartupStage2Text L"加载欢迎MIDI……"
#define StartupStage3Text L"让我们开始吧！"
#define OpenFileTitle L"请选择您想要播放的文件: "
#define OpenSplashFileTitle L"请选择您希望作为欢迎画面的文件: "
#define OpenBackgroundFileTitle L"请选择您希望作为背景图像的文件: "
#define DigitSeparate 4
#define StatisticsText1 "专业の钢琴特效 (中文版)"
#define StatisticsText2 "开发者: happy_mimimix"
#define StatisticsText3 "时长:"
#define StatisticsText4 "刻:"
#define StatisticsText5 "微秒:"
#define StatisticsText6 "帧率:"
#define StatisticsText7 "歌曲速率:"
#define StatisticsText8 "连击:"
#define StatisticsText9 "每秒手速:"
#define StatisticsText10 "手指个数:"
#define StatisticsText11 "音符数:"
#define StatisticsText12 "每秒演奏:"
#define StatisticsText13 "同时演奏:"
#define StatisticsText14 "已渲染:"
#define StatisticsText15 "音量:"
#define StatisticsText16 "静音"
#define StatisticsText17 "播放速度:"
#define StatisticsText18 "音符速度:"
#define StatisticsText19 "X偏移:"
#define StatisticsText20 "Y偏移:"
#define StatisticsText21 "缩放:"
#define StatisticsText22 "窗口大小:"
#define StatisticsText23 "琴键范围:"
#define StatisticsText24 "音符力度阈值:"
#define StatisticsText25 "分数:"
#define StatisticsText26 "难度:"
#define StatisticsText27 "自动播放:"
#define StatisticsText28 "开启 "
#define StatisticsText29 "恭喜全连!!! "
#define StatisticsText30 "奥托普雷演示中... "
#define StatisticsText31 "游戏暂停... "
#define StatisticsText32 "错误: 分数溢出! "
#define ZoomMoveMsg "- 左键单击并拖动可移动屏幕\n- 右键单击并拖动可水平缩放\n- 再次点击“查看->移动和缩放”可应用更改\n- 点击“查看->重置移动和缩放”可撤销更改"
#define PropertyWindowTitle L"属性"
#define Property1Title L"视觉"
#define Property1Text1 "琴键显示:"
#define Property1Text2 "全部128键"
#define Property1Text3 "自适应"
#define Property1Text4 "指定范围:"
#define Property1Text5 "至"
#define Property1Text6 "音轨颜色:"
#define Property1Text7 "随机"
#define Property1Text8 "背景颜色:"
#define Property1Text9 "横条颜色:"
#define Property1Text10 "重置默认颜色"
#define Property1Text11 "背景图片:"
#define Property1Text12 "浏览"
#define Property1Text13 "重置"
#define Property1Text14 "提示：前往“渲染”类别查看更多高级图形渲染选项。"
#define Property2Title L"音频"
#define Property2Text1 "标准WinMM输出:"
#define Property2Text2 "使用更高效的KDMAPI代替WinMM (需要 OmniMIDI)"
#define Property3Title L"渲染"
#define Property3Text1 "高级图形渲染选项:"
#define Property3Text2 "基于刻渲染"
#define Property3Text3 "可视化弯音"
#define Property3Text4 "等宽音符"
#define Property3Text5 "显示标记"
#define Property3Text6 "文本编码格式:"
#define Property3Text7 "锁定帧率至60"
#define Property3Text8 "导出视频"
#define Property3Text9 "显示调试信息"
#define Property3Text10 "隐藏统计数据"
#define Property3Text11 "隐藏重叠音符"
#define Property4Title L"控制"
#define Property4Text1 "按键行为:"
#define Property4Text2 "左右箭头跳过:"
#define Property4Text3 "秒"
#define Property4Text4 "上下箭头加速:"
#define Property4Text5 "%"
#define Property4Text6 "全屏模式下不隐藏工具条"
#define Property4Text7 "仿Phigros计分系统"
#define Property4Text8 "欢迎MIDI:"
#define Property4Text9 "音符力度阈值:"
#define TrackWindowTitle "音轨设置"
#define TrackText1 "文件名:"
#define TrackText2 "路径:"
#define TrackText3 "音符数:"
#define TrackText4 "时长:"
#define TrackText5 "减速而不是卡顿"
#define TrackText6 "将所有乐器替换为钢琴"
#define TrackText7 "播放"
#define TrackText8 "终止"
#define AboutWindowTitle "关于"
#define AboutText2 "好"
#define LoadWindowTitle L"加载中..."
#define LoadingText "正在读取"
#define LoadingStage1 L"正在将文件复制到内存..."
#define LoadingStage2 L"正在解压缩..."
#define LoadingStage3 L"正在解析音轨..."
#define LoadingStage4 L"正在连接音符..."
#define LoadingStage5 L"正在整理事件..."
#define LoadingStage6 L"正在准备音符计数查表..."
#define ResolutionWindowTitle "设置分辨率"
#define ResolutionText1 "宽度:"
#define ResolutionText2 "高度:"
#define ResolutionText3 "确认"
#define ResolutionText4 "取消"
#define MenuText1 "打开"
#define MenuText2 "关闭"
#define MenuText3 "演奏"
#define MenuText4 "播放/暂停\tSpace"
#define MenuText5 "停止\tEsc"
#define MenuText6 "快进\tRight"
#define MenuText7 "快退\tLeft"
#define MenuText8 "播放加速\tCtrl+Down"
#define MenuText9 "播放减速\tCtrl+Up"
#define MenuText10 "播放重置\tCtrl+R"
#define MenuText11 "音符加速\tShift+Up"
#define MenuText12 "音符减速\tShift+Down"
#define MenuText13 "音符重置\tShift+R"
#define MenuText14 "音量加\tUp"
#define MenuText15 "音量减\tDown"
#define MenuText16 "静音\tCtrl+M"
#define MenuText17 "查看"
#define MenuText18 "工具条"
#define MenuText19 "键盘"
#define MenuText20 "置顶"
#define MenuText21 "全屏\tAlt+Enter"
#define MenuText22 "设置窗口大小\tCtrl+W"
#define MenuText23 "移动和缩放"
#define MenuText24 "重置移动和缩放"
#define MenuText25 "设置"
#define MenuText26 "关于"
#define MenuText27 "钢琴特效编辑器"
#endif
#ifdef ARN
#define MainWindowTitle1 L"ZHUAN1 YE4 DE5 GANG1 QIN2 TE4 XIAO4"
#define MainWindowTitle2 L"KAI1 FA1 ZHE3: happy_mimimix"
#define MainWindowTitle3 L"ZHENG4 ZAI4 BO1 FANG4: "
#define MainWindowTitle4 L"ZHENG4 ZAI4 XUAN4 RAN3: "
#define MainWindowTitle5 L"KONG4 XIAN2"
#define MainWindowTitle6 L"HUAN1 YING2 MIDI+"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (QIANG2 ZHI4 RUAN3 JIAN4 XUAN4 RAN3)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"HUAN1 YING2 SHI3 YONG4 ZHUAN1 YE4 DE5 GANG1 QIN2 TE4 XIAO4"
#define StartupStage1Text L"ZHUN3 BEI4 ZHONG1..."
#define StartupStage2Text L"ZAI3 RU4 HUAN1 YING2 MIDI+"
#define StartupStage3Text L"CHU1 FA1! "
#define OpenFileTitle L"QING3 XUAN3 QU3 NIN2 XIANG3 YAO4 BO1 FANG4 DE5 WEN2 JIAN4: "
#define OpenSplashFileTitle L"QING3 XUAN3 QU3 NIN2 XI1 WANG4 YONG4 ZUO4 HUAN1 YING2 PING2 MU4 DE5 WEN2 JIAN4: "
#define OpenBackgroundFileTitle L"QING3 XUAN3 QU3 NIN2 XI1 WANG4 YONG4 ZUO4 BEI4 JING3 TU2 XIANG4 DE5 WEN2 JIAN4: "
#define DigitSeparate 3
#define StatisticsText1 "Piano-FX Pro (Arinoglish)"
#define StatisticsText2 "KAI1 FA1 ZHE3: happy_mimimix"
#define StatisticsText3 "SHI2 CHANG2:"
#define StatisticsText4 "KE4:"
#define StatisticsText5 "WEI1 MIAO3:"
#define StatisticsText6 "ZHEN1 LV4:"
#define StatisticsText7 "YIN1 YU4 SU4 LV4:"
#define StatisticsText8 "LIAN2 JI1:"
#define StatisticsText9 "MEI3 MIAO3 SHOU3 SU4:"
#define StatisticsText10 "SHOU3 ZHI3 GE4 SHU4:"
#define StatisticsText11 "YIN1 FU2 SHU4:"
#define StatisticsText12 "MEI3 MIAO3 YAN3 ZOU4:"
#define StatisticsText13 "TONG2 SHI2 YAN3 ZOU4:"
#define StatisticsText14 "YI3 XUAN4 RAN3:"
#define StatisticsText15 "YIN1 LIANG4:"
#define StatisticsText16 "JING4 YIN1"
#define StatisticsText17 "BO1 FANG4 SU4 DU5:"
#define StatisticsText18 "YIN1 FU2 SU4 DU5:"
#define StatisticsText19 "X PIAN1 YI2:"
#define StatisticsText20 "Y PIAN1 YI2:"
#define StatisticsText21 "SUO1 FANG4:"
#define StatisticsText22 "CHUANG1 KOU3 DA4 XIAO3:"
#define StatisticsText23 "QIN2 JIAN4 FAN4 WEI2:"
#define StatisticsText24 "YIN1 FU2 LI4 DU4 YU4 ZHI2:"
#define StatisticsText25 "FEN1 SHU4:"
#define StatisticsText26 "QU3 MU4 NAN2 DU4:"
#define StatisticsText27 "ZI4 DONG4 YAN3 ZOU4:"
#define StatisticsText28 "KAI1 QI3 "
#define StatisticsText29 "GON1 XI3 QUAN2 LIAN2!!! "
#define StatisticsText30 "ZI4 DONG4 YAN3 SHI4 ZHONG1... "
#define StatisticsText31 "YOU2 XI4 ZAN4 TING2... "
#define StatisticsText32 "CUO4 WU4: FEN1 SHU4 YI4 CHU1! "
#define ZoomMoveMsg "- ZUO3 JIAN4 DAN1 JI1 BING4 TUO1 DONG4 KE3 YI2 DONG4 PING2 MU4\n- YOU4 JIAN4 DAN1 JI1 BING4 TUO1 DONG1 KE3 SHUI3 PING2 SUO1 FANG4\n- ZAI4 CI4 DIAN3 JI1 'CHA2 KAN4 -> YI2 DONG4 HE2 SUO1 FANG4' KE3 YING4 YONG4 GENG1 GAI3\n- DIAN3 JI1 'CHA2 KAN4 -> CHONG2 ZHI4 YI2 DONG4 HE2 SUO1 FANG4' KE3 CHE4 XIAO1 GENG1 GAI3"
#define PropertyWindowTitle L"SHE4 ZHI4"
#define Property1Title L"SHI4 JUE2"
#define Property1Text1 "QIN2 JIAN4 XIAN3 SHI4:"
#define Property1Text2 "QUAN2 BU4 128 JIAN4"
#define Property1Text3 "GEN1 JU4 MIDI+ ZI4 SHI4 YING4"
#define Property1Text4 "ZHI3 DING4 FAN4 WEI2:"
#define Property1Text5 "ZHI2 DAO4"
#define Property1Text6 "YIN1 GUI3 YAN2 SE4:"
#define Property1Text7 "SUI2 JI1"
#define Property1Text8 "BEI4 JING3 YAN2 SE4:"
#define Property1Text9 "HENG2 TIAO2 YAN2 SE4:"
#define Property1Text10 "CHONG2 ZHI4 YAN2 SE4"
#define Property1Text11 "BEI4 JING3 TU2 PIAN4:"
#define Property1Text12 "LIU2 LAN3"
#define Property1Text13 "CHONG2 ZHI4"
#define Property1Text14 "QIAN2 WANG3 'XUAN4 RAN3' LEI4 BIE2 CHA2 KAN4 GENG4 DUO1 GAO1 JI2 XUAN4 RAN3 SHE4 ZHI4."
#define Property2Title L"YIN1 PIN2"
#define Property2Text1 "BIAO1 ZHUN3 WINMM+ SHU1 CHU1:"
#define Property2Text2 "SHI3 YONG4 KDMAPI+ DAI4 TI4 WINMM+ (XU1 YAO4 OMNI MIDI+)"
#define Property3Title L"XUAN4 RAN3"
#define Property3Text1 "GAO1 JI2 TU2 XING2 XUAN4 RAN3 PEI4 ZHI4:"
#define Property3Text2 "JI1 YU2 KE4 XUAN4 RAN3"
#define Property3Text3 "KE3 SHI4 HUA4 WAN1 YIN1"
#define Property3Text4 "DENG3 KUAN1 YIN1 FU2"
#define Property3Text5 "XIAN3 SHI4 BIAO1 JI4"
#define Property3Text6 "WEN2 BEN3 BIAN1 MA3 GE2 SHI4:"
#define Property3Text7 "SUO3 DING4 ZHEN1 LV4 ZHI4 60 ZHEN1"
#define Property3Text8 "DAO3 CHU1 SHI4 PIN2"
#define Property3Text9 "XIAN3 SHI4 TIAO2 SHI4 XIN4 XI1"
#define Property3Text10 "YIN3 CANG2 TONG3 JI4 XIN4 XI1"
#define Property3Text11 "YIN3 CANG2 CHONG2 DIE2 YIN1 FU2"
#define Property4Title L"KONG4 ZHI4"
#define Property4Text1 "KONG4 ZHI4 XING2 WEI2 SHE4 ZHI4:"
#define Property4Text2 "ZUO3 YOU4 JIAN4 TOU2 TIAO4 GUO4:"
#define Property4Text3 "MIAO3"
#define Property4Text4 "SHANG4 XIA4 JIAN4 TOU2 JIA1 SU4:"
#define Property4Text5 "FEN1 ZHI1 BAI3"
#define Property4Text6 "QUAN2 PING2 MO2 SHI4 XIA4 BU4 YIN3 CANG2 GONG1 JU4 TIAO2"
#define Property4Text7 "PHIGROS+ FENG1 GE2 JI4 FEN1 XI4 TONG3"
#define Property4Text8 "HUAN1 YING2 MIDI+:"
#define Property4Text9 "YIN1 FU2 LI4 DU4 YU4 ZHI2:"
#define TrackWindowTitle "YIN1 GUI3 SHE4 ZHI4"
#define TrackText1 "WEN3 JIAN4:"
#define TrackText2 "LU4 JING4:"
#define TrackText3 "YIN1 FU2 SHU4:"
#define TrackText4 "SHI1 CHANG2:"
#define TrackText5 "JIAN3 SU4 ER2 BU2 SHI4 KA3 DUN4"
#define TrackText6 "JIANG1 SUO3 YOU3 YUE4 QI4 TI4 HUAN4 CHENG2 GANG1 QIN2"
#define TrackText7 "BO1 FANG4"
#define TrackText8 "ZHONG1 ZHI3"
#define AboutWindowTitle "GUAN1 YU2"
#define AboutText2 "HAO3 DE5"
#define LoadWindowTitle L"JIA1 ZAI3 ZHONG1..."
#define LoadingText "ZHENG4 ZAI4 DU2 QU3"
#define LoadingStage1 L"ZHENG4 ZAI4 JIANG1 WEN2 JIAN4 FU4 ZHI4 DAO4 NEI4 CUN2..."
#define LoadingStage2 L"ZHENG4 ZAI4 JIE3 YA1 SUO1..."
#define LoadingStage3 L"ZHENG4 ZAI4 JIE3 XI1 YIN1 GUI3..."
#define LoadingStage4 L"ZHENG4 ZAI4 LIAN2 JI1 YIN1 FU2..."
#define LoadingStage5 L"ZHENG4 ZAI4 ZHENG3 LI3 SHI1 JIAN4..."
#define LoadingStage6 L"ZHENG4 ZAI4 ZHUN3 BEI4 YIN1 FU2 JI4 SHU4 CHA2 BIAO3..."
#define ResolutionWindowTitle "SHE4 ZHI4 FEN1 BIAN4 LV4"
#define ResolutionText1 "KUAN1:"
#define ResolutionText2 "GAO1:"
#define ResolutionText3 "QUE4 REN4"
#define ResolutionText4 "QU3 XIAO1"
#define MenuText1 "DA3 KAI1"
#define MenuText2 "GUAN1 BI4"
#define MenuText3 "YAN3 ZOU4"
#define MenuText4 "BO1 FANG4/ZAN4 TING2\tSpace"
#define MenuText5 "TING2 ZHI3\tEsc"
#define MenuText6 "KUAI4 JIN4\tRight"
#define MenuText7 "KUAI4 TUI4\tLeft"
#define MenuText8 "BO1 FANG4 JIA1 SU4\tCtrl+Down"
#define MenuText9 "BO1 FANG4 JIAN3 SU4\tCtrl+Up"
#define MenuText10 "BO1 FANG4 CHONG2 ZHI4\tCtrl+R"
#define MenuText11 "YIN1 FU2 JIA1 SU4\tShift+Up"
#define MenuText12 "YIN1 FU2 JIAN3 SU4\tShift+Down"
#define MenuText13 "CHONG2 ZHI4 YIN1 FU2\tShift+R"
#define MenuText14 "YIN1 LIANG4 JIA1\tUp"
#define MenuText15 "YIN1 LIANG4 JIAN3\tDown"
#define MenuText16 "JING4 YIN1\tCtrl+M"
#define MenuText17 "CHA2 KAN4"
#define MenuText18 "GONG1 JU4 TIAO2"
#define MenuText19 "JIAN4 PAN2"
#define MenuText20 "CHUANG1 KOU3 ZHI4 DING3"
#define MenuText21 "QUAN2 PING2 XIAN3 SHI4\tAlt+Enter"
#define MenuText22 "SHE4 ZHI4 CHUANG1 KOU3 DA4 XIAO3\tCtrl+W"
#define MenuText23 "YI2 DONG4 HE2 SUO1 FANG4"
#define MenuText24 "CHONG2 ZHI4 YI2 DONG4 HE2 SUO1 FANG4"
#define MenuText25 "SHE4 ZHI4"
#define MenuText26 "GUAN1 YU2"
#define MenuText27 "GANG1 QIN2 TE4 XIAO4 BIAN1 JI1 QI4"
#define PropertyWindowW 350
#define ResolutionWindowW 120
#define StatisticsWidth 300
#endif
#ifdef JPN
#define MainWindowTitle1 L"Piano-FX Pro"
#define MainWindowTitle2 L"開発者: happy_mimimix"
#define MainWindowTitle3 L"再生中: "
#define MainWindowTitle4 L"レンダリング中: "
#define MainWindowTitle5 L"なし"
#define MainWindowTitle6 L"スプラッシュMIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (ソフトウェアレンダリング強制)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"Piano-FX Proへようこそ"
#define StartupStage1Text L"準備中..."
#define StartupStage2Text L"スプラッシュMIDIを読み込み中..."
#define StartupStage3Text L"スタート！"
#define OpenFileTitle L"再生するファイルを選択: "
#define OpenSplashFileTitle L"スプラッシュ画面用MIDIを選択: "
#define OpenBackgroundFileTitle L"背景画像を選択: "
#define DigitSeparate 4
#define StatisticsText1 "Piano-FX Pro (日本語)"
#define StatisticsText2 "開発者: happy_mimimix"
#define StatisticsText3 "時間:"
#define StatisticsText4 "ティック:"
#define StatisticsText5 "マイクロ秒:"
#define StatisticsText6 "フレームレート:"
#define StatisticsText7 "曲のテンポ:"
#define StatisticsText8 "コンボ数:"
#define StatisticsText9 "クリック毎秒:"
#define StatisticsText10 "同時押し数:"
#define StatisticsText11 "ノート数:"
#define StatisticsText12 "ノーツパーセカンド:"
#define StatisticsText13 "ポリフォニー:"
#define StatisticsText14 "レンダリング済:"
#define StatisticsText15 "音量:"
#define StatisticsText16 "ミュート中"
#define StatisticsText17 "再生速度:"
#define StatisticsText18 "ノート速度:"
#define StatisticsText19 "Xオフセット:"
#define StatisticsText20 "Yオフセット:"
#define StatisticsText21 "ズーム:"
#define StatisticsText22 "ウィンドウサイズ:"
#define StatisticsText23 "鍵盤範囲:"
#define StatisticsText24 "音符の強度閾値:"
#define StatisticsText25 "スコア:"
#define StatisticsText26 "レベル:"
#define StatisticsText27 "自動演奏:"
#define StatisticsText28 "ON "
#define StatisticsText29 "フルコンボ!!! "
#define StatisticsText30 "デモンストレーション中... "
#define StatisticsText31 "一時停止中... "
#define StatisticsText32 "エラー: スコアオーバーフロー! "
#define ZoomMoveMsg "- 左クリックしてドラッグすると、画面が移動します\n- 右クリックしたままドラッグすると水平方向にズームします\n- 変更を適用するには、もう一度 「表示->移動とズーム 」をクリックします\n- 変更を元に戻すには、「表示->移動とズームをリセット 」をクリックします"
#define PropertyWindowTitle L"設定"
#define Property1Title L"表示"
#define Property1Text1 "表示する鍵盤:"
#define Property1Text2 "全128鍵表示"
#define Property1Text3 "曲に合わせる"
#define Property1Text4 "範囲指定:"
#define Property1Text5 "から"
#define Property1Text6 "トラック色:"
#define Property1Text7 "ランダム化"
#define Property1Text8 "背景色:"
#define Property1Text9 "バー色:"
#define Property1Text10 "デフォルト色に戻す"
#define Property1Text11 "背景画像:"
#define Property1Text12 "参照"
#define Property1Text13 "リセット"
#define Property1Text14 "ヒント: 高度なグラフィック設定は「レンダリング」カテゴリをご確認ください。"
#define Property2Title L"オーディオ"
#define Property2Text1 "標準WinMM出力:"
#define Property2Text2 "KDMAPIを使用 (OmniMIDI必要)"
#define Property3Title L"レンダリング"
#define Property3Text1 "高度なグラフィック設定:"
#define Property3Text2 "ティックベースレンダリング"
#define Property3Text3 "ピッチベンド可視化"
#define Property3Text4 "等幅ノート"
#define Property3Text5 "マーカー表示"
#define Property3Text6 "マーカー文字コード:"
#define Property3Text7 "FPSを60に固定"
#define Property3Text8 "動画出力"
#define Property3Text9 "デバッグ情報表示"
#define Property3Text10 "統計非表示"
#define Property3Text11 "重なり合った音符を非表示にする"
#define Property4Title L"操作"
#define Property4Text1 "操作の動作:"
#define Property4Text2 "左右キーでスキップ:"
#define Property4Text3 "秒"
#define Property4Text4 "上下キーで速度変更:"
#define Property4Text5 "%"
#define Property4Text6 "全画面表示時でもツールバーを表示する"
#define Property4Text7 "Phigros式スコアリング"
#define Property4Text8 "スプラッシュMIDI:"
#define Property4Text9 "音符の強度閾値:"
#define TrackWindowTitle "トラック設定"
#define TrackText1 "ファイル:"
#define TrackText2 "フォルダ:"
#define TrackText3 "ノート数:"
#define TrackText4 "長さ:"
#define TrackText5 "ラグの代わりに減速"
#define TrackText6 "全楽器をピアノに置換"
#define TrackText7 "再生"
#define TrackText8 "中止"
#define AboutWindowTitle "バージョン情報"
#define AboutText2 "OK"
#define LoadWindowTitle L"読み込み中..."
#define LoadingText "読み込み中"
#define LoadingStage1 L"MIDIをメモリにコピー中..."
#define LoadingStage2 L"解凍中..."
#define LoadingStage3 L"音トラックを解析中..."
#define LoadingStage4 L"音符を連結中..."
#define LoadingStage5 L"イベントを整理中..."
#define LoadingStage6 L"音符カウントの照合テーブルを作成中..."
#define ResolutionWindowTitle "解像度設定"
#define ResolutionText1 "幅さ:"
#define ResolutionText2 "高さ:"
#define ResolutionText3 "確定"
#define ResolutionText4 "取消"
#define MenuText1 "開く"
#define MenuText2 "閉じる"
#define MenuText3 "再生"
#define MenuText4 "再生/一時停止\tSpace"
#define MenuText5 "停止\tEsc"
#define MenuText6 "早送り\tRight"
#define MenuText7 "巻き戻し\tLeft"
#define MenuText8 "再生加速\tCtrl+Down"
#define MenuText9 "再生減速\tCtrl+Up"
#define MenuText10 "速度リセット\tCtrl+R"
#define MenuText11 "ノート加速\tShift+Up"
#define MenuText12 "ノート減速\tShift+Down"
#define MenuText13 "ノートリセット\tShift+R"
#define MenuText14 "音量上げ\tUp"
#define MenuText15 "音量下げ\tDown"
#define MenuText16 "ミュート\tCtrl+M"
#define MenuText17 "表示"
#define MenuText18 "コントロールパネル"
#define MenuText19 "鍵盤表示"
#define MenuText20 "最前面表示"
#define MenuText21 "全画面表示\tAlt+Enter"
#define MenuText22 "ウィンドウサイズ設定\tCtrl+W"
#define MenuText23 "移動とズーム"
#define MenuText24 "移動とズームをリセット"
#define MenuText25 "設定"
#define MenuText26 "バージョン情報"
#define MenuText27 "Piano-FX Studioを開く"
#endif
#ifdef KOR
#define MainWindowTitle1 L"Piano-FX Pro"
#define MainWindowTitle2 L"개발자: happy_mimimix"
#define MainWindowTitle3 L"현재 재생: "
#define MainWindowTitle4 L"렌더링 중: "
#define MainWindowTitle5 L"없음"
#define MainWindowTitle6 L"시작 MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (소프트웨어 렌더링 강제)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"Piano-FX Pro에 오신 것을 환영합니다"
#define StartupStage1Text L"준비 중..."
#define StartupStage2Text L"시작 MIDI 불러오는 중..."
#define StartupStage3Text L"시작합니다!"
#define OpenFileTitle L"재생할 파일을 선택하세요: "
#define OpenSplashFileTitle L"시작 화면 MIDI 선택: "
#define OpenBackgroundFileTitle L"배경 이미지 선택: "
#define DigitSeparate 3
#define StatisticsText1 "Piano-FX Pro (한국어)"
#define StatisticsText2 "개발자: happy_mimimix"
#define StatisticsText3 "시간:"
#define StatisticsText4 "틱:"
#define StatisticsText5 "마이크로초:"
#define StatisticsText6 "프레임 속도:"
#define StatisticsText7 "템포:"
#define StatisticsText8 "콤보:"
#define StatisticsText9 "초당 클릭:"
#define StatisticsText10 "동시 입력:"
#define StatisticsText11 "노트 수:"
#define StatisticsText12 "초당 노트:"
#define StatisticsText13 "폴리포니:"
#define StatisticsText14 "렌더링 완료:"
#define StatisticsText15 "볼륨:"
#define StatisticsText16 "음소거"
#define StatisticsText17 "재생 속도:"
#define StatisticsText18 "노트 속도:"
#define StatisticsText19 "X 오프셋:"
#define StatisticsText20 "Y 오프셋:"
#define StatisticsText21 "줌:"
#define StatisticsText22 "창 크기:"
#define StatisticsText23 "건반 범위:"
#define StatisticsText24 "음표의 강도 임계값:"
#define StatisticsText25 "점수:"
#define StatisticsText26 "난이도:"
#define StatisticsText27 "자동 연주:"
#define StatisticsText28 "켬 "
#define StatisticsText29 "풀 콤보!!! "
#define StatisticsText30 "데모 진행 중... "
#define StatisticsText31 "일시 정지... "
#define StatisticsText32 "오류: 점수 오버플로우! "
#define ZoomMoveMsg "- 왼쪽 클릭 후 드래그하여 화면 이동\n- 오른쪽 클릭 후 드래그하여 가로로 확대하기\n- 변경 사항을 적용하려면 “보기->이동 / 확대” 를 다시 클릭합니다\n- 변경 사항을 취소하려면 “보기->위치 초기화” 를 클릭합니다"
#define PropertyWindowTitle L"설정"
#define Property1Title L"화면"
#define Property1Text1 "건반 표시:"
#define Property1Text2 "전체 128건반"
#define Property1Text3 "곡에 맞춤"
#define Property1Text4 "범위 지정:"
#define Property1Text5 "부터"
#define Property1Text6 "트랙 색상:"
#define Property1Text7 "무작위화"
#define Property1Text8 "배경 색상:"
#define Property1Text9 "바 색상:"
#define Property1Text10 "기본값 복원"
#define Property1Text11 "배경 이미지:"
#define Property1Text12 "찾아보기"
#define Property1Text13 "초기화"
#define Property1Text14 "힌트: 고급 그래픽 렌더링 옵션은 '렌더링' 항목에서 확인하세요."
#define Property2Title L"오디오"
#define Property2Text1 "표준 WinMM 출력:"
#define Property2Text2 "KDMAPI 사용 (OmniMIDI 필요)"
#define Property3Title L"렌더링"
#define Property3Text1 "고급 그래픽 렌더링 설정:"
#define Property3Text2 "틱 기반 렌더링"
#define Property3Text3 "피치 벤드 시각화"
#define Property3Text4 "동일 너비 노트"
#define Property3Text5 "마커 표시"
#define Property3Text6 "마커 인코딩:"
#define Property3Text7 "FPS 60으로 고정"
#define Property3Text8 "동영상 출력"
#define Property3Text9 "디버그 정보 표시"
#define Property3Text10 "통계 숨기기"
#define Property3Text11 "중복된 음표를 숨기기"
#define Property4Title L"제어"
#define Property4Text1 "제어 동작 설정:"
#define Property4Text2 "좌우 키 이동량:"
#define Property4Text3 "초"
#define Property4Text4 "상하 키 속도 변경:"
#define Property4Text5 "%"
#define Property4Text6 "전체 화면에서 도구 모음 표시"
#define Property4Text7 "Phigros 스타일 점수"
#define Property4Text8 "시작 MIDI:"
#define Property4Text9 "음표의 강도 임계값:"
#define TrackWindowTitle "트랙 설정"
#define TrackText1 "파일:"
#define TrackText2 "폴더:"
#define TrackText3 "노트 수:"
#define TrackText4 "길이:"
#define TrackText5 "렉 대신 감속"
#define TrackText6 "모든 악기를 피아노로 변경"
#define TrackText7 "재생"
#define TrackText8 "중단"
#define AboutWindowTitle "정보"
#define AboutText2 "확인"
#define LoadWindowTitle L"로딩 중..."
#define LoadingText "불러오는 중"
#define LoadingStage1 L"MIDI 메모리 복사 중..."
#define LoadingStage2 L"압축 해제 중..."
#define LoadingStage3 L"트랙 분석 중..."
#define LoadingStage4 L"노트 연결 중..."
#define LoadingStage5 L"이벤트 정렬 중..."
#define LoadingStage6 L"노트 카운트 조회 테이블 준비 중..."
#define ResolutionWindowTitle "해상도 설정"
#define ResolutionText1 "너비:"
#define ResolutionText2 "높이:"
#define ResolutionText3 "확인"
#define ResolutionText4 "취소"
#define MenuText1 "열기"
#define MenuText2 "닫기"
#define MenuText3 "재생"
#define MenuText4 "재생/일시정지\tSpace"
#define MenuText5 "중지\tEsc"
#define MenuText6 "빨리감기\tRight"
#define MenuText7 "뒤로\tLeft"
#define MenuText8 "빠르게\tCtrl+Down"
#define MenuText9 "느리게\tCtrl+Up"
#define MenuText10 "속도 초기화\tCtrl+R"
#define MenuText11 "노트 빠르게\tShift+Up"
#define MenuText12 "노트 느리게\tShift+Down"
#define MenuText13 "노트 초기화\tShift+R"
#define MenuText14 "볼륨 업\tUp"
#define MenuText15 "볼륨 다운\tDown"
#define MenuText16 "음소거\tCtrl+M"
#define MenuText17 "보기"
#define MenuText18 "제어 패널"
#define MenuText19 "건반 표시"
#define MenuText20 "항상 위"
#define MenuText21 "전체 화면\tAlt+Enter"
#define MenuText22 "창 크기 설정\tCtrl+W"
#define MenuText23 "이동/확대"
#define MenuText24 "위치 초기화"
#define MenuText25 "설정"
#define MenuText26 "정보"
#define MenuText27 "피아노 FX 스튜디오 열기"
#endif
#ifdef RUS
#define MainWindowTitle1 L"Piano-FX Pro"
#define MainWindowTitle2 L"Разработчик: happy_mimimix"
#define MainWindowTitle3 L"Сейчас играет: "
#define MainWindowTitle4 L"Сейчас рендерится: "
#define MainWindowTitle5 L"Нет"
#define MainWindowTitle6 L"Заставка MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (Принудительный программный рендеринг)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"Добро пожаловать в Piano-FX Pro"
#define StartupStage1Text L"Подготовка..."
#define StartupStage2Text L"Загрузка заставки MIDI..."
#define StartupStage3Text L"Поехали!"
#define OpenFileTitle L"Выберите файл для воспроизведения: "
#define OpenSplashFileTitle L"Выберите MIDI-файл для заставки: "
#define OpenBackgroundFileTitle L"Выберите фоновое изображение: "
#define DigitSeparate 3
#define StatisticsText1 "Piano-FX Pro (русский)"
#define StatisticsText2 "Разработчик: happy_mimimix"
#define StatisticsText3 "Время:"
#define StatisticsText4 "Тики:"
#define StatisticsText5 "Микросекунды:"
#define StatisticsText6 "частота кадров:"
#define StatisticsText7 "Темп песни:"
#define StatisticsText8 "Комбо:"
#define StatisticsText9 "Кликов в секунду:"
#define StatisticsText10 "Одновременные прессы:"
#define StatisticsText11 "Ноты:"
#define StatisticsText12 "Нот в секунду:"
#define StatisticsText13 "Полифония:"
#define StatisticsText14 "Отрендерено:"
#define StatisticsText15 "Громкость:"
#define StatisticsText16 "БЕЗ ЗВУКА"
#define StatisticsText17 "Скорость:"
#define StatisticsText18 "Скорость нот:"
#define StatisticsText19 "Смещение X:"
#define StatisticsText20 "Смещение Y:"
#define StatisticsText21 "Масштаб:"
#define StatisticsText22 "Размер окна:"
#define StatisticsText23 "Диапазон клавиш:"
#define StatisticsText24 "Порог интенсивности ноты:"
#define StatisticsText25 "Счет:"
#define StatisticsText26 "Уровень:"
#define StatisticsText27 "Автовоспр:"
#define StatisticsText28 "ВКЛ"
#define StatisticsText29 "ПОЛНЫЙ КОМБО!!! "
#define StatisticsText30 "Демонстрация... "
#define StatisticsText31 "Пауза... "
#define StatisticsText32 "ОШИБКА: Переполнение счета! "
#define ZoomMoveMsg "- Щелкните левой кнопкой мыши и перетащите, чтобы переместить экран\n- Щелкните правой кнопкой мыши и перетащите, чтобы увеличить масштаб по горизонтали\n- Нажмите 'Вид -> Позиция и масштаб' еще раз, чтобы применить изменения\n- Нажмите 'Вид -> Сброс позиции', чтобы отменить изменения"
#define PropertyWindowTitle L"Настройки"
#define Property1Title L"Внешний вид"
#define Property1Text1 "Отображаемые клавиши:"
#define Property1Text2 "Все 128 клавиш"
#define Property1Text3 "По композиции"
#define Property1Text4 "Диапазон:"
#define Property1Text5 "до"
#define Property1Text6 "Цвета дорожек:"
#define Property1Text7 "Случайные цвета"
#define Property1Text8 "Цвет фона:"
#define Property1Text9 "Цвет полосы:"
#define Property1Text10 "Сбросить цвета"
#define Property1Text11 "Фоновое изображение:"
#define Property1Text12 "Обзор"
#define Property1Text13 "Сброс"
#define Property1Text14 "Подсказка: дополнительные параметры графики см. в категории «Рендеринг»."
#define Property2Title L"Звук"
#define Property2Text1 "Стандартный вывод WinMM:"
#define Property2Text2 "Использовать KDMAPI вместо WinMM (требуется OmniMIDI)"
#define Property3Title L"Рендеринг"
#define Property3Text1 "Расширенные настройки графики:"
#define Property3Text2 "Рендеринг по тикам"
#define Property3Text3 "Визуализация бендов"
#define Property3Text4 "Равная ширина нот"
#define Property3Text5 "Показывать маркеры"
#define Property3Text6 "Кодировка маркеров:"
#define Property3Text7 "Ограничить FPS до 60"
#define Property3Text8 "Экспорт видео"
#define Property3Text9 "Показывать отладочную информацию"
#define Property3Text10 "Скрыть статистику"
#define Property3Text11 "Скрыть перекрывающиеся ноты"
#define Property4Title L"Управление"
#define Property4Text1 "Поведение элементов управления:"
#define Property4Text2 "Перемотка стрелками:"
#define Property4Text3 "сек"
#define Property4Text4 "Изменение скорости стрелками:"
#define Property4Text5 "%"
#define Property4Text6 "Не скрывать панель в полноэкранном режиме"
#define Property4Text7 "Система счета Phigros"
#define Property4Text8 "Приветственный MIDI:"
#define Property4Text9 "Порог интенсивности ноты:"
#define TrackWindowTitle "Настройки трека"
#define TrackText1 "Файл:"
#define TrackText2 "Папка:"
#define TrackText3 "Нот:"
#define TrackText4 "Длительность:"
#define TrackText5 "Замедление вместо лагов"
#define TrackText6 "Заменить все инструменты на пианино"
#define TrackText7 "Играть"
#define TrackText8 "Отмена"
#define AboutWindowTitle "О программе"
#define AboutText2 "OK"
#define LoadWindowTitle L"Загрузка..."
#define LoadingText "Загрузка"
#define LoadingStage1 L"Копирование MIDI в память..."
#define LoadingStage2 L"Распаковка..."
#define LoadingStage3 L"Анализ треков..."
#define LoadingStage4 L"Соединение нот..."
#define LoadingStage5 L"Сортировка событий..."
#define LoadingStage6 L"Подготовка таблицы поиска количества нот..."
#define ResolutionWindowTitle "Разрешение"
#define ResolutionText1 "Ширина:"
#define ResolutionText2 "Высота:"
#define ResolutionText3 "ОК"
#define ResolutionText4 "Отмена"
#define MenuText1 "Открыть"
#define MenuText2 "Закрыть"
#define MenuText3 "Играть"
#define MenuText4 "Воспр./Пауза\tSpace"
#define MenuText5 "Стоп\tEsc"
#define MenuText6 "Вперед\tRight"
#define MenuText7 "Назад\tLeft"
#define MenuText8 "Ускорить\tCtrl+Down"
#define MenuText9 "Замедлить\tCtrl+Up"
#define MenuText10 "Сброс скорости\tCtrl+R"
#define MenuText11 "Быстрые ноты\tShift+Up"
#define MenuText12 "Медленные ноты\tShift+Down"
#define MenuText13 "Сброс нот\tShift+R"
#define MenuText14 "Громче\tUp"
#define MenuText15 "Тише\tDown"
#define MenuText16 "Без звука\tCtrl+M"
#define MenuText17 "Вид"
#define MenuText18 "Панель управления"
#define MenuText19 "Клавиатура"
#define MenuText20 "Поверх окон"
#define MenuText21 "Полный экран\tAlt+Enter"
#define MenuText22 "Размер окна\tCtrl+W"
#define MenuText23 "Позиция и масштаб"
#define MenuText24 "Сброс позиции"
#define MenuText25 "Настройки"
#define MenuText26 "О программе"
#define MenuText27 "Открыть Piano-FX Studio"
#endif
#ifdef DRN
#define MainWindowTitle1 L"ЖЩ1 ЯЭ4 ДЭ5 ГГ1 ЪМ2 ТЭ4 ЩС4"
#define MainWindowTitle2 L"КБ1 ФА1 ЖЭ3: happy_mimimix"
#define MainWindowTitle3 L"ЖЖ4 ЗБ4 БО1 ФГ4: "
#define MainWindowTitle4 L"ЖЖ4 ЗБ4 ЩЩ4 РН3: "
#define MainWindowTitle5 L"КК4 ЩП2"
#define MainWindowTitle6 L"ХЩ1 ЯЫ2 MIDI+"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7 L"  (ЪВ2 ЖИ4 РЩ3 ЙП4 ЩЩ4 РН3)"
#else
#define MainWindowTitle7 L""
#endif
#define WelcomeText L"ХЩ1 ЯЫ2 ШИ3 ЯК4 ЖЩ1 ЯЭ4 ДЭ5 ГГ1 ЪМ2 ТЭ4 ЩС4"
#define StartupStage1Text L"ЖЬ3 БЙ4 ЖК1..."
#define StartupStage2Text L"ЗБ3 РЕ4 ХЩ1 ЯЫ2 MIDI+"
#define StartupStage3Text L"ЧЕ1 ФА1! "
#define OpenFileTitle L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩВ3 ЯУ4 БО1 ФГ4 ДЭ5 ВД2 ЙП4: "
#define OpenSplashFileTitle L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩИ1 ВГ4 ЯК4 ЗХ4 ХЩ1 ЯЫ2 ПЫ2 МЕ4 ДЭ5 ВД2 ЙП4: "
#define OpenBackgroundFileTitle L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩИ1 ВГ4 ЯК4 ЗХ4 БЙ4 ЙЫ3 ТЕ2 ЩВ4 ДЭ5 ВД2 ЙП4: "
#define DigitSeparate 3
#define StatisticsText1 "Piano-FX Pro (DoubleArinoglish)"
#define StatisticsText2 "КБ1 ФА1 ЖЭ3: happy_mimimix"
#define StatisticsText3 "ШИ2 ЧГ2:"
#define StatisticsText4 "КЭ4:"
#define StatisticsText5 "ВЙ1 МС3:"
#define StatisticsText6 "ЖД1 ЛЁ4:"
#define StatisticsText7 "ЯМ1 ЯЕ4 СЕ4 ЛЁ4:"
#define StatisticsText8 "ЛП2 ЙИ1:"
#define StatisticsText9 "МЙ3 МС3 ШФ3 СЕ4:"
#define StatisticsText10 "ШФ3 ЖИ3 ГЭ4 ШЕ4:"
#define StatisticsText11 "ЯМ1 ФЕ2 ШЕ4:"
#define StatisticsText12 "МЙ3 МС3 ЯН3 ЗФ4:"
#define StatisticsText13 "ТК2 ШИ2 ЯН3 ЗФ4:"
#define StatisticsText14 "ЯИ3 ЩЩ4 РН3:"
#define StatisticsText15 "ЯМ1 ЛВ4:"
#define StatisticsText16 "ЙЫ4 ЯМ1"
#define StatisticsText17 "БО1 ФГ4 СЕ4 ДЕ5:"
#define StatisticsText18 "ЯМ1 ФЕ2 СЕ4 ДЕ5:"
#define StatisticsText19 "X ПП1 ЯИ2:"
#define StatisticsText20 "Y ПП1 ЯИ2:"
#define StatisticsText21 "СХ1 ФГ4:"
#define StatisticsText22 "ЧШ1 КФ3 ДА4 ЩС3:"
#define StatisticsText23 "ЪМ2 ЙП4 ФН4 ВЙ2:"
#define StatisticsText24 "ЯМ1 ФЕ2 ЛИ4 ДЕ4 ЯЕ4 ЖИ2:"
#define StatisticsText25 "ФД1 ШЕ4:"
#define StatisticsText26 "ЪЕ3 МЕ4 НН2 ДЕ4:"
#define StatisticsText27 "ЗИ4 ДК4 ЯН3 ЗФ4:"
#define StatisticsText28 "КБ1 ЪИ3 "
#define StatisticsText29 "GON1 ЩИ3 ЪЩ2 ЛП2!!! "
#define StatisticsText30 "ЗИ4 ДК4 ЯН3 ШИ4 ЖК1... "
#define StatisticsText31 "ЯФ2 ЩИ4 ЗН4 ТЫ2... "
#define StatisticsText32 "ЦХ4 ВЕ4: ФД1 ШЕ4 ЯИ4 ЧЕ1! "
#define ZoomMoveMsg "- ЗХ3 ЙП4 ДН1 ЙИ1 БЫ4 ТХ1 ДК4 КЭ3 ЯИ2 ДК4 ПЫ2 МЕ4\n- ЯФ4 ЙП4 ДН1 ЙИ1 БЫ4 ТХ1 ДК1 КЭ3 ШЪ3 ПЫ2 СХ1 ФГ4\n- ЗБ4 ЦИ4 ДП3 ЙИ1 'ЧА2 КН4 -> ЯИ2 ДК4 ХЭ2 СХ1 ФГ4' КЭ3 ЯЫ4 ЯК4 ГЖ1 ГБ3\n- ДП3 ЙИ1 'ЧА2 КН4 -> ЧК2 ЖИ4 ЯИ2 ДК4 ХЭ2 СХ1 ФГ4' КЭ3 ЧЭ4 ЩС1 ГЖ1 ГБ3"
#define PropertyWindowTitle L"ШЭ4 ЖИ4"
#define Property1Title L"ШИ4 ЙТ2"
#define Property1Text1 "ЪМ2 ЙП4 ЩП3 ШИ4:"
#define Property1Text2 "ЪЩ2 БЕ4 128 ЙП4"
#define Property1Text3 "ГД1 ЙЕ4 MIDI+ ЗИ4 ШИ4 ЯЫ4"
#define Property1Text4 "ЖИ3 ДЫ4 ФН4 ВЙ2:"
#define Property1Text5 "ЖИ2 ДУ4"
#define Property1Text6 "ЯМ1 ГЪ3 ЯН2 СЭ4:"
#define Property1Text7 "СЪ2 ЙИ1"
#define Property1Text8 "БЙ4 ЙЫ3 ЯН2 СЭ4:"
#define Property1Text9 "ХЖ2 ТС2 ЯН2 СЭ4:"
#define Property1Text10 "ЧК2 ЖИ4 ЯН2 СЭ4"
#define Property1Text11 "БЙ4 ЙЫ3 ТЕ2 ПП4:"
#define Property1Text12 "ЛЮ2 ЛН3"
#define Property1Text13 "ЧК2 ЖИ4"
#define Property1Text14 "ЪП2 ВГ3 'ЩЩ4 РН3' ЛЙ4 БЗ2 ЧА2 КН4 ГЖ4 ДХ1 ГУ1 ЙИ2 ЩЩ4 РН3 ШЭ4 ЖИ4."
#define Property2Title L"ЯМ1 ПМ2"
#define Property2Text1 "БС1 ЖЬ3 WINMM+ ШЕ1 ЧЕ1:"
#define Property2Text2 "ШИ3 ЯК4 KDMAPI+ ДБ4 ТИ4 WINMM+ (ЩЕ1 ЯУ4 OMNI MIDI+)"
#define Property3Title L"ЩЩ4 РН3"
#define Property3Text1 "ГУ1 ЙИ2 ТЕ2 ЩЫ2 ЩЩ4 РН3 ПЙ4 ЖИ4:"
#define Property3Text2 "ЙИ1 ЯЕ2 КЭ4 ЩЩ4 РН3"
#define Property3Text3 "КЭ3 ШИ4 ХЦ4 ВН1 ЯМ1"
#define Property3Text4 "ДЖ3 КЩ1 ЯМ1 ФЕ2"
#define Property3Text5 "ЩП3 ШИ4 БС1 ЙИ4"
#define Property3Text6 "ВД2 БД3 БП1 МА3 ГЭ2 ШИ4:"
#define Property3Text7 "СХ3 ДЫ4 ЖД1 ЛЁ4 ЖИ4 60 ЖД1"
#define Property3Text8 "ДУ3 ЧЕ1 ШИ4 ПМ2"
#define Property3Text9 "ЩП3 ШИ4 ТС2 ШИ4 ЩМ4 ЩИ1"
#define Property3Text10 "ЯМ3 ЦГ2 ТК3 ЙИ4 ЩМ4 ЩИ1"
#define Property3Text11 "ЯМ3 ЦГ2 ЧК2 ДЗ2 ЯМ1 ФЕ2"
#define Property4Title L"КК4 ЖИ4"
#define Property4Text1 "КК4 ЖИ4 ЩЫ2 ВЙ2 ШЭ4 ЖИ4:"
#define Property4Text2 "ЗХ3 ЯФ4 ЙП4 ТФ2 ТС4 ГХ4:"
#define Property4Text3 "МС3"
#define Property4Text4 "ШГ4 ЩЯ4 ЙП4 ТФ2 ЙЯ1 СЕ4:"
#define Property4Text5 "ФД1 ЖИ1 ББ3"
#define Property4Text6 "ЪЩ2 ПЫ2 МО2 ШИ4 ЩЯ4 БЕ4 ЯМ3 ЦГ2 ГК1 ЙЕ4 ТС2"
#define Property4Text7 "PHIGROS+ ФЖ1 ГЭ2 ЙИ4 ФД1 ЩИ4 ТК3"
#define Property4Text8 "ХЩ1 ЯЫ2 MIDI+:"
#define Property4Text9 "ЯМ1 ФЕ2 ЛИ4 ДЕ4 ЯЕ4 ЖИ2:"
#define TrackWindowTitle "ЯМ1 ГЪ3 ШЭ4 ЖИ4"
#define TrackText1 "ВД3 ЙП4:"
#define TrackText2 "ЛЕ4 ЙЫ4:"
#define TrackText3 "ЯМ1 ФЕ2 ШЕ4:"
#define TrackText4 "ШИ1 ЧГ2:"
#define TrackText5 "ЙП3 СЕ4 ER2 БЕ2 ШИ4 КА3 ДЬ4"
#define TrackText6 "ЙВ1 СХ3 ЯФ3 ЯТ4 ЪИ4 ТИ4 ХЩ4 ЧЖ2 ГГ1 ЪМ2"
#define TrackText7 "БО1 ФГ4"
#define TrackText8 "ЖК1 ЖИ3"
#define AboutWindowTitle "ГЩ1 ЯЕ2"
#define AboutText2 "ХУ3 ДЭ5"
#define LoadWindowTitle L"ЙЯ1 ЗБ3 ЖК1..."
#define LoadingText "ЖЖ4 ЗБ4 ДЕ2 ЪЕ3"
#define LoadingStage1 L"ЖЖ4 ЗБ4 ЙВ1 ВД2 ЙП4 ФЕ4 ЖИ4 ДУ4 НЙ4 ЦЬ2..."
#define LoadingStage2 L"ЖЖ4 ЗБ4 ЙЗ3 ЯА1 СХ1..."
#define LoadingStage3 L"ЖЖ4 ЗБ4 ЙЗ3 ЩИ1 ЯМ1 ГЪ3..."
#define LoadingStage4 L"ЖЖ4 ЗБ4 ЛП2 ЙИ1 ЯМ1 ФЕ2..."
#define LoadingStage5 L"ЖЖ4 ЗБ4 ЖЖ3 ЛИ3 ШИ1 ЙП4..."
#define LoadingStage6 L"ЖЖ4 ЗБ4 ЖЬ3 БЙ4 ЯМ1 ФЕ2 ЙИ4 ШЕ4 ЧА2 БС3..."
#define ResolutionWindowTitle "ШЭ4 ЖИ4 ФД1 БП4 ЛЁ4"
#define ResolutionText1 "КЩ1:"
#define ResolutionText2 "ГУ1:"
#define ResolutionText3 "ЪТ4 РД4"
#define ResolutionText4 "ЪЕ3 ЩС1"
#define MenuText1 "ДА3 КБ1"
#define MenuText2 "ГЩ1 БИ4"
#define MenuText3 "ЯН3 ЗФ4"
#define MenuText4 "БО1 ФГ4/ЗН4 ТЫ2\tSpace"
#define MenuText5 "ТЫ2 ЖИ3\tEsc"
#define MenuText6 "КЧ4 ЙМ4\tRight"
#define MenuText7 "КЧ4 ТЪ4\tLeft"
#define MenuText8 "БО1 ФГ4 ЙЯ1 СЕ4\tCtrl+Down"
#define MenuText9 "БО1 ФГ4 ЙП3 СЕ4\tCtrl+Up"
#define MenuText10 "БО1 ФГ4 ЧК2 ЖИ4\tCtrl+R"
#define MenuText11 "ЯМ1 ФЕ2 ЙЯ1 СЕ4\tShift+Up"
#define MenuText12 "ЯМ1 ФЕ2 ЙП3 СЕ4\tShift+Down"
#define MenuText13 "ЧК2 ЖИ4 ЯМ1 ФЕ2\tShift+R"
#define MenuText14 "ЯМ1 ЛВ4 ЙЯ1\tUp"
#define MenuText15 "ЯМ1 ЛВ4 ЙП3\tDown"
#define MenuText16 "ЙЫ4 ЯМ1\tCtrl+M"
#define MenuText17 "ЧА2 КН4"
#define MenuText18 "ГК1 ЙЕ4 ТС2"
#define MenuText19 "ЙП4 ПН2"
#define MenuText20 "ЧШ1 КФ3 ЖИ4 ДЫ3"
#define MenuText21 "ЪЩ2 ПЫ2 ЩП3 ШИ4\tAlt+Enter"
#define MenuText22 "ШЭ4 ЖИ4 ЧШ1 КФ3 ДА4 ЩС3\tCtrl+W"
#define MenuText23 "ЯИ2 ДК4 ХЭ2 СХ1 ФГ4"
#define MenuText24 "ЧК2 ЖИ4 ЯИ2 ДК4 ХЭ2 СХ1 ФГ4"
#define MenuText25 "ШЭ4 ЖИ4"
#define MenuText26 "ГЩ1 ЯЕ2"
#define MenuText27 "ГГ1 ЪМ2 ТЭ4 ЩС4 БП1 ЙИ1 ЪИ4"
#define StatisticsWidth 300
#endif
