#define AboutText1 "Piano-FX Pro v4.2 | Forked from Piano From Above v1.1.0\n\nContributors list: \nHappy_mimimix(25 %) <-Funny special effects && Final optimization\nanon64(5 %) <-Color events support\nKhangaroo(30 %) <-Performance boost\nBrianPantano(40 %) <-Main program"
#ifdef ENG
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 97 //Text: L"Developed by: happy_mimimix"
#define MainWindowTitle3W 43 //Text: L"Now playing: "
#define MainWindowTitle4W 51 //Text: L"Now rendering: "
#define MainWindowTitle5W 17 //Text: L"None"
#define MainWindowTitle6W 38 //Text: L"Splash MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 104 //Text: L"  (Enforced Software Rendering)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 80 //Text: L"Welcome to Piano-FX Pro"
#define StartupStage1TextW 39 //Text: L"Preparing..."
#define StartupStage2TextW 69 //Text: L"Loading splash midi..."
#define StartupStage3TextW 27 //Text: L"Let's go!"
#define OpenFileTitleW 126 //Text: L"Please select the file you want to play: "
#define OpenSplashFileTitleW 151 //Text: L"Please select your desired splash screen MIDI: "
#define OpenBackgroundFileTitleW 148 //Text: L"Please select your desired background image: "
#define StatisticsText1W 41 //Text: "Piano-FX Pro"
#define StatisticsText2W 97 //Text: "Developed by: happy_mimimix"
#define StatisticsText3W 17 //Text: "Time:"
#define StatisticsText4W 15 //Text: "Tick:"
#define StatisticsText5W 45 //Text: "Microseconds:"
#define StatisticsText6W 15 //Text: "FPS:"
#define StatisticsText7W 24 //Text: "Tempo:"
#define StatisticsText8W 25 //Text: "Combo:"
#define StatisticsText9W 54 //Text: "ClicksPerSecond:"
#define StatisticsText10W 69 //Text: "SimultaneousPresses:"
#define StatisticsText11W 21 //Text: "Notes:"
#define StatisticsText12W 55 //Text: "NotesPerSecond:"
#define StatisticsText13W 36 //Text: "Polyphony:"
#define StatisticsText14W 34 //Text: "Rendered:"
#define StatisticsText15W 25 //Text: "Volume:"
#define StatisticsText16W 23 //Text: "MUTED"
#define StatisticsText17W 51 //Text: "PlaybackSpeed:"
#define StatisticsText18W 38 //Text: "NoteSpeed:"
#define StatisticsText19W 30 //Text: "Offset-X:"
#define StatisticsText20W 30 //Text: "Offset-Y:"
#define StatisticsText21W 20 //Text: "Zoom:"
#define StatisticsText22W 41 //Text: "WindowSize:"
#define StatisticsText23W 35 //Text: "KeyRange:"
#define StatisticsText24W 59 //Text: "VelocityThreshold:"
#define StatisticsText25W 21 //Text: "Score:"
#define StatisticsText26W 19 //Text: "Level:"
#define StatisticsText27W 31 //Text: "AutoPlay:"
#define StatisticsText28W 12 //Text: "ON "
#define StatisticsText29W 52 //Text: "FULL COMBO!!! "
#define StatisticsText30W 94 //Text: "Demonstration in progress... "
#define StatisticsText31W 53 //Text: "Game paused... "
#define StatisticsText32W 81 //Text: "ERROR: Score overflow! "
#define ZoomMoveMsgW 619 //Text: "- Left-click and drag to move the screen\n- Right-click and drag to zoom horizontally\n- Click 'View -> Move And Zoom' again to apply changes\n- Click 'View -> Reset Move And Zoom' to revert changes"
#define PropertyWindowTitleW 39 //Text: L"Preferences"
#define Property1TitleW 18 //Text: L"Visual"
#define Property1Text1W 51 //Text: "Keys to display:"
#define Property1Text2W 57 //Text: "Show all 128 keys"
#define Property1Text3W 51 //Text: "Show song keys"
#define Property1Text4W 37 //Text: "Show keys:"
#define Property1Text5W 25 //Text: "through"
#define Property1Text6W 41 //Text: "Track colors:"
#define Property1Text7W 35 //Text: "Randomize"
#define Property1Text8W 57 //Text: "Background color:"
#define Property1Text9W 31 //Text: "Bar color:"
#define Property1Text10W 76 //Text: "Restore Defaults Colors"
#define Property1Text11W 61 //Text: "Background image:"
#define Property1Text12W 23 //Text: "Browse"
#define Property1Text13W 19 //Text: "Reset"
#define Property1Text14W 255 //Text: "Hint: Visit the 'Render' category for more advanced graphics rendering options. "
#define Property2TitleW 18 //Text: L"Audio"
#define Property2Text1W 80 //Text: "Standard WinMM output:"
#define Property2Text2W 213 //Text: "Use more efficient KDMAPI instead of WinMM (Requires OmniMIDI)"
#define Property3TitleW 23 //Text: L"Render"
#define Property3Text1W 117 //Text: "Advanced graphics rendering config:"
#define Property3Text2W 67 //Text: "Tick-based rendering"
#define Property3Text3W 65 //Text: "Visualize pitch bends"
#define Property3Text4W 57 //Text: "Same width notes"
#define Property3Text5W 45 //Text: "Show markers"
#define Property3Text6W 71 //Text: "Marker text encoding:"
#define Property3Text7W 47 //Text: "Lock FPS to 60"
#define Property3Text8W 41 //Text: "Video output"
#define Property3Text9W 77 //Text: "Show debug information"
#define Property3Text10W 44 //Text: "Hide statistics"
#define Property3Text11W 73 //Text: "Hide overlapping notes"
#define Property4TitleW 23 //Text: L"Control"
#define Property4Text1W 61 //Text: "Controls' behavior:"
#define Property4Text2W 124 //Text: "Left and right arrows skip the song by:"
#define Property4Text3W 26 //Text: "seconds"
#define Property4Text4W 140 //Text: "Up and down arrows speed up the song by:"
#define Property4Text5W 25 //Text: "percent"
#define Property4Text6W 148 //Text: "Don't hide playback toolbar in full screen mode"
#define Property4Text7W 90 //Text: "Phigros style scoring system"
#define Property4Text8W 41 //Text: "Splash MIDI:"
#define Property4Text9W 59 //Text: "Velocity threshold:"
#define TrackWindowTitleW 45 //Text: "Track Settings"
#define TrackText1W 13 //Text: "File:"
#define TrackText2W 23 //Text: "Folder:"
#define TrackText3W 21 //Text: "Notes:"
#define TrackText4W 25 //Text: "Length:"
#define TrackText5W 79 //Text: "Slow down instead of lag"
#define TrackText6W 102 //Text: "Override instruments with piano"
#define TrackText7W 13 //Text: "Play"
#define TrackText8W 18 //Text: "Abort"
#define AboutWindowTitleW 19 //Text: "About"
#define AboutText2W 9 //Text: "OK"
#define LoadWindowTitleW 33 //Text: L"Loading..."
#define LoadingTextW 25 //Text: "Loading"
#define LoadingStage1W 93 //Text: L"Copying MIDI into memory..."
#define LoadingStage2W 56 //Text: L"Decompressing..."
#define LoadingStage3W 53 //Text: L"Parsing tracks..."
#define LoadingStage4W 64 //Text: L"Connecting notes..."
#define LoadingStage5W 55 //Text: L"Sorting events..."
#define LoadingStage6W 116 //Text: L"Preparing note count lookup table..."
#define ResolutionWindowTitleW 46 //Text: "Set Resolution"
#define ResolutionText1W 21 //Text: "Width:"
#define ResolutionText2W 23 //Text: "Height:"
#define ResolutionText3W 25 //Text: "Confirm"
#define ResolutionText4W 21 //Text: "Cancel"
#define MenuText1W 17 //Text: "Open"
#define MenuText2W 17 //Text: "Close"
#define MenuText3W 13 //Text: "Play"
#define MenuText4W 55 //Text: "Play/Pause\tSpace"
#define MenuText5W 25 //Text: "Stop\tEsc"
#define MenuText6W 45 //Text: "Skip Fwd\tRight"
#define MenuText7W 42 //Text: "Skip Back\tLeft"
#define MenuText8W 85 //Text: "Faster Playback\tCtrl+Down"
#define MenuText9W 77 //Text: "Slower Playback\tCtrl+Up"
#define MenuText10W 70 //Text: "Reset Playback\tCtrl+R"
#define MenuText11W 70 //Text: "Faster Notes\tShift+Up"
#define MenuText12W 80 //Text: "Slower Notes\tShift+Down"
#define MenuText13W 64 //Text: "Reset Notes\tShift+R"
#define MenuText14W 42 //Text: "Volume Up\tUp"
#define MenuText15W 61 //Text: "Volume Down\tDown"
#define MenuText16W 38 //Text: "Mute\tCtrl+M"
#define MenuText17W 15 //Text: "View"
#define MenuText18W 54 //Text: "Playback Toolbar"
#define MenuText19W 31 //Text: "Keyboard"
#define MenuText20W 48 //Text: "Always On Top"
#define MenuText21W 66 //Text: "Full Screen\tAlt+Enter"
#define MenuText22W 76 //Text: "Set Window Size\tCtrl+W"
#define MenuText23W 51 //Text: "Move And Zoom"
#define MenuText24W 72 //Text: "Reset Move And Zoom"
#define MenuText25W 39 //Text: "Preferences"
#define MenuText26W 19 //Text: "About"
#define MenuText27W 69 //Text: "Open Piano-FX Studio"
#endif
#ifdef CHN
#define MainWindowTitle1W 56 //Text: L"专业の钢琴特效"
#define MainWindowTitle2W 80 //Text: L"开发者：happy_mimimix"
#define MainWindowTitle3W 40 //Text: L"正在播放："
#define MainWindowTitle4W 40 //Text: L"正在渲染："
#define MainWindowTitle5W 8 //Text: L"无"
#define MainWindowTitle6W 31 //Text: L"欢迎MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 57 //Text: L"  (强制软件渲染)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 90 //Text: L"欢迎使用 专业の钢琴特效"
#define StartupStage1TextW 36 //Text: L"准备中……"
#define StartupStage2TextW 59 //Text: L"加载欢迎MIDI……"
#define StartupStage3TextW 56 //Text: L"让我们开始吧！"
#define OpenFileTitleW 93 //Text: L"请选择您想要播放的文件: "
#define OpenSplashFileTitleW 125 //Text: L"请选择您希望作为欢迎画面的文件: "
#define OpenBackgroundFileTitleW 125 //Text: L"请选择您希望作为背景图像的文件: "
#define StatisticsText1W 87 //Text: "专业の钢琴特效 (中文版)"
#define StatisticsText2W 77 //Text: "开发者: happy_mimimix"
#define StatisticsText3W 19 //Text: "时长:"
#define StatisticsText4W 11 //Text: "刻:"
#define StatisticsText5W 19 //Text: "微秒:"
#define StatisticsText6W 19 //Text: "帧率:"
#define StatisticsText7W 35 //Text: "歌曲速率:"
#define StatisticsText8W 19 //Text: "连击:"
#define StatisticsText9W 35 //Text: "每秒手速:"
#define StatisticsText10W 35 //Text: "手指个数:"
#define StatisticsText11W 27 //Text: "音符数:"
#define StatisticsText12W 35 //Text: "每秒演奏:"
#define StatisticsText13W 35 //Text: "同时演奏:"
#define StatisticsText14W 27 //Text: "已渲染:"
#define StatisticsText15W 19 //Text: "音量:"
#define StatisticsText16W 16 //Text: "静音"
#define StatisticsText17W 35 //Text: "播放速度:"
#define StatisticsText18W 35 //Text: "音符速度:"
#define StatisticsText19W 23 //Text: "X偏移:"
#define StatisticsText20W 23 //Text: "Y偏移:"
#define StatisticsText21W 19 //Text: "缩放:"
#define StatisticsText22W 35 //Text: "窗口大小:"
#define StatisticsText23W 35 //Text: "琴键范围:"
#define StatisticsText24W 51 //Text: "音符力度阈值:"
#define StatisticsText25W 19 //Text: "分数:"
#define StatisticsText26W 19 //Text: "难度:"
#define StatisticsText27W 35 //Text: "自动播放:"
#define StatisticsText28W 18 //Text: "开启 "
#define StatisticsText29W 42 //Text: "恭喜全连!!! "
#define StatisticsText30W 66 //Text: "奥托普雷演示中... "
#define StatisticsText31W 42 //Text: "游戏暂停... "
#define StatisticsText32W 57 //Text: "错误: 分数溢出! "
#define ZoomMoveMsgW 493 //Text: "- 左键单击并拖动可移动屏幕\n- 右键单击并拖动可水平缩放\n- 再次点击“查看->移动和缩放”可应用更改\n- 点击“查看->重置移动和缩放”可撤销更改"
#define PropertyWindowTitleW 16 //Text: L"属性"
#define Property1TitleW 16 //Text: L"视觉"
#define Property1Text1W 35 //Text: "琴键显示:"
#define Property1Text2W 36 //Text: "全部128键"
#define Property1Text3W 24 //Text: "自适应"
#define Property1Text4W 35 //Text: "指定范围:"
#define Property1Text5W 8 //Text: "至"
#define Property1Text6W 35 //Text: "音轨颜色:"
#define Property1Text7W 16 //Text: "随机"
#define Property1Text8W 35 //Text: "背景颜色:"
#define Property1Text9W 35 //Text: "横条颜色:"
#define Property1Text10W 48 //Text: "重置默认颜色"
#define Property1Text11W 35 //Text: "背景图片:"
#define Property1Text12W 16 //Text: "浏览"
#define Property1Text13W 16 //Text: "重置"
#define Property1Text14W 181 //Text: "提示：前往“渲染”类别查看更多高级图形渲染选项。"
#define Property2TitleW 16 //Text: L"音频"
#define Property2Text1W 57 //Text: "标准WinMM输出:"
#define Property2Text2W 177 //Text: "使用更高效的KDMAPI代替WinMM（需要 OmniMIDI）"
#define Property3TitleW 16 //Text: L"渲染"
#define Property3Text1W 67 //Text: "高级图形渲染选项:"
#define Property3Text2W 40 //Text: "基于刻渲染"
#define Property3Text3W 40 //Text: "可视化弯音"
#define Property3Text4W 32 //Text: "等宽音符"
#define Property3Text5W 32 //Text: "显示标记"
#define Property3Text6W 51 //Text: "文本编码格式:"
#define Property3Text7W 48 //Text: "锁定帧率至60"
#define Property3Text8W 32 //Text: "导出视频"
#define Property3Text9W 48 //Text: "显示调试信息"
#define Property3Text10W 48 //Text: "隐藏统计数据"
#define Property3Text11W 48 //Text: "隐藏重叠音符"
#define Property4TitleW 16 //Text: L"控制"
#define Property4Text1W 35 //Text: "按键行为:"
#define Property4Text2W 51 //Text: "左右箭头跳过:"
#define Property4Text3W 8 //Text: "秒"
#define Property4Text4W 51 //Text: "上下箭头加速:"
#define Property4Text5W 7 //Text: "%"
#define Property4Text6W 88 //Text: "全屏模式下不隐藏工具条"
#define Property4Text7W 63 //Text: "仿Phigros计分系统"
#define Property4Text8W 34 //Text: "欢迎MIDI:"
#define Property4Text9W 51 //Text: "音符力度阈值:"
#define TrackWindowTitleW 32 //Text: "音轨设置"
#define TrackText1W 27 //Text: "文件名:"
#define TrackText2W 19 //Text: "路径:"
#define TrackText3W 27 //Text: "音符数:"
#define TrackText4W 19 //Text: "时长:"
#define TrackText5W 56 //Text: "减速而不是卡顿"
#define TrackText6W 80 //Text: "将所有乐器替换为钢琴"
#define TrackText7W 16 //Text: "播放"
#define TrackText8W 16 //Text: "终止"
#define AboutWindowTitleW 16 //Text: "关于"
#define AboutText2W 8 //Text: "好"
#define LoadWindowTitleW 32 //Text: L"加载中..."
#define LoadingTextW 32 //Text: "正在读取"
#define LoadingStage1W 88 //Text: L"正在将文件复制到内存..."
#define LoadingStage2W 48 //Text: L"正在解压缩..."
#define LoadingStage3W 56 //Text: L"正在解析音轨..."
#define LoadingStage4W 56 //Text: L"正在连接音符..."
#define LoadingStage5W 56 //Text: L"正在整理事件..."
#define LoadingStage6W 88 //Text: L"正在准备音符计数查表..."
#define ResolutionWindowTitleW 40 //Text: "设置分辨率"
#define ResolutionText1W 19 //Text: "宽度:"
#define ResolutionText2W 19 //Text: "高度:"
#define ResolutionText3W 16 //Text: "确认"
#define ResolutionText4W 16 //Text: "取消"
#define MenuText1W 16 //Text: "打开"
#define MenuText2W 16 //Text: "关闭"
#define MenuText3W 16 //Text: "演奏"
#define MenuText4W 54 //Text: "播放/暂停\tSpace"
#define MenuText5W 27 //Text: "停止\tEsc"
#define MenuText6W 33 //Text: "快进\tRight"
#define MenuText7W 29 //Text: "快退\tLeft"
#define MenuText8W 67 //Text: "播放加速\tCtrl+Down"
#define MenuText9W 57 //Text: "播放减速\tCtrl+Up"
#define MenuText10W 53 //Text: "播放重置\tCtrl+R"
#define MenuText11W 61 //Text: "音符加速\tShift+Up"
#define MenuText12W 70 //Text: "音符减速\tShift+Down"
#define MenuText13W 57 //Text: "音符重置\tShift+R"
#define MenuText14W 33 //Text: "音量加\tUp"
#define MenuText15W 42 //Text: "音量减\tDown"
#define MenuText16W 38 //Text: "静音\tCtrl+M"
#define MenuText17W 16 //Text: "查看"
#define MenuText18W 24 //Text: "工具条"
#define MenuText19W 16 //Text: "键盘"
#define MenuText20W 16 //Text: "置顶"
#define MenuText21W 47 //Text: "全屏\tAlt+Enter"
#define MenuText22W 71 //Text: "设置窗口大小\tCtrl+W"
#define MenuText23W 40 //Text: "移动和缩放"
#define MenuText24W 56 //Text: "重置移动和缩放"
#define MenuText25W 16 //Text: "设置"
#define MenuText26W 16 //Text: "关于"
#define MenuText27W 56 //Text: "钢琴特效编辑器"
#endif
#ifdef ARN
#define MainWindowTitle1W 135 //Text: L"ZHUAN1 YE4 DE5 GANG1 QIN2 TE4 XIAO4"
#define MainWindowTitle2W 101 //Text: L"KAI1 FA1 ZHE3: happy_mimimix"
#define MainWindowTitle3W 87 //Text: L"ZHENG4 ZAI4 BO1 FANG4: "
#define MainWindowTitle4W 92 //Text: L"ZHENG4 ZAI4 XUAN4 RAN3: "
#define MainWindowTitle5W 45 //Text: L"KONG4 XIAN2"
#define MainWindowTitle6W 67 //Text: L"HUAN1 YING2 MIDI+"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 143 //Text: L"  (QIANG2 ZHI4 RUAN3 JIAN4 XUAN4 RAN3)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 224 //Text: L"HUAN1 YING2 SHI3 YONG4 ZHUAN1 YE4 DE5 GANG1 QIN2 TE4 XIAO4"
#define StartupStage1TextW 76 //Text: L"ZHUN3 BEI4 ZHONG1..."
#define StartupStage2TextW 100 //Text: L"ZAI3 RU4 HUAN1 YING2 MIDI+"
#define StartupStage3TextW 37 //Text: L"CHU1 FA1! "
#define OpenFileTitleW 227 //Text: L"QING3 XUAN3 QU3 NIN2 XIANG3 YAO4 BO1 FANG4 DE5 WEN2 JIAN4: "
#define OpenSplashFileTitleW 310 //Text: L"QING3 XUAN3 QU3 NIN2 XI1 WANG4 YONG4 ZUO4 HUAN1 YING2 PING2 MU4 DE5 WEN2 JIAN4: "
#define OpenBackgroundFileTitleW 305 //Text: L"QING3 XUAN3 QU3 NIN2 XI1 WANG4 YONG4 ZUO4 BEI4 JING3 TU2 XIANG4 DE5 WEN2 JIAN4: "
#define StatisticsText1W 79 //Text: "Piano-FX Pro (Arinoglish)"
#define StatisticsText2W 101 //Text: "KAI1 FA1 ZHE3: happy_mimimix"
#define StatisticsText3W 47 //Text: "SHI2 CHANG2:"
#define StatisticsText4W 15 //Text: "KE4:"
#define StatisticsText5W 44 //Text: "WEI1 MIAO3:"
#define StatisticsText6W 37 //Text: "ZHEN1 LV4:"
#define StatisticsText7W 61 //Text: "YIN1 YU4 SU4 LV4:"
#define StatisticsText8W 34 //Text: "LIAN2 JI1:"
#define StatisticsText9W 82 //Text: "MEI3 MIAO3 SHOU3 SU4:"
#define StatisticsText10W 77 //Text: "SHOU3 ZHI3 GE4 SHU4:"
#define StatisticsText11W 52 //Text: "YIN1 FU2 SHU4:"
#define StatisticsText12W 82 //Text: "MEI3 MIAO3 YAN3 ZOU4:"
#define StatisticsText13W 82 //Text: "TONG2 SHI2 YAN3 ZOU4:"
#define StatisticsText14W 57 //Text: "YI3 XUAN4 RAN3:"
#define StatisticsText15W 44 //Text: "YIN1 LIANG4:"
#define StatisticsText16W 37 //Text: "JING4 YIN1"
#define StatisticsText17W 70 //Text: "BO1 FANG4 SU4 DU5:"
#define StatisticsText18W 63 //Text: "YIN1 FU2 SU4 DU5:"
#define StatisticsText19W 41 //Text: "X PIAN1 YI2:"
#define StatisticsText20W 41 //Text: "Y PIAN1 YI2:"
#define StatisticsText21W 45 //Text: "SUO1 FANG4:"
#define StatisticsText22W 93 //Text: "CHUANG1 KOU3 DA4 XIAO3:"
#define StatisticsText23W 79 //Text: "QIN2 JIAN4 FAN4 WEI2:"
#define StatisticsText24W 92 //Text: "YIN1 FU2 LI4 DU4 YU4 ZHI2:"
#define StatisticsText25W 39 //Text: "FEN1 SHU4:"
#define StatisticsText26W 68 //Text: "QU3 MU4 NAN2 DU4:"
#define StatisticsText27W 78 //Text: "ZI4 DONG4 YAN3 ZOU4:"
#define StatisticsText28W 31 //Text: "KAI1 QI3 "
#define StatisticsText29W 88 //Text: "GON1 XI3 QUAN2 LIAN2!!! "
#define StatisticsText30W 112 //Text: "ZI4 DONG4 YAN3 SHI4 ZHONG1... "
#define StatisticsText31W 82 //Text: "YOU2 XI4 ZAN4 TING2... "
#define StatisticsText32W 114 //Text: "CUO4 WU4: FEN1 SHU4 YI4 CHU1! "
#define ZoomMoveMsgW 1,129 //Text: "- ZUO3 JIAN4 DAN1 JI1 BING4 TUO1 DONG4 KE3 YI2 DONG4 PING2 MU4\n- YOU4 JIAN4 DAN1 JI1 BING4 TUO1 DONG1 KE3 SHUI3 PING2 SUO1 FANG4\n- ZAI4 CI4 DIAN3 JI1 'CHA2 KAN4 -> YI2 DONG4 HE2 SUO1 FANG4' KE3 YING4 YONG4 GENG1 GAI3\n- DIAN3 JI1 'CHA2 KAN4 -> CHONG2 ZHI4 YI2 DONG4 HE2 SUO1 FANG4' KE3 CHE4 XIAO1 GENG1 GAI3"
#define PropertyWindowTitleW 34 //Text: L"SHE4 ZHI4"
#define Property1TitleW 33 //Text: L"SHI4 JUE2"
#define Property1Text1W 80 //Text: "QIN2 JIAN4 XIAN3 SHI4:"
#define Property1Text2W 73 //Text: "QUAN2 BU4 128 JIAN4"
#define Property1Text3W 106 //Text: "GEN1 JU4 MIDI+ ZI4 SHI4 YING4"
#define Property1Text4W 79 //Text: "ZHI3 DING4 FAN4 WEI2:"
#define Property1Text5W 36 //Text: "ZHI2 DAO4"
#define Property1Text6W 69 //Text: "YIN1 GUI3 YAN2 SE4:"
#define Property1Text7W 27 //Text: "SUI2 JI1"
#define Property1Text8W 72 //Text: "BEI4 JING3 YAN2 SE4:"
#define Property1Text9W 81 //Text: "HENG2 TIAO2 YAN2 SE4:"
#define Property1Text10W 79 //Text: "CHONG2 ZHI4 YAN2 SE4"
#define Property1Text11W 75 //Text: "BEI4 JING3 TU2 PIAN4:"
#define Property1Text12W 33 //Text: "LIU2 LAN3"
#define Property1Text13W 45 //Text: "CHONG2 ZHI4"
#define Property1Text14W 327 //Text: "QIAN2 WANG3 'XUAN4 RAN3' LEI4 BIE2 CHA2 KAN4 GENG4 DUO1 GAO1 JI2 XUAN4 RAN3 SHE4 ZHI4."
#define Property2TitleW 33 //Text: L"YIN1 PIN2"
#define Property2Text1W 119 //Text: "BIAO1 ZHUN3 WINMM+ SHU1 CHU1:"
#define Property2Text2W 218 //Text: "SHI3 YONG4 KDMAPI+ DAI4 TI4 WINMM+ (XU1 YAO4 OMNI MIDI+)"
#define Property3TitleW 42 //Text: L"XUAN4 RAN3"
#define Property3Text1W 148 //Text: "GAO1 JI2 TU2 XING2 XUAN4 RAN3 PEI4 ZHI4:"
#define Property3Text2W 83 //Text: "JI1 YU2 KE4 XUAN4 RAN3"
#define Property3Text3W 89 //Text: "KE3 SHI4 HUA4 WAN1 YIN1"
#define Property3Text4W 78 //Text: "DENG3 KUAN1 YIN1 FU2"
#define Property3Text5W 72 //Text: "XIAN3 SHI4 BIAO1 JI4"
#define Property3Text6W 111 //Text: "WEN2 BEN3 BIAN1 MA3 GE2 SHI4:"
#define Property3Text7W 128 //Text: "SUO3 DING4 ZHEN1 LV4 ZHI4 60 ZHEN1"
#define Property3Text8W 73 //Text: "DAO3 CHU1 SHI4 PIN2"
#define Property3Text9W 107 //Text: "XIAN3 SHI4 TIAO2 SHI4 XIN4 XI1"
#define Property3Text10W 107 //Text: "YIN3 CANG2 TONG3 JI4 XIN4 XI1"
#define Property3Text11W 119 //Text: "YIN3 CANG2 CHONG2 DIE2 YIN1 FU2"
#define Property4TitleW 40 //Text: L"KONG4 ZHI4"
#define Property4Text1W 120 //Text: "KONG4 ZHI4 XING2 WEI2 SHE4 ZHI4:"
#define Property4Text2W 125 //Text: "ZUO3 YOU4 JIAN4 TOU2 TIAO4 GUO4:"
#define Property4Text3W 22 //Text: "MIAO3"
#define Property4Text4W 119 //Text: "SHANG4 XIA4 JIAN4 TOU2 JIA1 SU4:"
#define Property4Text5W 51 //Text: "FEN1 ZHI1 BAI3"
#define Property4Text6W 215 //Text: "QUAN2 PING2 MO2 SHI4 XIA4 BU4 YIN3 CANG2 GONG1 JU4 TIAO2"
#define Property4Text7W 141 //Text: "PHIGROS+ FENG1 GE2 JI4 FEN1 XI4 TONG3"
#define Property4Text8W 70 //Text: "HUAN1 YING2 MIDI+:"
#define Property4Text9W 92 //Text: "YIN1 FU2 LI4 DU4 YU4 ZHI2:"
#define TrackWindowTitleW 69 //Text: "YIN1 GUI3 SHE4 ZHI4"
#define TrackText1W 43 //Text: "WEN3 JIAN4:"
#define TrackText2W 36 //Text: "LU4 JING4:"
#define TrackText3W 52 //Text: "YIN1 FU2 SHU4:"
#define TrackText4W 47 //Text: "SHI1 CHANG2:"
#define TrackText5W 115 //Text: "JIAN3 SU4 ER2 BU2 SHI4 KA3 DUN4"
#define TrackText6W 206 //Text: "JIANG1 SUO3 YOU3 YUE4 QI4 TI4 HUAN4 CHENG2 GANG1 QIN2"
#define TrackText7W 37 //Text: "BO1 FANG4"
#define TrackText8W 45 //Text: "ZHONG1 ZHI3"
#define AboutWindowTitleW 37 //Text: "GUAN1 YU2"
#define AboutText2W 33 //Text: "HAO3 DE5"
#define LoadWindowTitleW 69 //Text: L"JIA1 ZAI3 ZHONG1..."
#define LoadingTextW 75 //Text: "ZHENG4 ZAI4 DU2 QU3"
#define LoadingStage1W 210 //Text: L"ZHENG4 ZAI4 JIANG1 WEN2 JIAN4 FU4 ZHI4 DAO4 NEI4 CUN2..."
#define LoadingStage2W 102 //Text: L"ZHENG4 ZAI4 JIE3 YA1 SUO1..."
#define LoadingStage3W 115 //Text: L"ZHENG4 ZAI4 JIE3 XI1 YIN1 GUI3..."
#define LoadingStage4W 117 //Text: L"ZHENG4 ZAI4 LIAN2 JI1 YIN1 FU2..."
#define LoadingStage5W 130 //Text: L"ZHENG4 ZAI4 ZHENG3 LI3 SHI1 JIAN4..."
#define LoadingStage6W 198 //Text: L"ZHENG4 ZAI4 ZHUN3 BEI4 YIN1 FU2 JI4 SHU4 CHA2 BIAO3..."
#define ResolutionWindowTitleW 88 //Text: "SHE4 ZHI4 FEN1 BIAN4 LV4"
#define ResolutionText1W 25 //Text: "KUAN1:"
#define ResolutionText2W 21 //Text: "GAO1:"
#define ResolutionText3W 37 //Text: "QUE4 REN4"
#define ResolutionText4W 37 //Text: "QU3 XIAO1"
#define MenuText1W 31 //Text: "DA3 KAI1"
#define MenuText2W 35 //Text: "GUAN1 BI4"
#define MenuText3W 37 //Text: "YAN3 ZOU4"
#define MenuText4W 99 //Text: "BO1 FANG4/ZAN4 TING2\tSpace"
#define MenuText5W 48 //Text: "TING2 ZHI3\tEsc"
#define MenuText6W 53 //Text: "KUAI4 JIN4\tRight"
#define MenuText7W 50 //Text: "KUAI4 TUI4\tLeft"
#define MenuText8W 103 //Text: "BO1 FANG4 JIA1 SU4\tCtrl+Down"
#define MenuText9W 99 //Text: "BO1 FANG4 JIAN3 SU4\tCtrl+Up"
#define MenuText10W 106 //Text: "BO1 FANG4 CHONG2 ZHI4\tCtrl+R"
#define MenuText11W 90 //Text: "YIN1 FU2 JIA1 SU4\tShift+Up"
#define MenuText12W 104 //Text: "YIN1 FU2 JIAN3 SU4\tShift+Down"
#define MenuText13W 102 //Text: "CHONG2 ZHI4 YIN1 FU2\tShift+R"
#define MenuText14W 67 //Text: "YIN1 LIANG4 JIA1\tUp"
#define MenuText15W 81 //Text: "YIN1 LIANG4 JIAN3\tDown"
#define MenuText16W 59 //Text: "JING4 YIN1\tCtrl+M"
#define MenuText17W 37 //Text: "CHA2 KAN4"
#define MenuText18W 60 //Text: "GONG1 JU4 TIAO2"
#define MenuText19W 39 //Text: "JIAN4 PAN2"
#define MenuText20W 92 //Text: "CHUANG1 KOU3 ZHI4 DING3"
#define MenuText21W 116 //Text: "QUAN2 PING2 XIAN3 SHI4\tAlt+Enter"
#define MenuText22W 149 //Text: "SHE4 ZHI4 CHUANG1 KOU3 DA4 XIAO3\tCtrl+W"
#define MenuText23W 95 //Text: "YI2 DONG4 HE2 SUO1 FANG4"
#define MenuText24W 142 //Text: "CHONG2 ZHI4 YI2 DONG4 HE2 SUO1 FANG4"
#define MenuText25W 34 //Text: "SHE4 ZHI4"
#define MenuText26W 37 //Text: "GUAN1 YU2"
#define MenuText27W 126 //Text: "GANG1 QIN2 TE4 XIAO4 BIAN1 JI1 QI4"
#endif
#ifdef JPN
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 77 //Text: L"開発者: happy_mimimix"
#define MainWindowTitle3W 29 //Text: L"再生中: "
#define MainWindowTitle4W 61 //Text: L"レンダリング中: "
#define MainWindowTitle5W 16 //Text: L"なし"
#define MainWindowTitle6W 63 //Text: L"スプラッシュMIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 121 //Text: L"  (ソフトウェアレンダリング強制)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 81 //Text: L"Piano-FX Proへようこそ"
#define StartupStage1TextW 32 //Text: L"準備中..."
#define StartupStage2TextW 119 //Text: L"スプラッシュMIDIを読み込み中..."
#define StartupStage3TextW 40 //Text: L"スタート！"
#define OpenFileTitleW 93 //Text: L"再生するファイルを選択: "
#define OpenSplashFileTitleW 116 //Text: L"スプラッシュ画面用MIDIを選択: "
#define OpenBackgroundFileTitleW 61 //Text: L"背景画像を選択: "
#define StatisticsText1W 72 //Text: "Piano-FX Pro (日本語)"
#define StatisticsText2W 77 //Text: "開発者: happy_mimimix"
#define StatisticsText3W 19 //Text: "時間:"
#define StatisticsText4W 35 //Text: "ティック:"
#define StatisticsText5W 43 //Text: "マイクロ秒:"
#define StatisticsText6W 59 //Text: "フレームレート:"
#define StatisticsText7W 43 //Text: "曲のテンポ:"
#define StatisticsText8W 35 //Text: "コンボ数:"
#define StatisticsText9W 51 //Text: "クリック毎秒:"
#define StatisticsText10W 43 //Text: "同時押し数:"
#define StatisticsText11W 35 //Text: "ノート数:"
#define StatisticsText12W 75 //Text: "ノーツパーセカンド:"
#define StatisticsText13W 51 //Text: "ポリフォニー:"
#define StatisticsText14W 59 //Text: "レンダリング済:"
#define StatisticsText15W 19 //Text: "音量:"
#define StatisticsText16W 40 //Text: "ミュート中"
#define StatisticsText17W 35 //Text: "再生速度:"
#define StatisticsText18W 43 //Text: "ノート速度:"
#define StatisticsText19W 47 //Text: "Xオフセット:"
#define StatisticsText20W 47 //Text: "Yオフセット:"
#define StatisticsText21W 27 //Text: "ズーム:"
#define StatisticsText22W 67 //Text: "ウィンドウサイズ:"
#define StatisticsText23W 35 //Text: "鍵盤範囲:"
#define StatisticsText24W 59 //Text: "音符の強度閾値:"
#define StatisticsText25W 27 //Text: "スコア:"
#define StatisticsText26W 27 //Text: "レベル:"
#define StatisticsText27W 35 //Text: "自動演奏:"
#define StatisticsText28W 42 //Text: "有効化済み "
#define StatisticsText29W 50 //Text: "フルコンボ!!! "
#define StatisticsText30W 98 //Text: "デモンストレーション中... "
#define StatisticsText31W 50 //Text: "一時停止中... "
#define StatisticsText32W 113 //Text: "エラー: スコアオーバーフロー! "
#define ZoomMoveMsgW 961 //Text: "- 左クリックしてドラッグすると、画面が移動します\n- 右クリックしたままドラッグすると水平方向にズームします\n- 変更を適用するには、もう一度 「表示->移動とズーム 」をクリックします\n- 変更を元に戻すには、「表示->移動とズームをリセット 」をクリックします"
#define PropertyWindowTitleW 16 //Text: L"設定"
#define Property1TitleW 16 //Text: L"表示"
#define Property1Text1W 51 //Text: "表示する鍵盤:"
#define Property1Text2W 44 //Text: "全128鍵表示"
#define Property1Text3W 48 //Text: "曲に合わせる"
#define Property1Text4W 35 //Text: "範囲指定:"
#define Property1Text5W 16 //Text: "から"
#define Property1Text6W 43 //Text: "トラック色:"
#define Property1Text7W 40 //Text: "ランダム化"
#define Property1Text8W 27 //Text: "背景色:"
#define Property1Text9W 27 //Text: "バー色:"
#define Property1Text10W 72 //Text: "デフォルト色に戻す"
#define Property1Text11W 35 //Text: "背景画像:"
#define Property1Text12W 16 //Text: "参照"
#define Property1Text13W 32 //Text: "リセット"
#define Property1Text14W 293 //Text: "ヒント: 高度なグラフィック設定は「レンダリング」カテゴリをご確認ください。"
#define Property2TitleW 40 //Text: L"オーディオ"
#define Property2Text1W 57 //Text: "標準WinMM出力:"
#define Property2Text2W 231 //Text: "WinMMの代わりに効率的なKDMAPIを使用する（OmniMIDIが必要）"
#define Property3TitleW 48 //Text: L"レンダリング"
#define Property3Text1W 91 //Text: "高度なグラフィック設定:"
#define Property3Text2W 104 //Text: "ティックベースレンダリング"
#define Property3Text3W 72 //Text: "ピッチベンド可視化"
#define Property3Text4W 40 //Text: "等幅ノート"
#define Property3Text5W 48 //Text: "マーカー表示"
#define Property3Text6W 75 //Text: "マーカー文字コード:"
#define Property3Text7W 52 //Text: "FPSを60に固定"
#define Property3Text8W 32 //Text: "動画出力"
#define Property3Text9W 64 //Text: "デバッグ情報表示"
#define Property3Text10W 40 //Text: "統計非表示"
#define Property3Text11W 120 //Text: "重なり合った音符を非表示にする"
#define Property4TitleW 16 //Text: L"操作"
#define Property4Text1W 43 //Text: "操作の動作:"
#define Property4Text2W 75 //Text: "左右キーでスキップ:"
#define Property4Text3W 8 //Text: "秒"
#define Property4Text4W 75 //Text: "上下キーで速度変更:"
#define Property4Text5W 7 //Text: "%"
#define Property4Text6W 144 //Text: "全画面表示時でもツールバーを表示する"
#define Property4Text7W 79 //Text: "Phigros式スコアリング"
#define Property4Text8W 66 //Text: "スプラッシュMIDI:"
#define Property4Text9W 59 //Text: "音符の強度閾値:"
#define TrackWindowTitleW 48 //Text: "トラック設定"
#define TrackText1W 35 //Text: "ファイル:"
#define TrackText2W 35 //Text: "フォルダ:"
#define TrackText3W 35 //Text: "ノート数:"
#define TrackText4W 19 //Text: "長さ:"
#define TrackText5W 72 //Text: "ラグの代わりに減速"
#define TrackText6W 80 //Text: "全楽器をピアノに置換"
#define TrackText7W 16 //Text: "再生"
#define TrackText8W 16 //Text: "中止"
#define AboutWindowTitleW 56 //Text: "バージョン情報"
#define AboutText2W 16 //Text: "了解"
#define LoadWindowTitleW 48 //Text: L"読み込み中..."
#define LoadingTextW 40 //Text: "読み込み中"
#define LoadingStage1W 95 //Text: L"MIDIをメモリにコピー中..."
#define LoadingStage2W 32 //Text: L"解凍中..."
#define LoadingStage3W 80 //Text: L"音トラックを解析中..."
#define LoadingStage4W 56 //Text: L"音符を連結中..."
#define LoadingStage5W 72 //Text: L"イベントを整理中..."
#define LoadingStage6W 144 //Text: L"音符カウントの照合テーブルを作成中..."
#define ResolutionWindowTitleW 40 //Text: "解像度設定"
#define ResolutionText1W 19 //Text: "幅さ:"
#define ResolutionText2W 19 //Text: "高さ:"
#define ResolutionText3W 16 //Text: "確定"
#define ResolutionText4W 16 //Text: "取消"
#define MenuText1W 16 //Text: "開く"
#define MenuText2W 24 //Text: "閉じる"
#define MenuText3W 16 //Text: "再生"
#define MenuText4W 70 //Text: "再生/一時停止\tSpace"
#define MenuText5W 27 //Text: "停止\tEsc"
#define MenuText6W 41 //Text: "早送り\tRight"
#define MenuText7W 45 //Text: "巻き戻し\tLeft"
#define MenuText8W 67 //Text: "再生加速\tCtrl+Down"
#define MenuText9W 57 //Text: "再生減速\tCtrl+Up"
#define MenuText10W 69 //Text: "速度リセット\tCtrl+R"
#define MenuText11W 69 //Text: "ノート加速\tShift+Up"
#define MenuText12W 78 //Text: "ノート減速\tShift+Down"
#define MenuText13W 81 //Text: "ノートリセット\tShift+R"
#define MenuText14W 41 //Text: "音量上げ\tUp"
#define MenuText15W 50 //Text: "音量下げ\tDown"
#define MenuText16W 54 //Text: "ミュート\tCtrl+M"
#define MenuText17W 16 //Text: "表示"
#define MenuText18W 72 //Text: "コントロールパネル"
#define MenuText19W 32 //Text: "鍵盤表示"
#define MenuText20W 40 //Text: "最前面表示"
#define MenuText21W 71 //Text: "全画面表示\tAlt+Enter"
#define MenuText22W 103 //Text: "ウィンドウサイズ設定\tCtrl+W"
#define MenuText23W 48 //Text: "移動とズーム"
#define MenuText24W 88 //Text: "移動とズームをリセット"
#define MenuText25W 16 //Text: "設定"
#define MenuText26W 56 //Text: "バージョン情報"
#define MenuText27W 74 //Text: "Piano-FX Studioを開く"
#endif
#ifdef KOR
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 75 //Text: L"개발자: happy_mimimix"
#define MainWindowTitle3W 36 //Text: L"현재 재생: "
#define MainWindowTitle4W 36 //Text: L"렌더링 중: "
#define MainWindowTitle5W 15 //Text: L"없음"
#define MainWindowTitle6W 32 //Text: L"시작 MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 87 //Text: L"  (소프트웨어 렌더링 강제)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 113 //Text: L"Piano-FX Pro 오신 것을 환영합니다"
#define StartupStage1TextW 32 //Text: L"준비 중..."
#define StartupStage2TextW 81 //Text: L"시작 MIDI 불러오는 중..."
#define StartupStage3TextW 39 //Text: L"시작합니다!"
#define OpenFileTitleW 89 //Text: L"재생할 파일을 선택하세요: "
#define OpenSplashFileTitleW 70 //Text: L"시작 화면 MIDI 선택: "
#define OpenBackgroundFileTitleW 60 //Text: L"배경 이미지 선택: "
#define StatisticsText1W 70 //Text: "Piano-FX Pro (한국어)"
#define StatisticsText2W 75 //Text: "개발자: happy_mimimix"
#define StatisticsText3W 17 //Text: "시간:"
#define StatisticsText4W 10 //Text: "틱:"
#define StatisticsText5W 39 //Text: "마이크로초:"
#define StatisticsText6W 41 //Text: "프레임 속도:"
#define StatisticsText7W 17 //Text: "템포:"
#define StatisticsText8W 17 //Text: "콤보:"
#define StatisticsText9W 34 //Text: "초당 클릭:"
#define StatisticsText10W 34 //Text: "동시 입력:"
#define StatisticsText11W 27 //Text: "노트 수:"
#define StatisticsText12W 34 //Text: "초당 노트:"
#define StatisticsText13W 32 //Text: "폴리포니:"
#define StatisticsText14W 41 //Text: "렌더링 완료:"
#define StatisticsText15W 17 //Text: "볼륨:"
#define StatisticsText16W 22 //Text: "음소거"
#define StatisticsText17W 34 //Text: "재생 속도:"
#define StatisticsText18W 34 //Text: "노트 속도:"
#define StatisticsText19W 31 //Text: "X 오프셋:"
#define StatisticsText20W 31 //Text: "Y 오프셋:"
#define StatisticsText21W 10 //Text: "줌:"
#define StatisticsText22W 27 //Text: "창 크기:"
#define StatisticsText23W 34 //Text: "건반 범위:"
#define StatisticsText24W 65 //Text: "음표의 강도 임계값:"
#define StatisticsText25W 17 //Text: "점수:"
#define StatisticsText26W 25 //Text: "난이도:"
#define StatisticsText27W 34 //Text: "자동 연주:"
#define StatisticsText28W 9 //Text: "켬 "
#define StatisticsText29W 34 //Text: "풀 콤보!!! "
#define StatisticsText30W 51 //Text: "데모 진행 중... "
#define StatisticsText31W 41 //Text: "일시 정지... "
#define StatisticsText32W 77 //Text: "오류: 점수 오버플로우! "
#define ZoomMoveMsgW 675 //Text: "- 왼쪽 클릭 후 드래그하여 화면 이동\n- 오른쪽 클릭 후 드래그하여 가로로 확대하기\n- 변경 사항을 적용하려면 “보기->이동 / 확대” 를 다시 클릭합니다\n- 변경 사항을 취소하려면 “보기->위치 초기화” 를 클릭합니다"
#define PropertyWindowTitleW 15 //Text: L"설정"
#define Property1TitleW 15 //Text: L"화면"
#define Property1Text1W 34 //Text: "건반 표시:"
#define Property1Text2W 43 //Text: "전체 128건반"
#define Property1Text3W 31 //Text: "곡에 맞춤"
#define Property1Text4W 34 //Text: "범위 지정:"
#define Property1Text5W 15 //Text: "부터"
#define Property1Text6W 34 //Text: "트랙 색상:"
#define Property1Text7W 29 //Text: "무작위화"
#define Property1Text8W 34 //Text: "배경 색상:"
#define Property1Text9W 27 //Text: "바 색상:"
#define Property1Text10W 39 //Text: "기본값 복원"
#define Property1Text11W 41 //Text: "배경 이미지:"
#define Property1Text12W 29 //Text: "찾아보기"
#define Property1Text13W 22 //Text: "초기화"
#define Property1Text14W 205 //Text: "힌트: 고급 그래픽 렌더링 옵션은 '렌더링' 항목에서 확인하세요."
#define Property2TitleW 22 //Text: L"오디오"
#define Property2Text1W 59 //Text: "표준 WinMM 출력:"
#define Property2Text2W 179 //Text: "WinMM 대신 더 효율적인 KDMAPI 사용 (OmniMIDI 필요)"
#define Property3TitleW 22 //Text: L"렌더링"
#define Property3Text1W 82 //Text: "고급 그래픽 렌더링 설정:"
#define Property3Text2W 48 //Text: "틱 기반 렌더링"
#define Property3Text3W 55 //Text: "피치 벤드 시각화"
#define Property3Text4W 48 //Text: "동일 너비 노트"
#define Property3Text5W 31 //Text: "마커 표시"
#define Property3Text6W 41 //Text: "마커 인코딩:"
#define Property3Text7W 53 //Text: "FPS 60으로 고정"
#define Property3Text8W 39 //Text: "동영상 출력"
#define Property3Text9W 55 //Text: "디버그 정보 표시"
#define Property3Text10W 39 //Text: "통계 숨기기"
#define Property3Text11W 70 //Text: "중복된 음표를 숨기기"
#define Property4TitleW 15 //Text: L"제어"
#define Property4Text1W 51 //Text: "제어 동작 설정:"
#define Property4Text2W 51 //Text: "좌우 키 이동량:"
#define Property4Text3W 7 //Text: "초"
#define Property4Text4W 60 //Text: "상하 키 속도 변경:"
#define Property4Text5W 7 //Text: "%"
#define Property4Text6W 96 //Text: "전체 화면에서 도구 모음 표시"
#define Property4Text7W 64 //Text: "Phigros 스타일 점수"
#define Property4Text8W 35 //Text: "시작 MIDI:"
#define Property4Text9W 65 //Text: "음표의 강도 임계값:"
#define TrackWindowTitleW 31 //Text: "트랙 설정"
#define TrackText1W 17 //Text: "파일:"
#define TrackText2W 17 //Text: "폴더:"
#define TrackText3W 27 //Text: "노트 수:"
#define TrackText4W 17 //Text: "길이:"
#define TrackText5W 41 //Text: "렉 대신 감속"
#define TrackText6W 87 //Text: "모든 악기를 피아노로 변경"
#define TrackText7W 15 //Text: "재생"
#define TrackText8W 15 //Text: "중단"
#define AboutWindowTitleW 15 //Text: "정보"
#define AboutText2W 15 //Text: "확인"
#define LoadWindowTitleW 32 //Text: L"로딩 중..."
#define LoadingTextW 39 //Text: "불러오는 중"
#define LoadingStage1W 73 //Text: L"MIDI 메모리 복사 중..."
#define LoadingStage2W 49 //Text: L"압축 해제 중..."
#define LoadingStage3W 49 //Text: L"트랙 분석 중..."
#define LoadingStage4W 49 //Text: L"노트 연결 중..."
#define LoadingStage5W 56 //Text: L"이벤트 정렬 중..."
#define LoadingStage6W 113 //Text: L"노트 카운트 조회 테이블 준비 중..."
#define ResolutionWindowTitleW 39 //Text: "해상도 설정"
#define ResolutionText1W 17 //Text: "너비:"
#define ResolutionText2W 17 //Text: "높이:"
#define ResolutionText3W 15 //Text: "확인"
#define ResolutionText4W 15 //Text: "취소"
#define MenuText1W 15 //Text: "열기"
#define MenuText2W 15 //Text: "닫기"
#define MenuText3W 15 //Text: "재생"
#define MenuText4W 66 //Text: "재생/일시정지\tSpace"
#define MenuText5W 25 //Text: "중지\tEsc"
#define MenuText6W 46 //Text: "빨리감기\tRight"
#define MenuText7W 27 //Text: "뒤로\tLeft"
#define MenuText8W 57 //Text: "빠르게\tCtrl+Down"
#define MenuText9W 47 //Text: "느리게\tCtrl+Up"
#define MenuText10W 60 //Text: "속도 초기화\tCtrl+R"
#define MenuText11W 67 //Text: "노트 빠르게\tShift+Up"
#define MenuText12W 77 //Text: "노트 느리게\tShift+Down"
#define MenuText13W 63 //Text: "노트 초기화\tShift+R"
#define MenuText14W 33 //Text: "볼륨 업\tUp"
#define MenuText15W 49 //Text: "볼륨 다운\tDown"
#define MenuText16W 44 //Text: "음소거\tCtrl+M"
#define MenuText17W 15 //Text: "보기"
#define MenuText18W 31 //Text: "제어 패널"
#define MenuText19W 31 //Text: "건반 표시"
#define MenuText20W 24 //Text: "항상 위"
#define MenuText21W 63 //Text: "전체 화면\tAlt+Enter"
#define MenuText22W 64 //Text: "창 크기 설정\tCtrl+W"
#define MenuText23W 32 //Text: "이동/확대"
#define MenuText24W 39 //Text: "위치 초기화"
#define MenuText25W 15 //Text: "설정"
#define MenuText26W 15 //Text: "정보"
#define MenuText27W 55 //Text: "특수 효과 에디터"
#endif
#ifdef RUS
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 96 //Text: L"Разработчик: happy_mimimix"
#define MainWindowTitle3W 54 //Text: L"Сейчас играет: "
#define MainWindowTitle4W 71 //Text: L"Сейчас рендерится: "
#define MainWindowTitle5W 13 //Text: L"Нет"
#define MainWindowTitle6W 49 //Text: L"Заставка MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 153 //Text: L"  (Принудительный программный рендеринг)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 113 //Text: L"Добро пожаловать в Piano-FX Pro"
#define StartupStage1TextW 49 //Text: L"Подготовка..."
#define StartupStage2TextW 89 //Text: L"Загрузка заставки MIDI..."
#define StartupStage3TextW 31 //Text: L"Поехали!"
#define OpenFileTitleW 133 //Text: L"Выберите файл для воспроизведения: "
#define OpenSplashFileTitleW 123 //Text: L"Выберите MIDI-файл для заставки: "
#define OpenBackgroundFileTitleW 116 //Text: L"Выберите фоновое изображение: "
#define StatisticsText1W 75 //Text: "Piano-FX Pro (русский)"
#define StatisticsText2W 96 //Text: "Разработчик: happy_mimimix"
#define StatisticsText3W 23 //Text: "Время:"
#define StatisticsText4W 19 //Text: "Тики:"
#define StatisticsText5W 53 //Text: "Микросекунды:"
#define StatisticsText6W 57 //Text: "частота кадров:"
#define StatisticsText7W 40 //Text: "Темп песни:"
#define StatisticsText8W 23 //Text: "Комбо:"
#define StatisticsText9W 63 //Text: "Кликов в секунду:"
#define StatisticsText10W 84 //Text: "Одновременные прессы:"
#define StatisticsText11W 21 //Text: "Ноты:"
#define StatisticsText12W 51 //Text: "Нот в секунду:"
#define StatisticsText13W 41 //Text: "Полифония:"
#define StatisticsText14W 49 //Text: "Отрендерено:"
#define StatisticsText15W 38 //Text: "Громкость:"
#define StatisticsText16W 36 //Text: "БЕЗ ЗВУКА"
#define StatisticsText17W 35 //Text: "Скорость:"
#define StatisticsText18W 49 //Text: "Скорость нот:"
#define StatisticsText19W 43 //Text: "Смещение X:"
#define StatisticsText20W 43 //Text: "Смещение Y:"
#define StatisticsText21W 33 //Text: "Масштаб:"
#define StatisticsText22W 44 //Text: "Размер окна:"
#define StatisticsText23W 63 //Text: "Диапазон клавиш:"
#define StatisticsText24W 95 //Text: "Порог интенсивности ноты:"
#define StatisticsText25W 19 //Text: "Счет:"
#define StatisticsText26W 31 //Text: "Уровень:"
#define StatisticsText27W 39 //Text: "Автовоспр:"
#define StatisticsText28W 15 //Text: "ВКЛ "
#define StatisticsText29W 66 //Text: "ПОЛНЫЙ КОМБО!!! "
#define StatisticsText30W 59 //Text: "Демонстрация... "
#define StatisticsText31W 30 //Text: "Пауза... "
#define StatisticsText32W 109 //Text: "ОШИБКА: Переполнение счета! "
#define ZoomMoveMsgW 1,041 //Text: "- Щелкните левой кнопкой мыши и перетащите, чтобы переместить экран\n- Щелкните правой кнопкой мыши и перетащите, чтобы увеличить масштаб по горизонтали\n- Нажмите 'Вид -> Позиция и масштаб' еще раз, чтобы применить изменения\n- Нажмите 'Вид -> Сброс позиции', чтобы отменить изменения"
#define PropertyWindowTitleW 36 //Text: L"Настройки"
#define Property1TitleW 44 //Text: L"Внешний вид"
#define Property1Text1W 86 //Text: "Отображаемые клавиши:"
#define Property1Text2W 53 //Text: "Все 128 клавиш"
#define Property1Text3W 50 //Text: "По композиции"
#define Property1Text4W 35 //Text: "Диапазон:"
#define Property1Text5W 9 //Text: "до"
#define Property1Text6W 56 //Text: "Цвета дорожек:"
#define Property1Text7W 60 //Text: "Случайные цвета"
#define Property1Text8W 39 //Text: "Цвет фона:"
#define Property1Text9W 47 //Text: "Цвет полосы:"
#define Property1Text10W 54 //Text: "Сбросить цвета"
#define Property1Text11W 79 //Text: "Фоновое изображение:"
#define Property1Text12W 21 //Text: "Обзор"
#define Property1Text13W 20 //Text: "Сброс"
#define Property1Text14W 273 //Text: "Подсказка: дополнительные параметры графики см. в категории «Рендеринг»."
#define Property2TitleW 16 //Text: L"Звук"
#define Property2Text1W 98 //Text: "Стандартный вывод WinMM:"
#define Property2Text2W 201 //Text: "Использовать KDMAPI вместо WinMM (требуется OmniMIDI)"
#define Property3TitleW 36 //Text: L"Рендеринг"
#define Property3Text1W 117 //Text: "Расширенные настройки графики:"
#define Property3Text2W 68 //Text: "Рендеринг по тикам"
#define Property3Text3W 73 //Text: "Визуализация бендов"
#define Property3Text4W 65 //Text: "Равная ширина нот"
#define Property3Text5W 73 //Text: "Показывать маркеры"
#define Property3Text6W 74 //Text: "Кодировка маркеров:"
#define Property3Text7W 75 //Text: "Ограничить FPS до 60"
#define Property3Text8W 51 //Text: "Экспорт видео"
#define Property3Text9W 131 //Text: "Показывать отладочную информацию"
#define Property3Text10W 67 //Text: "Скрыть статистику"
#define Property3Text11W 112 //Text: "Скрыть перекрывающиеся ноты"
#define Property4TitleW 41 //Text: L"Управление"
#define Property4Text1W 119 //Text: "Поведение элементов управления:"
#define Property4Text2W 77 //Text: "Перемотка стрелками:"
#define Property4Text3W 11 //Text: "сек"
#define Property4Text4W 109 //Text: "Изменение скорости стрелками:"
#define Property4Text5W 7 //Text: "%"
#define Property4Text6W 156 //Text: "Не скрывать панель в полноэкранном режиме"
#define Property4Text7W 75 //Text: "Система счета Phigros"
#define Property4Text8W 77 //Text: "Приветственный MIDI:"
#define Property4Text9W 95 //Text: "Порог интенсивности ноты:"
#define TrackWindowTitleW 58 //Text: "Настройки трека"
#define TrackText1W 20 //Text: "Файл:"
#define TrackText2W 23 //Text: "Папка:"
#define TrackText3W 15 //Text: "Нот:"
#define TrackText4W 51 //Text: "Длительность:"
#define TrackText5W 87 //Text: "Замедление вместо лагов"
#define TrackText6W 132 //Text: "Заменить все инструменты на пианино"
#define TrackText7W 24 //Text: "Играть"
#define TrackText8W 25 //Text: "Отмена"
#define AboutWindowTitleW 43 //Text: "О программе"
#define AboutText2W 25 //Text: "Хорошо"
#define LoadWindowTitleW 39 //Text: L"Загрузка..."
#define LoadingTextW 31 //Text: "Загрузка"
#define LoadingStage1W 102 //Text: L"Копирование MIDI в память..."
#define LoadingStage2W 47 //Text: L"Распаковка..."
#define LoadingStage3W 58 //Text: L"Анализ треков..."
#define LoadingStage4W 63 //Text: L"Соединение нот..."
#define LoadingStage5W 79 //Text: L"Сортировка событий..."
#define LoadingStage6W 161 //Text: L"Подготовка таблицы поиска количества нот..."
#define ResolutionWindowTitleW 41 //Text: "Разрешение"
#define ResolutionText1W 29 //Text: "Ширина:"
#define ResolutionText2W 27 //Text: "Высота:"
#define ResolutionText3W 10 //Text: "ОК"
#define ResolutionText4W 25 //Text: "Отмена"
#define MenuText1W 31 //Text: "Открыть"
#define MenuText2W 29 //Text: "Закрыть"
#define MenuText3W 24 //Text: "Играть"
#define MenuText4W 64 //Text: "Воспр./Пауза\tSpace"
#define MenuText5W 27 //Text: "Стоп\tEsc"
#define MenuText6W 41 //Text: "Вперед\tRight"
#define MenuText7W 33 //Text: "Назад\tLeft"
#define MenuText8W 67 //Text: "Ускорить\tCtrl+Down"
#define MenuText9W 62 //Text: "Замедлить\tCtrl+Up"
#define MenuText10W 74 //Text: "Сброс скорости\tCtrl+R"
#define MenuText11W 78 //Text: "Быстрые ноты\tShift+Up"
#define MenuText12W 97 //Text: "Медленные ноты\tShift+Down"
#define MenuText13W 59 //Text: "Сброс нот\tShift+R"
#define MenuText14W 33 //Text: "Громче\tUp"
#define MenuText15W 35 //Text: "Тише\tDown"
#define MenuText16W 55 //Text: "Без звука\tCtrl+M"
#define MenuText17W 13 //Text: "Вид"
#define MenuText18W 67 //Text: "Панель управления"
#define MenuText19W 41 //Text: "Клавиатура"
#define MenuText20W 43 //Text: "Поверх окон"
#define MenuText21W 79 //Text: "Полный экран\tAlt+Enter"
#define MenuText22W 65 //Text: "Размер окна\tCtrl+W"
#define MenuText23W 65 //Text: "Позиция и масштаб"
#define MenuText24W 49 //Text: "Сброс позиции"
#define MenuText25W 36 //Text: "Настройки"
#define MenuText26W 43 //Text: "О программе"
#define MenuText27W 83 //Text: "Открыть Piano-FX Studio"
#endif
#ifdef DRN
#define MainWindowTitle1W 113 //Text: L"ЖЩ1 ЯЭ4 ДЭ5 ГГ1 ЪМ2 ТЭ4 ЩС4"
#define MainWindowTitle2W 99 //Text: L"КБ1 ФА1 ЖЭ3: happy_mimimix"
#define MainWindowTitle3W 67 //Text: L"ЖЖ4 ЗБ4 БО1 ФГ4: "
#define MainWindowTitle4W 71 //Text: L"ЖЖ4 ЗБ4 ЩЩ4 РН3: "
#define MainWindowTitle5W 31 //Text: L"КК4 ЩП2"
#define MainWindowTitle6W 54 //Text: L"ХЩ1 ЯЫ2 MIDI+"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 108 //Text: L"  (ЪВ2 ЖИ4 РЩ3 ЙП4 ЩЩ4 РН3)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 179 //Text: L"ХЩ1 ЯЫ2 ШИ3 ЯК4 ЖЩ1 ЯЭ4 ДЭ5 ГГ1 ЪМ2 ТЭ4 ЩС4"
#define StartupStage1TextW 55 //Text: L"ЖЬ3 БЙ4 ЖК1..."
#define StartupStage2TextW 82 //Text: L"ЗБ3 РЕ4 ХЩ1 ЯЫ2 MIDI+"
#define StartupStage3TextW 33 //Text: L"ЧЕ1 ФА1! "
#define OpenFileTitleW 181 //Text: L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩВ3 ЯУ4 БО1 ФГ4 ДЭ5 ВД2 ЙП4: "
#define OpenSplashFileTitleW 244 //Text: L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩИ1 ВГ4 ЯК4 ЗХ4 ХЩ1 ЯЫ2 ПЫ2 МЕ4 ДЭ5 ВД2 ЙП4: "
#define OpenBackgroundFileTitleW 241 //Text: L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩИ1 ВГ4 ЯК4 ЗХ4 БЙ4 ЙЫ3 ТЕ2 ЩВ4 ДЭ5 ВД2 ЙП4: "
#define StatisticsText1W 101 //Text: "Piano-FX Pro (DoubleArinoglish)"
#define StatisticsText2W 99 //Text: "КБ1 ФА1 ЖЭ3: happy_mimimix"
#define StatisticsText3W 33 //Text: "ШИ2 ЧГ2:"
#define StatisticsText4W 16 //Text: "КЭ4:"
#define StatisticsText5W 31 //Text: "ВЙ1 МС3:"
#define StatisticsText6W 33 //Text: "ЖД1 ЛЁ4:"
#define StatisticsText7W 61 //Text: "ЯМ1 ЯЕ4 СЕ4 ЛЁ4:"
#define StatisticsText8W 31 //Text: "ЛП2 ЙИ1:"
#define StatisticsText9W 65 //Text: "МЙ3 МС3 ШФ3 СЕ4:"
#define StatisticsText10W 67 //Text: "ШФ3 ЖИ3 ГЭ4 ШЕ4:"
#define StatisticsText11W 49 //Text: "ЯМ1 ФЕ2 ШЕ4:"
#define StatisticsText12W 63 //Text: "МЙ3 МС3 ЯН3 ЗФ4:"
#define StatisticsText13W 63 //Text: "ТК2 ШИ2 ЯН3 ЗФ4:"
#define StatisticsText14W 51 //Text: "ЯИ3 ЩЩ4 РН3:"
#define StatisticsText15W 31 //Text: "ЯМ1 ЛВ4:"
#define StatisticsText16W 30 //Text: "ЙЫ4 ЯМ1"
#define StatisticsText17W 61 //Text: "БО1 ФГ4 СЕ4 ДЕ5:"
#define StatisticsText18W 62 //Text: "ЯМ1 ФЕ2 СЕ4 ДЕ5:"
#define StatisticsText19W 37 //Text: "X ПП1 ЯИ2:"
#define StatisticsText20W 37 //Text: "Y ПП1 ЯИ2:"
#define StatisticsText21W 31 //Text: "СХ1 ФГ4:"
#define StatisticsText22W 68 //Text: "ЧШ1 КФ3 ДА4 ЩС3:"
#define StatisticsText23W 63 //Text: "ЪМ2 ЙП4 ФН4 ВЙ2:"
#define StatisticsText24W 95 //Text: "ЯМ1 ФЕ2 ЛИ4 ДЕ4 ЯЕ4 ЖИ2:"
#define StatisticsText25W 34 //Text: "ФД1 ШЕ4:"
#define StatisticsText26W 62 //Text: "ЪЕ3 МЕ4 НН2 ДЕ4:"
#define StatisticsText27W 62 //Text: "ЗИ4 ДК4 ЯН3 ЗФ4:"
#define StatisticsText28W 31 //Text: "КБ1 ЪИ3 "
#define StatisticsText29W 81 //Text: "GON1 ЩИ3 ЪЩ2 ЛП2!!! "
#define StatisticsText30W 89 //Text: "ЗИ4 ДК4 ЯН3 ШИ4 ЖК1... "
#define StatisticsText31W 72 //Text: "ЯФ2 ЩИ4 ЗН4 ТЫ2... "
#define StatisticsText32W 98 //Text: "ЦХ4 ВЕ4: ФД1 ШЕ4 ЯИ4 ЧЕ1! "
#define ZoomMoveMsgW 903 //Text: "- ЗХ3 ЙП4 ДН1 ЙИ1 БЫ4 ТХ1 ДК4 КЭ3 ЯИ2 ДК4 ПЫ2 МЕ4\n- ЯФ4 ЙП4 ДН1 ЙИ1 БЫ4 ТХ1 ДК1 КЭ3 ШЪ3 ПЫ2 СХ1 ФГ4\n- ЗБ4 ЦИ4 ДП3 ЙИ1 'ЧА2 КН4 -> ЯИ2 ДК4 ХЭ2 СХ1 ФГ4' КЭ3 ЯЫ4 ЯК4 ГЖ1 ГБ3\n- ДП3 ЙИ1 'ЧА2 КН4 -> ЧК2 ЖИ4 ЯИ2 ДК4 ХЭ2 СХ1 ФГ4' КЭ3 ЧЭ4 ЩС1 ГЖ1 ГБ3"
#define PropertyWindowTitleW 33 //Text: L"ШЭ4 ЖИ4"
#define Property1TitleW 30 //Text: L"ШИ4 ЙТ2"
#define Property1Text1W 68 //Text: "ЪМ2 ЙП4 ЩП3 ШИ4:"
#define Property1Text2W 60 //Text: "ЪЩ2 БЕ4 128 ЙП4"
#define Property1Text3W 99 //Text: "ГД1 ЙЕ4 MIDI+ ЗИ4 ШИ4 ЯЫ4"
#define Property1Text4W 65 //Text: "ЖИ3 ДЫ4 ФН4 ВЙ2:"
#define Property1Text5W 31 //Text: "ЖИ2 ДУ4"
#define Property1Text6W 63 //Text: "ЯМ1 ГЪ3 ЯН2 СЭ4:"
#define Property1Text7W 29 //Text: "СЪ2 ЙИ1"
#define Property1Text8W 62 //Text: "БЙ4 ЙЫ3 ЯН2 СЭ4:"
#define Property1Text9W 63 //Text: "ХЖ2 ТС2 ЯН2 СЭ4:"
#define Property1Text10W 61 //Text: "ЧК2 ЖИ4 ЯН2 СЭ4"
#define Property1Text11W 61 //Text: "БЙ4 ЙЫ3 ТЕ2 ПП4:"
#define Property1Text12W 31 //Text: "ЛЮ2 ЛН3"
#define Property1Text13W 31 //Text: "ЧК2 ЖИ4"
#define Property1Text14W 261 //Text: "ЪП2 ВГ3 'ЩЩ4 РН3' ЛЙ4 БЗ2 ЧА2 КН4 ГЖ4 ДХ1 ГУ1 ЙИ2 ЩЩ4 РН3 ШЭ4 ЖИ4."
#define Property2TitleW 30 //Text: L"ЯМ1 ПМ2"
#define Property2Text1W 95 //Text: "БС1 ЖЬ3 WINMM+ ШЕ1 ЧЕ1:"
#define Property2Text2W 206 //Text: "ШИ3 ЯК4 KDMAPI+ ДБ4 ТИ4 WINMM+ (ЩЕ1 ЯУ4 OMNI MIDI+)"
#define Property3TitleW 33 //Text: L"ЩЩ4 РН3"
#define Property3Text1W 131 //Text: "ГУ1 ЙИ2 ТЕ2 ЩЫ2 ЩЩ4 РН3 ПЙ4 ЖИ4:"
#define Property3Text2W 79 //Text: "ЙИ1 ЯЕ2 КЭ4 ЩЩ4 РН3"
#define Property3Text3W 77 //Text: "КЭ3 ШИ4 ХЦ4 ВН1 ЯМ1"
#define Property3Text4W 65 //Text: "ДЖ3 КЩ1 ЯМ1 ФЕ2"
#define Property3Text5W 63 //Text: "ЩП3 ШИ4 БС1 ЙИ4"
#define Property3Text6W 94 //Text: "ВД2 БД3 БП1 МА3 ГЭ2 ШИ4:"
#define Property3Text7W 107 //Text: "СХ3 ДЫ4 ЖД1 ЛЁ4 ЖИ4 60 ЖД1"
#define Property3Text8W 62 //Text: "ДУ3 ЧЕ1 ШИ4 ПМ2"
#define Property3Text9W 102 //Text: "ЩП3 ШИ4 ТС2 ШИ4 ЩМ4 ЩИ1"
#define Property3Text10W 96 //Text: "ЯМ3 ЦГ2 ТК3 ЙИ4 ЩМ4 ЩИ1"
#define Property3Text11W 91 //Text: "ЯМ3 ЦГ2 ЧК2 ДЗ2 ЯМ1 ФЕ2"
#define Property4TitleW 31 //Text: L"КК4 ЖИ4"
#define Property4Text1W 101 //Text: "КК4 ЖИ4 ЩЫ2 ВЙ2 ШЭ4 ЖИ4:"
#define Property4Text2W 90 //Text: "ЗХ3 ЯФ4 ЙП4 ТФ2 ТС4 ГХ4:"
#define Property4Text3W 14 //Text: "МС3"
#define Property4Text4W 96 //Text: "ШГ4 ЩЯ4 ЙП4 ТФ2 ЙЯ1 СЕ4:"
#define Property4Text5W 46 //Text: "ФД1 ЖИ1 ББ3"
#define Property4Text6W 174 //Text: "ЪЩ2 ПЫ2 МО2 ШИ4 ЩЯ4 БЕ4 ЯМ3 ЦГ2 ГК1 ЙЕ4 ТС2"
#define Property4Text7W 133 //Text: "PHIGROS+ ФЖ1 ГЭ2 ЙИ4 ФД1 ЩИ4 ТК3"
#define Property4Text8W 57 //Text: "ХЩ1 ЯЫ2 MIDI+:"
#define Property4Text9W 95 //Text: "ЯМ1 ФЕ2 ЛИ4 ДЕ4 ЯЕ4 ЖИ2:"
#define TrackWindowTitleW 64 //Text: "ЯМ1 ГЪ3 ШЭ4 ЖИ4"
#define TrackText1W 31 //Text: "ВД3 ЙП4:"
#define TrackText2W 31 //Text: "ЛЕ4 ЙЫ4:"
#define TrackText3W 49 //Text: "ЯМ1 ФЕ2 ШЕ4:"
#define TrackText4W 33 //Text: "ШИ1 ЧГ2:"
#define TrackText5W 105 //Text: "ЙП3 СЕ4 ER2 БЕ2 ШИ4 КА3 ДЬ4"
#define TrackText6W 154 //Text: "ЙВ1 СХ3 ЯФ3 ЯТ4 ЪИ4 ТИ4 ХЩ4 ЧЖ2 ГГ1 ЪМ2"
#define TrackText7W 29 //Text: "БО1 ФГ4"
#define TrackText8W 33 //Text: "ЖК1 ЖИ3"
#define AboutWindowTitleW 30 //Text: "ГЩ1 ЯЕ2"
#define AboutText2W 29 //Text: "ХУ3 ДЭ5"
#define LoadWindowTitleW 53 //Text: L"ЙЯ1 ЗБ3 ЖК1..."
#define LoadingTextW 62 //Text: "ЖЖ4 ЗБ4 ДЕ2 ЪЕ3"
#define LoadingStage1W 164 //Text: L"ЖЖ4 ЗБ4 ЙВ1 ВД2 ЙП4 ФЕ4 ЖИ4 ДУ4 НЙ4 ЦЬ2..."
#define LoadingStage2W 84 //Text: L"ЖЖ4 ЗБ4 ЙЗ3 ЯА1 СХ1..."
#define LoadingStage3W 103 //Text: L"ЖЖ4 ЗБ4 ЙЗ3 ЩИ1 ЯМ1 ГЪ3..."
#define LoadingStage4W 101 //Text: L"ЖЖ4 ЗБ4 ЛП2 ЙИ1 ЯМ1 ФЕ2..."
#define LoadingStage5W 107 //Text: L"ЖЖ4 ЗБ4 ЖЖ3 ЛИ3 ШИ1 ЙП4..."
#define LoadingStage6W 164 //Text: L"ЖЖ4 ЗБ4 ЖЬ3 БЙ4 ЯМ1 ФЕ2 ЙИ4 ШЕ4 ЧА2 БС3..."
#define ResolutionWindowTitleW 79 //Text: "ШЭ4 ЖИ4 ФД1 БП4 ЛЁ4"
#define ResolutionText1W 19 //Text: "КЩ1:"
#define ResolutionText2W 15 //Text: "ГУ1:"
#define ResolutionText3W 29 //Text: "ЪТ4 РД4"
#define ResolutionText4W 31 //Text: "ЪЕ3 ЩС1"
#define MenuText1W 29 //Text: "ДА3 КБ1"
#define MenuText2W 30 //Text: "ГЩ1 БИ4"
#define MenuText3W 29 //Text: "ЯН3 ЗФ4"
#define MenuText4W 79 //Text: "БО1 ФГ4/ЗН4 ТЫ2\tSpace"
#define MenuText5W 41 //Text: "ТЫ2 ЖИ3\tEsc"
#define MenuText6W 46 //Text: "КЧ4 ЙМ4\tRight"
#define MenuText7W 41 //Text: "КЧ4 ТЪ4\tLeft"
#define MenuText8W 93 //Text: "БО1 ФГ4 ЙЯ1 СЕ4\tCtrl+Down"
#define MenuText9W 84 //Text: "БО1 ФГ4 ЙП3 СЕ4\tCtrl+Up"
#define MenuText10W 83 //Text: "БО1 ФГ4 ЧК2 ЖИ4\tCtrl+R"
#define MenuText11W 88 //Text: "ЯМ1 ФЕ2 ЙЯ1 СЕ4\tShift+Up"
#define MenuText12W 97 //Text: "ЯМ1 ФЕ2 ЙП3 СЕ4\tShift+Down"
#define MenuText13W 87 //Text: "ЧК2 ЖИ4 ЯМ1 ФЕ2\tShift+R"
#define MenuText14W 53 //Text: "ЯМ1 ЛВ4 ЙЯ1\tUp"
#define MenuText15W 62 //Text: "ЯМ1 ЛВ4 ЙП3\tDown"
#define MenuText16W 52 //Text: "ЙЫ4 ЯМ1\tCtrl+M"
#define MenuText17W 29 //Text: "ЧА2 КН4"
#define MenuText18W 42 //Text: "ГК1 ЙЕ4 ТС2"
#define MenuText19W 29 //Text: "ЙП4 ПН2"
#define MenuText20W 65 //Text: "ЧШ1 КФ3 ЖИ4 ДЫ3"
#define MenuText21W 99 //Text: "ЪЩ2 ПЫ2 ЩП3 ШИ4\tAlt+Enter"
#define MenuText22W 123 //Text: "ШЭ4 ЖИ4 ЧШ1 КФ3 ДА4 ЩС3\tCtrl+W"
#define MenuText23W 74 //Text: "ЯИ2 ДК4 ХЭ2 СХ1 ФГ4"
#define MenuText24W 107 //Text: "ЧК2 ЖИ4 ЯИ2 ДК4 ХЭ2 СХ1 ФГ4"
#define MenuText25W 33 //Text: "ШЭ4 ЖИ4"
#define MenuText26W 30 //Text: "ГЩ1 ЯЕ2"
#define MenuText27W 107 //Text: "ГГ1 ЪМ2 ТЭ4 ЩС4 БП1 ЙИ1 ЪИ4"
#endif
#ifdef KOP
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 75 //Text: L"제작자: happy_mimimix"
#define MainWindowTitle3W 36 //Text: L"현재 연주: "
#define MainWindowTitle4W 53 //Text: L"화면 그리기 중: "
#define MainWindowTitle5W 15 //Text: L"없음"
#define MainWindowTitle6W 32 //Text: L"기동 MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 87 //Text: L"  (소프트웨어 렌더링 강제)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 103 //Text: L"Piano-FX Pro 열렬히 환영합니다"
#define StartupStage1TextW 69 //Text: L"준비하고 있습니다..."
#define StartupStage2TextW 88 //Text: L"기동 MIDI 불러들이는 중..."
#define StartupStage3TextW 39 //Text: L"기동합니다!"
#define OpenFileTitleW 97 //Text: L"연주할 파일을 선택하십시오: "
#define OpenSplashFileTitleW 70 //Text: L"기동 화면 MIDI 선택: "
#define OpenBackgroundFileTitleW 51 //Text: L"배경화상 선택: "
#define StatisticsText1W 70 //Text: "Piano-FX Pro (조선말)"
#define StatisticsText2W 75 //Text: "제작자: happy_mimimix"
#define StatisticsText3W 17 //Text: "시간:"
#define StatisticsText4W 10 //Text: "틱:"
#define StatisticsText5W 39 //Text: "마이크로초:"
#define StatisticsText6W 41 //Text: "초당 프레임:"
#define StatisticsText7W 17 //Text: "템포:"
#define StatisticsText8W 17 //Text: "연속:"
#define StatisticsText9W 34 //Text: "초당 클릭:"
#define StatisticsText10W 34 //Text: "동시 입력:"
#define StatisticsText11W 27 //Text: "음표 수:"
#define StatisticsText12W 34 //Text: "초당 음표:"
#define StatisticsText13W 17 //Text: "다성:"
#define StatisticsText14W 58 //Text: "화면 그리기 완료:"
#define StatisticsText15W 17 //Text: "음량:"
#define StatisticsText16W 15 //Text: "무음"
#define StatisticsText17W 34 //Text: "연주 속도:"
#define StatisticsText18W 34 //Text: "음표 속도:"
#define StatisticsText19W 31 //Text: "X 오프셋:"
#define StatisticsText20W 31 //Text: "Y 오프셋:"
#define StatisticsText21W 17 //Text: "확대:"
#define StatisticsText22W 27 //Text: "창 크기:"
#define StatisticsText23W 34 //Text: "건반 범위:"
#define StatisticsText24W 58 //Text: "음표 세기 문턱값:"
#define StatisticsText25W 17 //Text: "점수:"
#define StatisticsText26W 17 //Text: "난도:"
#define StatisticsText27W 34 //Text: "자동 연주:"
#define StatisticsText28W 17 //Text: "켜짐 "
#define StatisticsText29W 39 //Text: "전음정타!!! "
#define StatisticsText30W 51 //Text: "시범 연주 중... "
#define StatisticsText31W 41 //Text: "일시 정지... "
#define StatisticsText32W 55 //Text: "오류: 점수 넘침! "
#define ZoomMoveMsgW 759 //Text: "- 왼쪽 버튼을 클릭한 다음 드래그하여 화면을 옮기십시오\n- 오른쪽 버튼을 클릭한 다음 드래그하여 가로로 확대하십시오\n- 변경을 적용하려면 \"보기->이동 / 확대\"를 다시 누르십시오\n- 변경을 취소하려면 \"보기->위치 초기화\"를 누르십시오"
#define PropertyWindowTitleW 15 //Text: L"설정"
#define Property1TitleW 15 //Text: L"화면"
#define Property1Text1W 34 //Text: "건반 표시:"
#define Property1Text2W 43 //Text: "전부 128건반"
#define Property1Text3W 39 //Text: "곡에 맞추기"
#define Property1Text4W 34 //Text: "범위 설정:"
#define Property1Text5W 15 //Text: "부터"
#define Property1Text6W 34 //Text: "성부 색상:"
#define Property1Text7W 22 //Text: "무작위"
#define Property1Text8W 34 //Text: "배경 색상:"
#define Property1Text9W 34 //Text: "막대 색상:"
#define Property1Text10W 39 //Text: "기본값 복원"
#define Property1Text11W 34 //Text: "배경 그림:"
#define Property1Text12W 29 //Text: "찾아보기"
#define Property1Text13W 22 //Text: "초기화"
#define Property1Text14W 231 //Text: "힌트: 고급 화상그리기(렌더링) 설정은 '렌더링' 항목에서 확인하십시오."
#define Property2TitleW 15 //Text: L"음향"
#define Property2Text1W 59 //Text: "표준 WinMM 출력:"
#define Property2Text2W 187 //Text: "WinMM 대신 더 효율적인 KDMAPI 리용 (OmniMIDI 필요함)"
#define Property3TitleW 22 //Text: L"렌더링"
#define Property3Text1W 73 //Text: "고급 화상그리기 설정:"
#define Property3Text2W 48 //Text: "틱 기반 그리기"
#define Property3Text3W 55 //Text: "피치 벤드 시각화"
#define Property3Text4W 41 //Text: "동일 폭 음표"
#define Property3Text5W 31 //Text: "마커 표시"
#define Property3Text6W 41 //Text: "마커 인코딩:"
#define Property3Text7W 61 //Text: "FPS를 60으로 고정"
#define Property3Text8W 39 //Text: "동영상 출력"
#define Property3Text9W 55 //Text: "디버그 정보 표시"
#define Property3Text10W 39 //Text: "통계 숨기기"
#define Property3Text11W 63 //Text: "겹치는 음표 숨기기"
#define Property4TitleW 15 //Text: L"조작"
#define Property4Text1W 51 //Text: "조작 동작 설정:"
#define Property4Text2W 51 //Text: "좌우 키 이동량:"
#define Property4Text3W 7 //Text: "초"
#define Property4Text4W 60 //Text: "상하 키 속도 변경:"
#define Property4Text5W 7 //Text: "%"
#define Property4Text6W 94 //Text: "전체 화면에서 도구막대 표시"
#define Property4Text7W 64 //Text: "Phigros류 점수 방식"
#define Property4Text8W 35 //Text: "기동 MIDI:"
#define Property4Text9W 58 //Text: "음표 세기 문턱값:"
#define TrackWindowTitleW 31 //Text: "성부 설정"
#define TrackText1W 17 //Text: "파일:"
#define TrackText2W 17 //Text: "폴더:"
#define TrackText3W 27 //Text: "음표 수:"
#define TrackText4W 17 //Text: "길이:"
#define TrackText5W 48 //Text: "지연 대신 감속"
#define TrackText6W 87 //Text: "모든 음색을 피아노로 변경"
#define TrackText7W 15 //Text: "연주"
#define TrackText8W 15 //Text: "중단"
#define AboutWindowTitleW 15 //Text: "정보"
#define AboutText2W 15 //Text: "확인"
#define LoadWindowTitleW 54 //Text: L"불러들이는 중..."
#define LoadingTextW 46 //Text: "불러들이는 중"
#define LoadingStage1W 88 //Text: L"MIDI를 메모리에 복사 중..."
#define LoadingStage2W 49 //Text: L"압축 해제 중..."
#define LoadingStage3W 49 //Text: L"성부 분석 중..."
#define LoadingStage4W 49 //Text: L"음표 연결 중..."
#define LoadingStage5W 56 //Text: L"이벤트 정렬 중..."
#define LoadingStage6W 82 //Text: L"음표 수 조회표 준비 중..."
#define ResolutionWindowTitleW 39 //Text: "해상도 설정"
#define ResolutionText1W 17 //Text: "너비:"
#define ResolutionText2W 17 //Text: "높이:"
#define ResolutionText3W 15 //Text: "확인"
#define ResolutionText4W 15 //Text: "취소"
#define MenuText1W 15 //Text: "열기"
#define MenuText2W 15 //Text: "닫기"
#define MenuText3W 15 //Text: "연주"
#define MenuText4W 66 //Text: "연주/일시정지\tSpace"
#define MenuText5W 25 //Text: "정지\tEsc"
#define MenuText6W 46 //Text: "빨리감기\tRight"
#define MenuText7W 35 //Text: "되감기\tLeft"
#define MenuText8W 57 //Text: "빠르게\tCtrl+Down"
#define MenuText9W 47 //Text: "느리게\tCtrl+Up"
#define MenuText10W 60 //Text: "속도 초기화\tCtrl+R"
#define MenuText11W 67 //Text: "음표 빠르게\tShift+Up"
#define MenuText12W 77 //Text: "음표 느리게\tShift+Down"
#define MenuText13W 63 //Text: "음표 초기화\tShift+R"
#define MenuText14W 47 //Text: "음량 올리기\tUp"
#define MenuText15W 57 //Text: "음량 내리기\tDown"
#define MenuText16W 37 //Text: "무음\tCtrl+M"
#define MenuText17W 15 //Text: "보기"
#define MenuText18W 22 //Text: "조작판"
#define MenuText19W 31 //Text: "건반 표시"
#define MenuText20W 24 //Text: "항상 위"
#define MenuText21W 63 //Text: "전체 화면\tAlt+Enter"
#define MenuText22W 64 //Text: "창 크기 설정\tCtrl+W"
#define MenuText23W 32 //Text: "이동/확대"
#define MenuText24W 39 //Text: "위치 초기화"
#define MenuText25W 15 //Text: "설정"
#define MenuText26W 15 //Text: "정보"
#define MenuText27W 53 //Text: "특수효과 편집기"
#endif
#ifdef HRG
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 101 //Text: L"かいはつしゃ: happy_mimimix"
#define MainWindowTitle3W 61 //Text: L"さいせいちゅう: "
#define MainWindowTitle4W 77 //Text: L"レンダリングちゅう: "
#define MainWindowTitle5W 16 //Text: L"なし"
#define MainWindowTitle6W 63 //Text: L"スプラッシュMIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 145 //Text: L"  (ソフトウェアレンダリングきょうせい)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 81 //Text: L"Piano-FX Proへようこそ"
#define StartupStage1TextW 64 //Text: L"じゅんびちゅう..."
#define StartupStage2TextW 135 //Text: L"スプラッシュMIDIをよみこみちゅう..."
#define StartupStage3TextW 40 //Text: L"スタート！"
#define OpenFileTitleW 125 //Text: L"さいせいするファイルをせんたく: "
#define OpenSplashFileTitleW 148 //Text: L"スプラッシュがめんようMIDIをせんたく: "
#define OpenBackgroundFileTitleW 101 //Text: L"はいけいがぞうをせんたく: "
#define StatisticsText1W 80 //Text: "Piano-FX Pro (ひらがな)"
#define StatisticsText2W 101 //Text: "かいはつしゃ: happy_mimimix"
#define StatisticsText3W 27 //Text: "じかん:"
#define StatisticsText4W 35 //Text: "ティック:"
#define StatisticsText5W 59 //Text: "マイクロびょう:"
#define StatisticsText6W 59 //Text: "フレームレート:"
#define StatisticsText7W 59 //Text: "きょくのテンポ:"
#define StatisticsText8W 43 //Text: "コンボすう:"
#define StatisticsText9W 75 //Text: "クリックまいびょう:"
#define StatisticsText10W 59 //Text: "どうじおしすう:"
#define StatisticsText11W 43 //Text: "ノートすう:"
#define StatisticsText12W 75 //Text: "ノーツパーセカンド:"
#define StatisticsText13W 51 //Text: "ポリフォニー:"
#define StatisticsText14W 67 //Text: "レンダリングずみ:"
#define StatisticsText15W 43 //Text: "おんりょう:"
#define StatisticsText16W 56 //Text: "ミュートちゅう"
#define StatisticsText17W 59 //Text: "さいせいそくど:"
#define StatisticsText18W 51 //Text: "ノートそくど:"
#define StatisticsText19W 47 //Text: "Xオフセット:"
#define StatisticsText20W 47 //Text: "Yオフセット:"
#define StatisticsText21W 27 //Text: "ズーム:"
#define StatisticsText22W 67 //Text: "ウィンドウサイズ:"
#define StatisticsText23W 59 //Text: "けんばんはんい:"
#define StatisticsText24W 99 //Text: "おんぷのきょうどしきいち:"
#define StatisticsText25W 27 //Text: "スコア:"
#define StatisticsText26W 27 //Text: "レベル:"
#define StatisticsText27W 59 //Text: "じどうえんそう:"
#define StatisticsText28W 58 //Text: "ゆうこうかずみ "
#define StatisticsText29W 50 //Text: "フルコンボ!!! "
#define StatisticsText30W 114 //Text: "デモンストレーションちゅう... "
#define StatisticsText31W 82 //Text: "いちじていしちゅう... "
#define StatisticsText32W 113 //Text: "エラー: スコアオーバーフロー! "
#define ZoomMoveMsgW 1,153 //Text: "- ひだりクリックしてドラッグすると、がめんがいどうします\n- みぎクリックしたままドラッグするとすいへいほうこうにズームします\n- へんこうをてきようするには、もういちど 「ひょうじ->いどうとズーム 」をクリックします\n- へんこうをもとにもどすには、「ひょうじ->いどうとズームをリセット 」をクリックします"
#define PropertyWindowTitleW 32 //Text: L"せってい"
#define Property1TitleW 32 //Text: L"ひょうじ"
#define Property1Text1W 83 //Text: "ひょうじするけんばん:"
#define Property1Text2W 76 //Text: "ぜん128けんひょうじ"
#define Property1Text3W 64 //Text: "きょくにあわせる"
#define Property1Text4W 51 //Text: "はんいしてい:"
#define Property1Text5W 16 //Text: "から"
#define Property1Text6W 51 //Text: "トラックいろ:"
#define Property1Text7W 40 //Text: "ランダムか"
#define Property1Text8W 59 //Text: "はいけいしょく:"
#define Property1Text9W 35 //Text: "バーいろ:"
#define Property1Text10W 88 //Text: "デフォルトいろにもどす"
#define Property1Text11W 59 //Text: "はいけいがぞう:"
#define Property1Text12W 40 //Text: "さんしょう"
#define Property1Text13W 32 //Text: "リセット"
#define Property1Text14W 333 //Text: "ヒント: こうどなグラフィックせっていは「レンダリング」カテゴリをごかくにんください。"
#define Property2TitleW 40 //Text: L"オーディオ"
#define Property2Text1W 121 //Text: "ひょうじゅんWinMMしゅつりょく:"
#define Property2Text2W 279 //Text: "WinMMのかわりにこうりつてきなKDMAPIをしようする（OmniMIDIがひつよう）"
#define Property3TitleW 48 //Text: L"レンダリング"
#define Property3Text1W 115 //Text: "こうどなグラフィックせってい:"
#define Property3Text2W 104 //Text: "ティックベースレンダリング"
#define Property3Text3W 72 //Text: "ピッチベンドかしか"
#define Property3Text4W 56 //Text: "とうはばノート"
#define Property3Text5W 64 //Text: "マーカーひょうじ"
#define Property3Text6W 75 //Text: "マーカーもじコード:"
#define Property3Text7W 60 //Text: "FPSを60にこてい"
#define Property3Text8W 72 //Text: "どうがしゅつりょく"
#define Property3Text9W 104 //Text: "デバッグじょうほうひょうじ"
#define Property3Text10W 72 //Text: "とうけいひひょうじ"
#define Property3Text11W 152 //Text: "かさなりあったおんぷをひひょうじにする"
#define Property4TitleW 24 //Text: L"そうさ"
#define Property4Text1W 59 //Text: "そうさのどうさ:"
#define Property4Text2W 83 //Text: "さゆうキーでスキップ:"
#define Property4Text3W 24 //Text: "びょう"
#define Property4Text4W 115 //Text: "じょうげキーでそくどへんこう:"
#define Property4Text5W 7 //Text: "%"
#define Property4Text6W 192 //Text: "ぜんがめんひょうじじでもツールバーをひょうじする"
#define Property4Text7W 87 //Text: "Phigrosしきスコアリング"
#define Property4Text8W 66 //Text: "スプラッシュMIDI:"
#define Property4Text9W 99 //Text: "おんぷのきょうどしきいち:"
#define TrackWindowTitleW 64 //Text: "トラックせってい"
#define TrackText1W 35 //Text: "ファイル:"
#define TrackText2W 35 //Text: "フォルダ:"
#define TrackText3W 43 //Text: "ノートすう:"
#define TrackText4W 27 //Text: "ながさ:"
#define TrackText5W 88 //Text: "ラグのかわりにげんそく"
#define TrackText6W 112 //Text: "ぜんがっきをピアノにおきかえ"
#define TrackText7W 32 //Text: "さいせい"
#define TrackText8W 32 //Text: "ちゅうし"
#define AboutWindowTitleW 80 //Text: "バージョンじょうほう"
#define AboutText2W 16 //Text: "はい"
#define LoadWindowTitleW 64 //Text: L"よみこみちゅう..."
#define LoadingTextW 56 //Text: "よみこみちゅう"
#define LoadingStage1W 111 //Text: L"MIDIをメモリにコピーちゅう..."
#define LoadingStage2W 64 //Text: L"かいとうちゅう..."
#define LoadingStage3W 120 //Text: L"おんトラックをかいせきちゅう..."
#define LoadingStage4W 96 //Text: L"おんぷをれんけつちゅう..."
#define LoadingStage5W 96 //Text: L"イベントをせいりちゅう..."
#define LoadingStage6W 208 //Text: L"おんぷカウントのしょうごうテーブルをさくせいちゅう..."
#define ResolutionWindowTitleW 72 //Text: "かいぞうどせってい"
#define ResolutionText1W 27 //Text: "はばさ:"
#define ResolutionText2W 27 //Text: "たかさ:"
#define ResolutionText3W 32 //Text: "かくてい"
#define ResolutionText4W 32 //Text: "とりけし"
#define MenuText1W 24 //Text: "ひらく"
#define MenuText2W 24 //Text: "とじる"
#define MenuText3W 32 //Text: "さいせい"
#define MenuText4W 102 //Text: "さいせい/いちじていし\tSpace"
#define MenuText5W 35 //Text: "ていし\tEsc"
#define MenuText6W 57 //Text: "はやおくり\tRight"
#define MenuText7W 53 //Text: "まきもどし\tLeft"
#define MenuText8W 91 //Text: "さいせいかそく\tCtrl+Down"
#define MenuText9W 89 //Text: "さいせいげんそく\tCtrl+Up"
#define MenuText10W 77 //Text: "そくどリセット\tCtrl+R"
#define MenuText11W 77 //Text: "ノートかそく\tShift+Up"
#define MenuText12W 94 //Text: "ノートげんそく\tShift+Down"
#define MenuText13W 81 //Text: "ノートリセット\tShift+R"
#define MenuText14W 65 //Text: "おんりょうあげ\tUp"
#define MenuText15W 74 //Text: "おんりょうさげ\tDown"
#define MenuText16W 54 //Text: "ミュート\tCtrl+M"
#define MenuText17W 32 //Text: "ひょうじ"
#define MenuText18W 72 //Text: "コントロールパネル"
#define MenuText19W 64 //Text: "けんばんひょうじ"
#define MenuText20W 80 //Text: "さいぜんめんひょうじ"
#define MenuText21W 103 //Text: "ぜんがめんひょうじ\tAlt+Enter"
#define MenuText22W 119 //Text: "ウィンドウサイズせってい\tCtrl+W"
#define MenuText23W 56 //Text: "いどうとズーム"
#define MenuText24W 96 //Text: "いどうとズームをリセット"
#define MenuText25W 32 //Text: "せってい"
#define MenuText26W 80 //Text: "バージョンじょうほう"
#define MenuText27W 82 //Text: "Piano-FX Studioをひらく"
#endif
