#define AboutText1 L"Piano-FX Pro v4.2 | Forked from Piano From Above v1.1.0\n\nContributors list: \nHappy_mimimix(25 %) <-Funny special effects && Final optimization\nanon64(5 %) <-Color events support\nKhangaroo(30 %) <-Performance boost\nBrianPantano(40 %) <-Main program"
#ifdef ENG
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 97 //Text: L"Developed by: happy_mimimix"
#define MainWindowTitle3W 43 //Text: L"Now playing: "
#define MainWindowTitle4W 51 //Text: L"Now rendering: "
#define MainWindowTitle5W 17 //Text: L"None"
#define MainWindowTitle6W 38 //Text: L"Splash MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 104 //Text: L"  (Enforced Software Rendering)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 80 //Text: L"Welcome to Piano-FX Pro"
#define StartupStage1TextW 39 //Text: L"Preparing..."
#define StartupStage2TextW 69 //Text: L"Loading splash midi..."
#define StartupStage3TextW 27 //Text: L"Let's go!"
#define OpenFileTitleW 126 //Text: L"Please select the file you want to play: "
#define OpenSplashFileTitleW 155 //Text: L"Please select your desiered splash screen MIDI: "
#define OpenBackgroundFileTitleW 152 //Text: L"Please select your desiered background image: "
#define StatisticsText1W 41 //Text: "Piano-FX Pro"
#define StatisticsText2W 97 //Text: "Developed by: happy_mimimix"
#define StatisticsText3W 17 //Text: "Time:"
#define StatisticsText4W 15 //Text: "Tick:"
#define StatisticsText5W 45 //Text: "Microseconds:"
#define StatisticsText6W 15 //Text: "FPS:"
#define StatisticsText7W 24 //Text: "Tempo:"
#define StatisticsText8W 25 //Text: "Combo:"
#define StatisticsText9W 54 //Text: "ClicksPerSecond:"
#define StatisticsText10W 69 //Text: "SimultaneousPresses:"
#define StatisticsText11W 21 //Text: "Notes:"
#define StatisticsText12W 55 //Text: "NotesPerSecond:"
#define StatisticsText13W 36 //Text: "Polyphony:"
#define StatisticsText14W 34 //Text: "Rendered:"
#define StatisticsText15W 25 //Text: "Volume:"
#define StatisticsText16W 23 //Text: "MUTED"
#define StatisticsText17W 51 //Text: "PlaybackSpeed:"
#define StatisticsText18W 38 //Text: "NoteSpeed:"
#define StatisticsText19W 30 //Text: "Offset-X:"
#define StatisticsText20W 30 //Text: "Offset-Y:"
#define StatisticsText21W 20 //Text: "Zoom:"
#define StatisticsText22W 41 //Text: "WindowSize:"
#define StatisticsText23W 35 //Text: "KeyRange:"
#define StatisticsText24W 21 //Text: "Score:"
#define StatisticsText25W 19 //Text: "Level:"
#define StatisticsText26W 31 //Text: "AutoPlay:"
#define StatisticsText27W 12 //Text: "ON "
#define StatisticsText28W 52 //Text: "FULL COMBO!!! "
#define StatisticsText29W 98 //Text: "Deomonstration in progress... "
#define StatisticsText30W 53 //Text: "Game paused... "
#define StatisticsText31W 81 //Text: "ERROR: Score overflow! "
#define ZoomMoveMsgW 641 //Text: "- Left-click and drag to move the screen\n- Right-click and drag to zoom horizontally\n- Click 'View -> Move And Zoom' again to apply changes\n- Click 'View -> Reset Move And Zoom' to revert changes"
#define PropertyWindowTitleW 39 //Text: L"Preferences"
#define Property1TitleW 18 //Text: L"Visual"
#define Property1Text1W 51 //Text: L"Keys to display:"
#define Property1Text2W 57 //Text: L"Show all 128 keys"
#define Property1Text3W 51 //Text: L"Show song keys"
#define Property1Text4W 37 //Text: L"Show keys:"
#define Property1Text5W 25 //Text: L"through"
#define Property1Text6W 41 //Text: L"Track colors:"
#define Property1Text7W 35 //Text: L"Randomize"
#define Property1Text8W 57 //Text: L"Background color:"
#define Property1Text9W 31 //Text: L"Bar color:"
#define Property1Text10W 76 //Text: L"Restore Defaults Colors"
#define Property1Text11W 61 //Text: L"Background image:"
#define Property1Text12W 23 //Text: L"Browse"
#define Property1Text13W 19 //Text: L"Reset"
#define Property1Text14W 255 //Text: L"Hint: Visit the 'Render' category for more advanced graphics rendering options. "
#define Property2TitleW 18 //Text: L"Audio"
#define Property2Text1W 80 //Text: L"Standard WinMM output:"
#define Property2Text2W 213 //Text: L"Use more efficient KDMAPI instead of WinMM (Requires OmniMIDI)"
#define Property3TitleW 23 //Text: L"Render"
#define Property3Text1W 117 //Text: L"Advanced graphics randering config:"
#define Property3Text2W 67 //Text: L"Tick-based rendering"
#define Property3Text3W 65 //Text: L"Visualize pitch bends"
#define Property3Text4W 57 //Text: L"Same width notes"
#define Property3Text5W 45 //Text: L"Show markers"
#define Property3Text6W 71 //Text: L"Marker text encoding:"
#define Property3Text7W 47 //Text: L"Lock FPS to 60"
#define Property3Text8W 41 //Text: L"Video output"
#define Property3Text9W 77 //Text: L"Show debug information"
#define Property3Text10W 44 //Text: L"Hide statistics"
#define Property3Text11W 55 //Text: L"Remove overlaps"
#define Property4TitleW 23 //Text: L"Control"
#define Property4Text1W 61 //Text: L"Controls' behavior:"
#define Property4Text2W 124 //Text: L"Left and right arrows skip the song by:"
#define Property4Text3W 26 //Text: L"seconds"
#define Property4Text4W 140 //Text: L"Up and down arrows speed up the song by:"
#define Property4Text5W 25 //Text: L"percent"
#define Property4Text6W 148 //Text: L"Don't hide playback toolbar in full screen mode"
#define Property4Text7W 90 //Text: L"Phigros style scoring system"
#define Property4Text8W 41 //Text: L"Splash MIDI:"
#define Property4Text9W 59 //Text: L"Velocity threshold:"
#define TrackWindowTitleW 45 //Text: L"Track Settings"
#define TrackText1W 13 //Text: L"File:"
#define TrackText2W 23 //Text: L"Folder:"
#define TrackText3W 21 //Text: L"Notes:"
#define TrackText4W 25 //Text: L"Length:"
#define TrackText5W 79 //Text: L"Slow down instead of lag"
#define TrackText6W 102 //Text: L"Override instruments with piano"
#define TrackText7W 13 //Text: L"Play"
#define TrackText8W 18 //Text: L"Abort"
#define AboutWindowTitleW 19 //Text: L"About"
#define AboutText2W 9 //Text: L"OK"
#define LoadWindowTitleW 33 //Text: L"Loading..."
#define LoadingTextW 25 //Text: L"Loading"
#define LoadingStage1W 93 //Text: L"Copying MIDI into memory..."
#define LoadingStage2W 56 //Text: L"Decompressing..."
#define LoadingStage3W 53 //Text: L"Parsing tracks..."
#define LoadingStage4W 64 //Text: L"Connecting notes..."
#define LoadingStage5W 55 //Text: L"Sorting events..."
#define ResolutionWindowTitleW 46 //Text: L"Set Resolution"
#define ResolutionText1W 21 //Text: L"Width:"
#define ResolutionText2W 23 //Text: L"Height:"
#define ResolutionText3W 25 //Text: L"Confirm"
#define ResolutionText4W 21 //Text: L"Cancel"
#define MenuText1W 17 //Text: L"Open"
#define MenuText2W 17 //Text: L"Close"
#define MenuText3W 13 //Text: L"Play"
#define MenuText4W 62 //Text: L"Play/Pause\tSpace"
#define MenuText5W 33 //Text: L"Stop\tEsc"
#define MenuText6W 52 //Text: L"Skip Fwd\tRight"
#define MenuText7W 49 //Text: L"Skip Back\tLeft"
#define MenuText8W 93 //Text: L"Faster Playback\tCtrl+Down"
#define MenuText9W 84 //Text: L"Slower Playback\tCtrl+Up"
#define MenuText10W 77 //Text: L"Reset Playback\tCtrl+R"
#define MenuText11W 77 //Text: L"Faster Notes\tShift+Up"
#define MenuText12W 87 //Text: L"Slower Notes\tShift+Down"
#define MenuText13W 71 //Text: L"Reset Notes\tShift+R"
#define MenuText14W 49 //Text: L"Volume Up\tUp"
#define MenuText15W 68 //Text: L"Volume Down\tDown"
#define MenuText16W 45 //Text: L"Mute\tCtrl+M"
#define MenuText17W 15 //Text: L"View"
#define MenuText18W 54 //Text: L"Playback Toolbar"
#define MenuText19W 31 //Text: L"Keyboard"
#define MenuText20W 48 //Text: L"Always On Top"
#define MenuText21W 73 //Text: L"Full Screen\tAlt+Enter"
#define MenuText22W 83 //Text: L"Set Window Size\tCtrl+W"
#define MenuText23W 51 //Text: L"Move And Zoom"
#define MenuText24W 72 //Text: L"Reset Move And Zoom"
#define MenuText25W 39 //Text: L"Preferences"
#define MenuText26W 19 //Text: L"About"
#define MenuText27W 69 //Text: L"Open Piano-FX Studio"
#endif
#ifdef CHN
#define MainWindowTitle1W 55 //Text: L"专业の钢琴特效"
#define MainWindowTitle2W 76 //Text: L"开发者：happy_mimimix"
#define MainWindowTitle3W 36 //Text: L"正在播放："
#define MainWindowTitle4W 36 //Text: L"正在渲染："
#define MainWindowTitle5W 8 //Text: L"无"
#define MainWindowTitle6W 31 //Text: L"欢迎MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 57 //Text: L"  (强制软件渲染)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 89 //Text: L"欢迎使用 专业の钢琴特效"
#define StartupStage1TextW 36 //Text: L"准备中……"
#define StartupStage2TextW 59 //Text: L"加载欢迎MIDI……"
#define StartupStage3TextW 56 //Text: L"让我们开始吧！"
#define OpenFileTitleW 93 //Text: L"请选择您想要播放的文件: "
#define OpenSplashFileTitleW 125 //Text: L"请选择您希望作为欢迎画面的文件: "
#define OpenBackgroundFileTitleW 125 //Text: L"请选择您希望作为背景图像的文件: "
#define StatisticsText1W 86 //Text: "专业の钢琴特效 (中文版)"
#define StatisticsText2W 77 //Text: "开发者: happy_mimimix"
#define StatisticsText3W 19 //Text: "时长:"
#define StatisticsText4W 11 //Text: "刻:"
#define StatisticsText5W 19 //Text: "微秒:"
#define StatisticsText6W 19 //Text: "帧率:"
#define StatisticsText7W 35 //Text: "歌曲速率:"
#define StatisticsText8W 19 //Text: "连击:"
#define StatisticsText9W 35 //Text: "每秒手速:"
#define StatisticsText10W 35 //Text: "手指个数:"
#define StatisticsText11W 27 //Text: "音符数:"
#define StatisticsText12W 35 //Text: "每秒演奏:"
#define StatisticsText13W 35 //Text: "同时演奏:"
#define StatisticsText14W 27 //Text: "已渲染:"
#define StatisticsText15W 19 //Text: "音量:"
#define StatisticsText16W 16 //Text: "静音"
#define StatisticsText17W 35 //Text: "播放速度:"
#define StatisticsText18W 35 //Text: "音符速度:"
#define StatisticsText19W 23 //Text: "X偏移:"
#define StatisticsText20W 23 //Text: "Y偏移:"
#define StatisticsText21W 19 //Text: "缩放:"
#define StatisticsText22W 35 //Text: "窗口大小:"
#define StatisticsText23W 35 //Text: "琴键范围:"
#define StatisticsText24W 19 //Text: "分数:"
#define StatisticsText25W 19 //Text: "难度:"
#define StatisticsText26W 35 //Text: "自动播放:"
#define StatisticsText27W 18 //Text: "开启 "
#define StatisticsText28W 42 //Text: "恭喜全连!!! "
#define StatisticsText29W 66 //Text: "奥托普雷演示中... "
#define StatisticsText30W 42 //Text: "游戏暂停... "
#define StatisticsText31W 57 //Text: "错误: 分数溢出! "
#define ZoomMoveMsgW 493 //Text: "- 左键单击并拖动可移动屏幕\n- 右键单击并拖动可水平缩放\n- 再次点击“查看->移动和缩放”可应用更改\n- 点击“查看->重置移动和缩放”可撤销更改"
#define PropertyWindowTitleW 16 //Text: L"属性"
#define Property1TitleW 16 //Text: L"视觉"
#define Property1Text1W 35 //Text: L"琴键显示:"
#define Property1Text2W 36 //Text: L"全部128键"
#define Property1Text3W 24 //Text: L"自适应"
#define Property1Text4W 35 //Text: L"指定范围:"
#define Property1Text5W 8 //Text: L"至"
#define Property1Text6W 35 //Text: L"音轨颜色:"
#define Property1Text7W 16 //Text: L"随机"
#define Property1Text8W 35 //Text: L"背景颜色:"
#define Property1Text9W 35 //Text: L"横条颜色:"
#define Property1Text10W 48 //Text: L"重置默认颜色"
#define Property1Text11W 35 //Text: L"背景图片:"
#define Property1Text12W 16 //Text: L"浏览"
#define Property1Text13W 16 //Text: L"重置"
#define Property1Text14W 175 //Text: L"提示：前往“渲染”类别查看更多高级图形渲染选项。"
#define Property2TitleW 16 //Text: L"音频"
#define Property2Text1W 57 //Text: L"标准WinMM输出:"
#define Property2Text2W 169 //Text: L"使用更高效的KDMAPI代替WinMM (需要 OmniMIDI)"
#define Property3TitleW 16 //Text: L"渲染"
#define Property3Text1W 67 //Text: L"高级图形渲染选项:"
#define Property3Text2W 40 //Text: L"基于刻渲染"
#define Property3Text3W 40 //Text: L"可视化弯音"
#define Property3Text4W 32 //Text: L"等宽音符"
#define Property3Text5W 32 //Text: L"显示标记"
#define Property3Text6W 51 //Text: L"文本编码格式:"
#define Property3Text7W 48 //Text: L"锁定帧率至60"
#define Property3Text8W 32 //Text: L"导出视频"
#define Property3Text9W 48 //Text: L"显示调试信息"
#define Property3Text10W 48 //Text: L"隐藏统计数据"
#define Property4TitleW 16 //Text: L"控制"
#define Property4Text1W 35 //Text: L"按键行为:"
#define Property4Text2W 51 //Text: L"左右箭头跳过:"
#define Property4Text3W 8 //Text: L"秒"
#define Property4Text4W 51 //Text: L"上下箭头加速:"
#define Property4Text5W 7 //Text: L"%"
#define Property4Text6W 88 //Text: L"全屏模式下不隐藏工具条"
#define Property4Text7W 63 //Text: L"仿Phigros计分系统"
#define Property4Text8W 34 //Text: L"欢迎MIDI:"
#define TrackWindowTitleW 32 //Text: L"音轨设置"
#define TrackText1W 27 //Text: L"文件名:"
#define TrackText2W 19 //Text: L"路径:"
#define TrackText3W 27 //Text: L"音符数:"
#define TrackText4W 19 //Text: L"时长:"
#define TrackText5W 56 //Text: L"减速而不是卡顿"
#define TrackText6W 80 //Text: L"将所有乐器替换为钢琴"
#define TrackText7W 16 //Text: L"播放"
#define TrackText8W 16 //Text: L"终止"
#define AboutWindowTitleW 16 //Text: L"关于"
#define AboutText2W 8 //Text: L"好"
#define LoadWindowTitleW 32 //Text: L"加载中..."
#define LoadingTextW 32 //Text: L"正在读取"
#define LoadingStage1W 88 //Text: L"正在将文件复制到内存..."
#define LoadingStage2W 48 //Text: L"正在解压缩..."
#define LoadingStage3W 56 //Text: L"正在解析音轨..."
#define LoadingStage4W 56 //Text: L"正在连接音符..."
#define LoadingStage5W 56 //Text: L"正在整理事件..."
#define ResolutionWindowTitleW 40 //Text: L"设置分辨率"
#define ResolutionText1W 19 //Text: L"宽度:"
#define ResolutionText2W 19 //Text: L"高度:"
#define ResolutionText3W 16 //Text: L"确认"
#define ResolutionText4W 16 //Text: L"取消"
#define MenuText1W 16 //Text: L"打开"
#define MenuText2W 16 //Text: L"关闭"
#define MenuText3W 16 //Text: L"演奏"
#define MenuText4W 54 //Text: L"播放/暂停\tSpace"
#define MenuText5W 27 //Text: L"停止\tEsc"
#define MenuText6W 33 //Text: L"快进\tRight"
#define MenuText7W 29 //Text: L"快退\tLeft"
#define MenuText8W 67 //Text: L"播放加速\tCtrl+Down"
#define MenuText9W 57 //Text: L"播放减速\tCtrl+Up"
#define MenuText10W 53 //Text: L"播放重置\tCtrl+R"
#define MenuText11W 61 //Text: L"音符加速\tShift+Up"
#define MenuText12W 70 //Text: L"音符减速\tShift+Down"
#define MenuText13W 57 //Text: L"音符重置\tShift+R"
#define MenuText14W 33 //Text: L"音量加\tUp"
#define MenuText15W 42 //Text: L"音量减\tDown"
#define MenuText16W 38 //Text: L"静音\tCtrl+M"
#define MenuText17W 16 //Text: L"查看"
#define MenuText18W 24 //Text: L"工具条"
#define MenuText19W 16 //Text: L"键盘"
#define MenuText20W 16 //Text: L"置顶"
#define MenuText21W 47 //Text: L"全屏\tAlt+Enter"
#define MenuText22W 71 //Text: L"设置窗口大小\tCtrl+W"
#define MenuText23W 40 //Text: L"移动和缩放"
#define MenuText24W 56 //Text: L"重置移动和缩放"
#define MenuText25W 16 //Text: L"设置"
#define MenuText26W 16 //Text: L"关于"
#define MenuText27W 56 //Text: L"钢琴特效编辑器"
#endif
#ifdef ARN
#define MainWindowTitle1W 135 //Text: L"ZHUAN1 YE4 DE5 GANG1 QIN2 TE4 XIAO4"
#define MainWindowTitle2W 101 //Text: L"KAI1 FA1 ZHE3: happy_mimimix"
#define MainWindowTitle3W 87 //Text: L"ZHENG4 ZAI4 BO1 FANG4: "
#define MainWindowTitle4W 92 //Text: L"ZHENG4 ZAI4 XUAN4 RAN3: "
#define MainWindowTitle5W 45 //Text: L"KONG4 XIAN2"
#define MainWindowTitle6W 67 //Text: L"HUAN1 YING2 MIDI+"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 143 //Text: L"  (QIANG2 ZHI4 RUAN3 JIAN4 XUAN4 RAN3)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 224 //Text: L"HUAN1 YING2 SHI3 YONG4 ZHUAN1 YE4 DE5 GANG1 QIN2 TE4 XIAO4"
#define StartupStage1TextW 76 //Text: L"ZHUN3 BEI4 ZHONG1..."
#define StartupStage2TextW 100 //Text: L"ZAI3 RU4 HUAN1 YING2 MIDI+"
#define StartupStage3TextW 37 //Text: L"CHU1 FA1! "
#define OpenFileTitleW 227 //Text: L"QING3 XUAN3 QU3 NIN2 XIANG3 YAO4 BO1 FANG4 DE5 WEN2 JIAN4: "
#define OpenSplashFileTitleW 310 //Text: L"QING3 XUAN3 QU3 NIN2 XI1 WANG4 YONG4 ZUO4 HUAN1 YING2 PING2 MU4 DE5 WEN2 JIAN4: "
#define OpenBackgroundFileTitleW 305 //Text: L"QING3 XUAN3 QU3 NIN2 XI1 WANG4 YONG4 ZUO4 BEI4 JING3 TU2 XIANG4 DE5 WEN2 JIAN4: "
#define StatisticsText1W 79 //Text: "Piano-FX Pro (Arinoglish)"
#define StatisticsText2W 101 //Text: "KAI1 FA1 ZHE3: happy_mimimix"
#define StatisticsText3W 47 //Text: "SHI2 CHANG2:"
#define StatisticsText4W 15 //Text: "KE4:"
#define StatisticsText5W 44 //Text: "WEI1 MIAO3:"
#define StatisticsText6W 37 //Text: "ZHEN1 LV4:"
#define StatisticsText7W 61 //Text: "YIN1 YU4 SU4 LV4:"
#define StatisticsText8W 34 //Text: "LIAN2 JI1:"
#define StatisticsText9W 82 //Text: "MEI3 MIAO3 SHOU3 SU4:"
#define StatisticsText10W 77 //Text: "SHOU3 ZHI3 GE4 SHU4:"
#define StatisticsText11W 52 //Text: "YIN1 FU2 SHU4:"
#define StatisticsText12W 82 //Text: "MEI3 MIAO3 YAN3 ZOU4:"
#define StatisticsText13W 82 //Text: "TONG2 SHI2 YAN3 ZOU4:"
#define StatisticsText14W 57 //Text: "YI3 XUAN4 RAN3:"
#define StatisticsText15W 44 //Text: "YIN1 LIANG4:"
#define StatisticsText16W 37 //Text: "JING4 YIN1"
#define StatisticsText17W 70 //Text: "BO1 FANG4 SU4 DU5:"
#define StatisticsText18W 63 //Text: "YIN1 FU2 SU4 DU5:"
#define StatisticsText19W 41 //Text: "X PIAN1 YI2:"
#define StatisticsText20W 41 //Text: "Y PIAN1 YI2:"
#define StatisticsText21W 45 //Text: "SUO1 FANG4:"
#define StatisticsText22W 93 //Text: "CHUANG1 KOU3 DA4 XIAO3:"
#define StatisticsText23W 79 //Text: "QIN2 JIAN4 FAN4 WEI2:"
#define StatisticsText24W 39 //Text: "FEN1 SHU4:"
#define StatisticsText25W 68 //Text: "QU3 MU4 NAN2 DU4:"
#define StatisticsText26W 78 //Text: "ZI4 DONG4 YAN3 ZOU4:"
#define StatisticsText27W 31 //Text: "KAI1 QI3 "
#define StatisticsText28W 88 //Text: "GON1 XI3 QUAN2 LIAN2!!! "
#define StatisticsText29W 112 //Text: "ZI4 DONG4 YAN3 SHI4 ZHONG1... "
#define StatisticsText30W 82 //Text: "YOU2 XI4 ZAN4 TING2... "
#define StatisticsText31W 114 //Text: "CUO4 WU4: FEN1 SHU4 YI4 CHU1! "
#define ZoomMoveMsgW 1,151 //Text: "- ZUO3 JIAN4 DAN1 JI1 BING4 TUO1 DONG4 KE3 YI2 DONG4 PING2 MU4\n- YOU4 JIAN4 DAN1 JI1 BING4 TUO1 DONG1 KE3 SHUI3 PING2 SUO1 FANG4\n- ZAI4 CI4 DIAN3 JI1 'CHA2 KAN4 -> YI2 DONG4 HE2 SUO1 FANG4' KE3 YING4 YONG4 GENG1 GAI3\n- DIAN3 JI1 'CHA2 KAN4 -> CHONG2 ZHI4 YI2 DONG4 HE2 SUO1 FANG4' KE3 CHE4 XIAO1 GENG1 GAI3"
#define PropertyWindowTitleW 34 //Text: L"SHE4 ZHI4"
#define Property1TitleW 33 //Text: L"SHI4 JUE2"
#define Property1Text1W 80 //Text: L"QIN2 JIAN4 XIAN3 SHI4:"
#define Property1Text2W 73 //Text: L"QUAN2 BU4 128 JIAN4"
#define Property1Text3W 106 //Text: L"GEN1 JU4 MIDI+ ZI4 SHI4 YING4"
#define Property1Text4W 79 //Text: L"ZHI3 DING4 FAN4 WEI2:"
#define Property1Text5W 36 //Text: L"ZHI2 DAO4"
#define Property1Text6W 69 //Text: L"YIN1 GUI3 YAN2 SE4:"
#define Property1Text7W 27 //Text: L"SUI2 JI1"
#define Property1Text8W 72 //Text: L"BEI4 JING3 YAN2 SE4:"
#define Property1Text9W 81 //Text: L"HENG2 TIAO2 YAN2 SE4:"
#define Property1Text10W 79 //Text: L"CHONG2 ZHI4 YAN2 SE4"
#define Property1Text11W 75 //Text: L"BEI4 JING3 TU2 PIAN4:"
#define Property1Text12W 33 //Text: L"LIU2 LAN3"
#define Property1Text13W 45 //Text: L"CHONG2 ZHI4"
#define Property1Text14W 327 //Text: L"QIAN2 WANG3 'XUAN4 RAN3' LEI4 BIE2 CHA2 KAN4 GENG4 DUO1 GAO1 JI2 XUAN4 RAN3 SHE4 ZHI4."
#define Property2TitleW 33 //Text: L"YIN1 PIN2"
#define Property2Text1W 119 //Text: L"BIAO1 ZHUN3 WINMM+ SHU1 CHU1:"
#define Property2Text2W 218 //Text: L"SHI3 YONG4 KDMAPI+ DAI4 TI4 WINMM+ (XU1 YAO4 OMNI MIDI+)"
#define Property3TitleW 42 //Text: L"XUAN4 RAN3"
#define Property3Text1W 148 //Text: L"GAO1 JI2 TU2 XING2 XUAN4 RAN3 PEI4 ZHI4:"
#define Property3Text2W 83 //Text: L"JI1 YU2 KE4 XUAN4 RAN3"
#define Property3Text3W 89 //Text: L"KE3 SHI4 HUA4 WAN1 YIN1"
#define Property3Text4W 78 //Text: L"DENG3 KUAN1 YIN1 FU2"
#define Property3Text5W 72 //Text: L"XIAN3 SHI4 BIAO1 JI4"
#define Property3Text6W 111 //Text: L"WEN2 BEN3 BIAN1 MA3 GE2 SHI4:"
#define Property3Text7W 128 //Text: L"SUO3 DING4 ZHEN1 LV4 ZHI4 60 ZHEN1"
#define Property3Text8W 73 //Text: L"DAO3 CHU1 SHI4 PIN2"
#define Property3Text9W 107 //Text: L"XIAN3 SHI4 TIAO2 SHI4 XIN4 XI1"
#define Property3Text10W 107 //Text: L"YIN3 CANG2 TONG3 JI4 XIN4 XI1"
#define Property4TitleW 40 //Text: L"KONG4 ZHI4"
#define Property4Text1W 120 //Text: L"KONG4 ZHI4 XING2 WEI2 SHE4 ZHI4:"
#define Property4Text2W 125 //Text: L"ZUO3 YOU4 JIAN4 TOU2 TIAO4 GUO4:"
#define Property4Text3W 22 //Text: L"MIAO3"
#define Property4Text4W 119 //Text: L"SHANG4 XIA4 JIAN4 TOU2 JIA1 SU4:"
#define Property4Text5W 51 //Text: L"FEN1 ZHI1 BAI3"
#define Property4Text6W 215 //Text: L"QUAN2 PING2 MO2 SHI4 XIA4 BU4 YIN3 CANG2 GONG1 JU4 TIAO2"
#define Property4Text7W 141 //Text: L"PHIGROS+ FENG1 GE2 JI4 FEN1 XI4 TONG3"
#define Property4Text8W 70 //Text: L"HUAN1 YING2 MIDI+:"
#define TrackWindowTitleW 69 //Text: L"YIN1 GUI3 SHE4 ZHI4"
#define TrackText1W 43 //Text: L"WEN3 JIAN4:"
#define TrackText2W 36 //Text: L"LU4 JING4:"
#define TrackText3W 52 //Text: L"YIN1 FU2 SHU4:"
#define TrackText4W 47 //Text: L"SHI1 CHANG2:"
#define TrackText5W 115 //Text: L"JIAN3 SU4 ER2 BU2 SHI4 KA3 DUN4"
#define TrackText6W 206 //Text: L"JIANG1 SUO3 YOU3 YUE4 QI4 TI4 HUAN4 CHENG2 GANG1 QIN2"
#define TrackText7W 37 //Text: L"BO1 FANG4"
#define TrackText8W 45 //Text: L"ZHONG1 ZHI3"
#define AboutWindowTitleW 37 //Text: L"GUAN1 YU2"
#define AboutText2W 33 //Text: L"HAO3 DE5"
#define LoadWindowTitleW 69 //Text: L"JIA1 ZAI3 ZHONG1..."
#define LoadingTextW 75 //Text: L"ZHENG4 ZAI4 DU2 QU3"
#define LoadingStage1W 210 //Text: L"ZHENG4 ZAI4 JIANG1 WEN2 JIAN4 FU4 ZHI4 DAO4 NEI4 CUN2..."
#define LoadingStage2W 102 //Text: L"ZHENG4 ZAI4 JIE3 YA1 SUO1..."
#define LoadingStage3W 115 //Text: L"ZHENG4 ZAI4 JIE3 XI1 YIN1 GUI3..."
#define LoadingStage4W 117 //Text: L"ZHENG4 ZAI4 LIAN2 JI1 YIN1 FU2..."
#define LoadingStage5W 130 //Text: L"ZHENG4 ZAI4 ZHENG3 LI3 SHI1 JIAN4..."
#define ResolutionWindowTitleW 88 //Text: L"SHE4 ZHI4 FEN1 BIAN4 LV4"
#define ResolutionText1W 25 //Text: L"KUAN1:"
#define ResolutionText2W 21 //Text: L"GAO1:"
#define ResolutionText3W 37 //Text: L"QUE4 REN4"
#define ResolutionText4W 37 //Text: L"QU3 XIAO1"
#define MenuText1W 31 //Text: L"DA3 KAI1"
#define MenuText2W 35 //Text: L"GUAN1 BI4"
#define MenuText3W 37 //Text: L"YAN3 ZOU4"
#define MenuText4W 106 //Text: L"BO1 FANG4/ZAN4 TING2\tSpace"
#define MenuText5W 55 //Text: L"TING2 ZHI3\tEsc"
#define MenuText6W 61 //Text: L"KAUI4 JIN4\tRight"
#define MenuText7W 57 //Text: L"KUAI4 TUI4\tLeft"
#define MenuText8W 111 //Text: L"BO1 FANG4 JIA1 SU4\tCtrl+Down"
#define MenuText9W 106 //Text: L"BO1 FANG4 JIAN3 SU4\tCtrl+Up"
#define MenuText10W 113 //Text: L"BO1 FANG4 CHONG2 ZHI4\tCtrl+R"
#define MenuText11W 97 //Text: L"YIN1 FU2 JIA1 SU4\tShift+Up"
#define MenuText12W 111 //Text: L"YIN1 FU2 JIAN3 SU4\tShift+Down"
#define MenuText13W 109 //Text: L"CHONG2 ZHI4 YIN1 FU2\tShift+R"
#define MenuText14W 74 //Text: L"YIN1 LIANG4 JIA1\tUp"
#define MenuText15W 88 //Text: L"YIN1 LIANG4 JIAN3\tDown"
#define MenuText16W 66 //Text: L"JING4 YIN1\tCtrl+M"
#define MenuText17W 37 //Text: L"CHA2 KAN4"
#define MenuText18W 60 //Text: L"GONG1 JU4 TIAO2"
#define MenuText19W 39 //Text: L"JIAN4 PAN2"
#define MenuText20W 92 //Text: L"CHUANG1 KOU3 ZHI4 DING3"
#define MenuText21W 123 //Text: L"QUAN2 PING2 XIAN3 SHI4\tAlt+Enter"
#define MenuText22W 157 //Text: L"SHE4 ZHI4 CHUANG1 KOU3 DA4 XIAO3\tCtrl+W"
#define MenuText23W 95 //Text: L"YI2 DONG4 HE2 SUO1 FANG4"
#define MenuText24W 142 //Text: L"CHONG2 ZHI4 YI2 DONG4 HE2 SUO1 FANG4"
#define MenuText25W 34 //Text: L"SHE4 ZHI4"
#define MenuText26W 37 //Text: L"GUAN1 YU2"
#define MenuText27W 126 //Text: L"GANG1 QIN2 TE4 XIAO4 BIAN1 JI1 QI4"
#endif
#ifdef JPN
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 77 //Text: L"開発者: happy_mimimix"
#define MainWindowTitle3W 29 //Text: L"再生中: "
#define MainWindowTitle4W 47 //Text: L"レンダリング中: "
#define MainWindowTitle5W 13 //Text: L"なし"
#define MainWindowTitle6W 49 //Text: L"スプラッシュMIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 93 //Text: L"  (ソフトウェアレンダリング強制)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 69 //Text: L"Piano-FX Proへようこそ"
#define StartupStage1TextW 32 //Text: L"準備中..."
#define StartupStage2TextW 102 //Text: L"スプラッシュMIDIを読み込み中..."
#define StartupStage3TextW 31 //Text: L"スタート！"
#define OpenFileTitleW 78 //Text: L"再生するファイルを選択: "
#define OpenSplashFileTitleW 100 //Text: L"スプラッシュ画面用MIDIを選択: "
#define OpenBackgroundFileTitleW 59 //Text: L"背景画像を選択: "
#define StatisticsText1W 72 //Text: "Piano-FX Pro (日本語)"
#define StatisticsText2W 77 //Text: "開発者: happy_mimimix"
#define StatisticsText3W 19 //Text: "時間:"
#define StatisticsText4W 23 //Text: "ティック:"
#define StatisticsText5W 34 //Text: "マイクロ秒:"
#define StatisticsText6W 45 //Text: "フレームレート:"
#define StatisticsText7W 36 //Text: "曲のテンポ:"
#define StatisticsText8W 29 //Text: "コンボ数:"
#define StatisticsText9W 62 //Text: "秒間ハンドスピード:"
#define StatisticsText10W 41 //Text: "同時押し数:"
#define StatisticsText11W 28 //Text: "ノート数:"
#define StatisticsText12W 59 //Text: "ノーツパーセカンド:"
#define StatisticsText13W 37 //Text: "ポリフォニー:"
#define StatisticsText14W 45 //Text: "レンダリング済:"
#define StatisticsText15W 19 //Text: "音量:"
#define StatisticsText16W 30 //Text: "ミュート中"
#define StatisticsText17W 35 //Text: "再生速度:"
#define StatisticsText18W 36 //Text: "ノート速度:"
#define StatisticsText19W 35 //Text: "Xオフセット:"
#define StatisticsText20W 35 //Text: "Yオフセット:"
#define StatisticsText21W 23 //Text: "ズーム:"
#define StatisticsText22W 51 //Text: "ウィンドウサイズ:"
#define StatisticsText23W 35 //Text: "鍵盤範囲:"
#define StatisticsText24W 20 //Text: "スコア:"
#define StatisticsText25W 22 //Text: "レベル:"
#define StatisticsText26W 35 //Text: "自動演奏:"
#define StatisticsText27W 12 //Text: "ON "
#define StatisticsText28W 40 //Text: "フルコンボ!!! "
#define StatisticsText29W 77 //Text: "デモンストレーション中... "
#define StatisticsText30W 50 //Text: "一時停止中... "
#define StatisticsText31W 89 //Text: "エラー: スコアオーバーフロー! "
#define ZoomMoveMsgW 763 //Text: "- 左クリックしてドラッグすると、画面が移動します\n- 右クリックしたままドラッグすると水平方向にズームします\n- 変更を適用するには、もう一度 「表示->移動とズーム 」をクリックします\n- 変更を元に戻すには、「表示->移動とズームをリセット 」をクリックします"
#define PropertyWindowTitleW 16 //Text: L"設定"
#define Property1TitleW 16 //Text: L"表示"
#define Property1Text1W 47 //Text: L"表示する鍵盤:"
#define Property1Text2W 44 //Text: L"全128鍵表示"
#define Property1Text3W 41 //Text: L"曲に合わせる"
#define Property1Text4W 35 //Text: L"範囲指定:"
#define Property1Text5W 12 //Text: L"から"
#define Property1Text6W 31 //Text: L"トラック色:"
#define Property1Text7W 32 //Text: L"ランダム化"
#define Property1Text8W 27 //Text: L"背景色:"
#define Property1Text9W 24 //Text: L"バー色:"
#define Property1Text10W 58 //Text: L"デフォルト色に戻す"
#define Property1Text11W 35 //Text: L"背景画像:"
#define Property1Text12W 16 //Text: L"参照"
#define Property1Text13W 21 //Text: L"リセット"
#define Property1Text14W 219 //Text: L"ヒント: 高度なグラフィック設定は「レンダリング」カテゴリをご確認ください。"
#define Property2TitleW 30 //Text: L"オーディオ"
#define Property2Text1W 57 //Text: L"標準WinMM出力:"
#define Property2Text2W 102 //Text: L"KDMAPIを使用 (OmniMIDI必要)"
#define Property3TitleW 35 //Text: L"レンダリング"
#define Property3Text1W 73 //Text: L"高度なグラフィック設定:"
#define Property3Text2W 75 //Text: L"ティックベースレンダリング"
#define Property3Text3W 59 //Text: L"ピッチベンド可視化"
#define Property3Text4W 33 //Text: L"等幅ノート"
#define Property3Text5W 41 //Text: L"マーカー表示"
#define Property3Text6W 62 //Text: L"マーカー文字コード:"
#define Property3Text7W 48 //Text: L"FPSを60に固定"
#define Property3Text8W 32 //Text: L"動画出力"
#define Property3Text9W 56 //Text: L"デバッグ情報表示"
#define Property3Text10W 40 //Text: L"統計非表示"
#define Property4TitleW 16 //Text: L"操作"
#define Property4Text1W 41 //Text: L"操作の動作:"
#define Property4Text2W 62 //Text: L"左右キーでスキップ:"
#define Property4Text3W 8 //Text: L"秒"
#define Property4Text4W 71 //Text: L"上下キーで速度変更:"
#define Property4Text5W 7 //Text: L"%"
#define Property4Text6W 108 //Text: L"フルスクリーンでもツールバーを表示"
#define Property4Text7W 65 //Text: L"Phigros式スコアリング"
#define Property4Text8W 52 //Text: L"スプラッシュMIDI:"
#define TrackWindowTitleW 37 //Text: L"トラック設定"
#define TrackText1W 25 //Text: L"ファイル:"
#define TrackText2W 26 //Text: L"フォルダ:"
#define TrackText3W 28 //Text: L"ノート数:"
#define TrackText4W 16 //Text: L"長さ:"
#define TrackText5W 60 //Text: L"ラグの代わりに減速"
#define TrackText6W 69 //Text: L"全楽器をピアノに置換"
#define TrackText7W 16 //Text: L"再生"
#define TrackText8W 16 //Text: L"中止"
#define AboutWindowTitleW 46 //Text: L"バージョン情報"
#define AboutText2W 9 //Text: L"OK"
#define LoadWindowTitleW 47 //Text: L"読み込み中..."
#define LoadingTextW 39 //Text: L"読み込み中"
#define LoadingStage1W 69 //Text: L"MIDIをメモリにコピー..."
#define LoadingStage2W 32 //Text: L"展開中..."
#define LoadingStage3W 45 //Text: L"トラック解析..."
#define LoadingStage4W 41 //Text: L"ノート接続..."
#define LoadingStage5W 48 //Text: L"イベント整理..."
#define ResolutionWindowTitleW 40 //Text: L"解像度設定"
#define ResolutionText1W 11 //Text: L"幅:"
#define ResolutionText2W 16 //Text: L"高さ:"
#define ResolutionText3W 16 //Text: L"確定"
#define ResolutionText4W 16 //Text: L"取消"
#define MenuText1W 12 //Text: L"開く"
#define MenuText2W 20 //Text: L"閉じる"
#define MenuText3W 16 //Text: L"再生"
#define MenuText4W 70 //Text: L"再生/一時停止\tSpace"
#define MenuText5W 27 //Text: L"停止\tEsc"
#define MenuText6W 38 //Text: L"早送り\tRight"
#define MenuText7W 41 //Text: L"巻き戻し\tLeft"
#define MenuText8W 67 //Text: L"再生加速\tCtrl+Down"
#define MenuText9W 57 //Text: L"再生減速\tCtrl+Up"
#define MenuText10W 59 //Text: L"速度リセット\tCtrl+R"
#define MenuText11W 62 //Text: L"ノート加速\tShift+Up"
#define MenuText12W 71 //Text: L"ノート減速\tShift+Down"
#define MenuText13W 63 //Text: L"ノートリセット\tShift+R"
#define MenuText14W 39 //Text: L"音量上げ\tUp"
#define MenuText15W 49 //Text: L"音量下げ\tDown"
#define MenuText16W 44 //Text: L"ミュート\tCtrl+M"
#define MenuText17W 16 //Text: L"表示"
#define MenuText18W 56 //Text: L"コントロールパネル"
#define MenuText19W 32 //Text: L"鍵盤表示"
#define MenuText20W 40 //Text: L"最前面表示"
#define MenuText21W 71 //Text: L"全画面表示\tAlt+Enter"
#define MenuText22W 87 //Text: L"ウィンドウサイズ設定\tCtrl+W"
#define MenuText23W 41 //Text: L"移動とズーム"
#define MenuText24W 69 //Text: L"移動とズームをリセット"
#define MenuText25W 16 //Text: L"設定"
#define MenuText26W 46 //Text: L"バージョン情報"
#define MenuText27W 68 //Text: L"Piano-FX Studioを開く"
#endif
#ifdef KOR
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 75 //Text: L"개발자: happy_mimimix"
#define MainWindowTitle3W 36 //Text: L"현재 재생: "
#define MainWindowTitle4W 36 //Text: L"렌더링 중: "
#define MainWindowTitle5W 15 //Text: L"없음"
#define MainWindowTitle6W 32 //Text: L"시작 MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 87 //Text: L"  (소프트웨어 렌더링 강제)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 120 //Text: L"Piano-FX Pro에 오신 것을 환영합니다"
#define StartupStage1TextW 32 //Text: L"준비 중..."
#define StartupStage2TextW 81 //Text: L"시작 MIDI 불러오는 중..."
#define StartupStage3TextW 39 //Text: L"시작합니다!"
#define OpenFileTitleW 89 //Text: L"재생할 파일을 선택하세요: "
#define OpenSplashFileTitleW 70 //Text: L"시작 화면 MIDI 선택: "
#define OpenBackgroundFileTitleW 60 //Text: L"배경 이미지 선택: "
#define StatisticsText1W 70 //Text: "Piano-FX Pro (한국어)"
#define StatisticsText2W 75 //Text: "개발자: happy_mimimix"
#define StatisticsText3W 17 //Text: "시간:"
#define StatisticsText4W 10 //Text: "틱:"
#define StatisticsText5W 39 //Text: "마이크로초:"
#define StatisticsText6W 34 //Text: "노래 템포:"
#define StatisticsText7W 17 //Text: "템포:"
#define StatisticsText8W 17 //Text: "콤보:"
#define StatisticsText9W 34 //Text: "초당 클릭:"
#define StatisticsText10W 34 //Text: "동시 입력:"
#define StatisticsText11W 27 //Text: "노트 수:"
#define StatisticsText12W 34 //Text: "초당 노트:"
#define StatisticsText13W 32 //Text: "폴리포니:"
#define StatisticsText14W 41 //Text: "렌더링 완료:"
#define StatisticsText15W 17 //Text: "볼륨:"
#define StatisticsText16W 22 //Text: "음소거"
#define StatisticsText17W 34 //Text: "재생 속도:"
#define StatisticsText18W 34 //Text: "노트 속도:"
#define StatisticsText19W 31 //Text: "X 오프셋:"
#define StatisticsText20W 31 //Text: "Y 오프셋:"
#define StatisticsText21W 10 //Text: "줌:"
#define StatisticsText22W 27 //Text: "창 크기:"
#define StatisticsText23W 34 //Text: "건반 범위:"
#define StatisticsText24W 17 //Text: "점수:"
#define StatisticsText25W 25 //Text: "난이도:"
#define StatisticsText26W 34 //Text: "자동 연주:"
#define StatisticsText27W 9 //Text: "켬 "
#define StatisticsText28W 34 //Text: "풀 콤보!!! "
#define StatisticsText29W 51 //Text: "데모 진행 중... "
#define StatisticsText30W 41 //Text: "일시 정지... "
#define StatisticsText31W 77 //Text: "오류: 점수 오버플로우! "
#define ZoomMoveMsgW 675 //Text: "- 왼쪽 클릭 후 드래그하여 화면 이동\n- 오른쪽 클릭 후 드래그하여 가로로 확대하기\n- 변경 사항을 적용하려면 “보기->이동 / 확대” 를 다시 클릭합니다\n- 변경 사항을 취소하려면 “보기->위치 초기화” 를 클릭합니다"
#define PropertyWindowTitleW 15 //Text: L"설정"
#define Property1TitleW 15 //Text: L"화면"
#define Property1Text1W 34 //Text: L"건반 표시:"
#define Property1Text2W 43 //Text: L"전체 128건반"
#define Property1Text3W 31 //Text: L"곡에 맞춤"
#define Property1Text4W 34 //Text: L"범위 지정:"
#define Property1Text5W 15 //Text: L"부터"
#define Property1Text6W 34 //Text: L"트랙 색상:"
#define Property1Text7W 29 //Text: L"무작위화"
#define Property1Text8W 34 //Text: L"배경 색상:"
#define Property1Text9W 27 //Text: L"바 색상:"
#define Property1Text10W 39 //Text: L"기본값 복원"
#define Property1Text11W 41 //Text: L"배경 이미지:"
#define Property1Text12W 29 //Text: L"찾아보기"
#define Property1Text13W 22 //Text: L"초기화"
#define Property1Text14W 205 //Text: L"힌트: 고급 그래픽 렌더링 옵션은 '렌더링' 항목에서 확인하세요."
#define Property2TitleW 22 //Text: L"오디오"
#define Property2Text1W 59 //Text: L"표준 WinMM 출력:"
#define Property2Text2W 97 //Text: L"KDMAPI 사용 (OmniMIDI 필요)"
#define Property3TitleW 22 //Text: L"렌더링"
#define Property3Text1W 82 //Text: L"고급 그래픽 렌더링 설정:"
#define Property3Text2W 48 //Text: L"틱 기반 렌더링"
#define Property3Text3W 55 //Text: L"피치 벤드 시각화"
#define Property3Text4W 48 //Text: L"동일 너비 노트"
#define Property3Text5W 31 //Text: L"마커 표시"
#define Property3Text6W 41 //Text: L"마커 인코딩:"
#define Property3Text7W 53 //Text: L"FPS 60으로 고정"
#define Property3Text8W 39 //Text: L"동영상 출력"
#define Property3Text9W 55 //Text: L"디버그 정보 표시"
#define Property3Text10W 39 //Text: L"통계 숨기기"
#define Property4TitleW 15 //Text: L"제어"
#define Property4Text1W 51 //Text: L"제어 동작 설정:"
#define Property4Text2W 51 //Text: L"좌우 키 이동량:"
#define Property4Text3W 7 //Text: L"초"
#define Property4Text4W 60 //Text: L"상하 키 속도 변경:"
#define Property4Text5W 7 //Text: L"%"
#define Property4Text6W 96 //Text: L"전체 화면에서 도구 모음 표시"
#define Property4Text7W 64 //Text: L"Phigros 스타일 점수"
#define Property4Text8W 35 //Text: L"시작 MIDI:"
#define TrackText1W 17 //Text: L"파일:"
#define TrackText2W 17 //Text: L"폴더:"
#define TrackText3W 27 //Text: L"노트 수:"
#define TrackText4W 17 //Text: L"길이:"
#define TrackText5W 41 //Text: L"렉 대신 감속"
#define TrackText6W 87 //Text: L"모든 악기를 피아노로 변경"
#define TrackText7W 15 //Text: L"재생"
#define TrackText8W 15 //Text: L"중단"
#define AboutWindowTitleW 15 //Text: L"정보"
#define AboutText2W 15 //Text: L"확인"
#define LoadWindowTitleW 32 //Text: L"로딩 중..."
#define LoadingTextW 39 //Text: L"불러오는 중"
#define LoadingStage1W 73 //Text: L"MIDI 메모리 복사 중..."
#define LoadingStage2W 49 //Text: L"압축 해제 중..."
#define LoadingStage3W 49 //Text: L"트랙 분석 중..."
#define LoadingStage4W 49 //Text: L"노트 연결 중..."
#define LoadingStage5W 56 //Text: L"이벤트 정렬 중..."
#define ResolutionWindowTitleW 39 //Text: L"해상도 설정"
#define ResolutionText1W 17 //Text: L"너비:"
#define ResolutionText2W 17 //Text: L"높이:"
#define ResolutionText3W 15 //Text: L"확인"
#define ResolutionText4W 15 //Text: L"취소"
#define MenuText1W 15 //Text: L"열기"
#define MenuText2W 15 //Text: L"닫기"
#define MenuText3W 15 //Text: L"재생"
#define MenuText4W 66 //Text: L"재생/일시정지\tSpace"
#define MenuText5W 25 //Text: L"중지\tEsc"
#define MenuText6W 39 //Text: L"앞으로\tRight"
#define MenuText7W 27 //Text: L"뒤로\tLeft"
#define MenuText8W 57 //Text: L"빠르게\tCtrl+Down"
#define MenuText9W 47 //Text: L"느리게\tCtrl+Up"
#define MenuText10W 60 //Text: L"속도 초기화\tCtrl+R"
#define MenuText11W 67 //Text: L"노트 빠르게\tShift+Up"
#define MenuText12W 77 //Text: L"노트 느리게\tShift+Down"
#define MenuText13W 63 //Text: L"노트 초기화\tShift+R"
#define MenuText14W 33 //Text: L"볼륨 업\tUp"
#define MenuText15W 49 //Text: L"볼륨 다운\tDown"
#define MenuText16W 44 //Text: L"음소거\tCtrl+M"
#define MenuText17W 15 //Text: L"보기"
#define MenuText18W 31 //Text: L"제어 패널"
#define MenuText19W 31 //Text: L"건반 표시"
#define MenuText20W 24 //Text: L"항상 위"
#define MenuText21W 63 //Text: L"전체 화면\tAlt+Enter"
#define MenuText22W 64 //Text: L"창 크기 설정\tCtrl+W"
#define MenuText23W 32 //Text: L"이동/확대"
#define MenuText24W 39 //Text: L"위치 초기화"
#define MenuText25W 15 //Text: L"설정"
#define MenuText26W 15 //Text: L"정보"
#define MenuText27W 80 //Text: L"피아노 FX 스튜디오 열기"
#endif
#ifdef RUS
#define MainWindowTitle1W 41 //Text: L"Piano-FX Pro"
#define MainWindowTitle2W 96 //Text: L"Разработчик: happy_mimimix"
#define MainWindowTitle3W 54 //Text: L"Сейчас играет: "
#define MainWindowTitle4W 71 //Text: L"Сейчас рендерится: "
#define MainWindowTitle5W 13 //Text: L"Нет"
#define MainWindowTitle6W 49 //Text: L"Заставка MIDI"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 153 //Text: L"  (Принудительный программный рендеринг)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 113 //Text: L"Добро пожаловать в Piano-FX Pro"
#define StartupStage1TextW 49 //Text: L"Подготовка..."
#define StartupStage2TextW 89 //Text: L"Загрузка заставки MIDI..."
#define StartupStage3TextW 31 //Text: L"Поехали!"
#define OpenFileTitleW 133 //Text: L"Выберите файл для воспроизведения: "
#define OpenSplashFileTitleW 123 //Text: L"Выберите MIDI-файл для заставки: "
#define OpenBackgroundFileTitleW 116 //Text: L"Выберите фоновое изображение: "
#define StatisticsText1W 75 //Text: "Piano-FX Pro (русский)"
#define StatisticsText2W 96 //Text: "Разработчик: happy_mimimix"
#define StatisticsText3W 23 //Text: "Время:"
#define StatisticsText4W 19 //Text: "Тики:"
#define StatisticsText5W 53 //Text: "Микросекунды:"
#define StatisticsText6W 57 //Text: "частота кадров:"
#define StatisticsText7W 40 //Text: "Темп песни:"
#define StatisticsText8W 23 //Text: "Комбо:"
#define StatisticsText9W 41 //Text: "Кликов/сек:"
#define StatisticsText10W 41 //Text: "Полифония:"
#define StatisticsText11W 21 //Text: "Ноты:"
#define StatisticsText12W 29 //Text: "Нот/сек:"
#define StatisticsText13W 41 //Text: "Полифония:"
#define StatisticsText14W 49 //Text: "Отрендерено:"
#define StatisticsText15W 38 //Text: "Громкость:"
#define StatisticsText16W 36 //Text: "БЕЗ ЗВУКА"
#define StatisticsText17W 35 //Text: "Скорость:"
#define StatisticsText18W 49 //Text: "Скорость нот:"
#define StatisticsText19W 43 //Text: "Смещение X:"
#define StatisticsText20W 43 //Text: "Смещение Y:"
#define StatisticsText21W 33 //Text: "Масштаб:"
#define StatisticsText22W 44 //Text: "Размер окна:"
#define StatisticsText23W 63 //Text: "Диапазон клавиш:"
#define StatisticsText24W 19 //Text: "Счет:"
#define StatisticsText25W 31 //Text: "Уровень:"
#define StatisticsText26W 39 //Text: "Автовоспр:"
#define StatisticsText27W 13 //Text: "ВКЛ"
#define StatisticsText28W 66 //Text: "ПОЛНЫЙ КОМБО!!! "
#define StatisticsText29W 59 //Text: "Демонстрация... "
#define StatisticsText30W 30 //Text: "Пауза... "
#define StatisticsText31W 109 //Text: "ОШИБКА: Переполнение счета! "
#define ZoomMoveMsgW 1,041 //Text: "- Щелкните левой кнопкой мыши и перетащите, чтобы переместить экран\n- Щелкните правой кнопкой мыши и перетащите, чтобы увеличить масштаб по горизонтали\n- Нажмите 'Вид -> Позиция и масштаб' еще раз, чтобы применить изменения\n- Нажмите 'Вид -> Сброс позиции', чтобы отменить изменения"
#define PropertyWindowTitleW 36 //Text: L"Настройки"
#define Property1TitleW 44 //Text: L"Внешний вид"
#define Property1Text1W 86 //Text: L"Отображаемые клавиши:"
#define Property1Text2W 53 //Text: L"Все 128 клавиш"
#define Property1Text3W 50 //Text: L"По композиции"
#define Property1Text4W 35 //Text: L"Диапазон:"
#define Property1Text5W 9 //Text: L"до"
#define Property1Text6W 56 //Text: L"Цвета дорожек:"
#define Property1Text7W 60 //Text: L"Случайные цвета"
#define Property1Text8W 39 //Text: L"Цвет фона:"
#define Property1Text9W 47 //Text: L"Цвет полосы:"
#define Property1Text10W 54 //Text: L"Сбросить цвета"
#define Property1Text11W 79 //Text: L"Фоновое изображение:"
#define Property1Text12W 21 //Text: L"Обзор"
#define Property1Text13W 20 //Text: L"Сброс"
#define Property1Text14W 273 //Text: L"Подсказка: дополнительные параметры графики см. в категории «Рендеринг»."
#define Property2TitleW 16 //Text: L"Звук"
#define Property2Text1W 98 //Text: L"Стандартный вывод WinMM:"
#define Property2Text2W 201 //Text: L"Использовать KDMAPI вместо WinMM (требуется OmniMIDI)"
#define Property3TitleW 36 //Text: L"Рендеринг"
#define Property3Text1W 117 //Text: L"Расширенные настройки графики:"
#define Property3Text2W 68 //Text: L"Рендеринг по тикам"
#define Property3Text3W 73 //Text: L"Визуализация бендов"
#define Property3Text4W 65 //Text: L"Равная ширина нот"
#define Property3Text5W 73 //Text: L"Показывать маркеры"
#define Property3Text6W 74 //Text: L"Кодировка маркеров:"
#define Property3Text7W 75 //Text: L"Ограничить FPS до 60"
#define Property3Text8W 51 //Text: L"Экспорт видео"
#define Property3Text9W 131 //Text: L"Показывать отладочную информацию"
#define Property3Text10W 67 //Text: L"Скрыть статистику"
#define Property4TitleW 41 //Text: L"Управление"
#define Property4Text1W 119 //Text: L"Поведение элементов управления:"
#define Property4Text2W 77 //Text: L"Перемотка стрелками:"
#define Property4Text3W 11 //Text: L"сек"
#define Property4Text4W 109 //Text: L"Изменение скорости стрелками:"
#define Property4Text5W 7 //Text: L"%"
#define Property4Text6W 156 //Text: L"Не скрывать панель в полноэкранном режиме"
#define Property4Text7W 75 //Text: L"Система счета Phigros"
#define Property4Text8W 77 //Text: L"Приветственный MIDI:"
#define TrackWindowTitleW 58 //Text: L"Настройки трека"
#define TrackText1W 20 //Text: L"Файл:"
#define TrackText2W 23 //Text: L"Папка:"
#define TrackText3W 15 //Text: L"Нот:"
#define TrackText4W 51 //Text: L"Длительность:"
#define TrackText5W 87 //Text: L"Замедление вместо лагов"
#define TrackText6W 132 //Text: L"Заменить все инструменты на пианино"
#define TrackText7W 24 //Text: L"Играть"
#define TrackText8W 25 //Text: L"Отмена"
#define AboutWindowTitleW 43 //Text: L"О программе"
#define AboutText2W 9 //Text: L"OK"
#define LoadWindowTitleW 39 //Text: L"Загрузка..."
#define LoadingTextW 31 //Text: L"Загрузка"
#define LoadingStage1W 102 //Text: L"Копирование MIDI в память..."
#define LoadingStage2W 47 //Text: L"Распаковка..."
#define LoadingStage3W 58 //Text: L"Анализ треков..."
#define LoadingStage4W 63 //Text: L"Соединение нот..."
#define LoadingStage5W 79 //Text: L"Сортировка событий..."
#define ResolutionWindowTitleW 41 //Text: L"Разрешение"
#define ResolutionText1W 29 //Text: L"Ширина:"
#define ResolutionText2W 27 //Text: L"Высота:"
#define ResolutionText3W 10 //Text: L"ОК"
#define ResolutionText4W 25 //Text: L"Отмена"
#define MenuText1W 31 //Text: L"Открыть"
#define MenuText2W 29 //Text: L"Закрыть"
#define MenuText3W 24 //Text: L"Играть"
#define MenuText4W 64 //Text: L"Воспр./Пауза\tSpace"
#define MenuText5W 27 //Text: L"Стоп\tEsc"
#define MenuText6W 41 //Text: L"Вперед\tRight"
#define MenuText7W 33 //Text: L"Назад\tLeft"
#define MenuText8W 67 //Text: L"Ускорить\tCtrl+Down"
#define MenuText9W 62 //Text: L"Замедлить\tCtrl+Up"
#define MenuText10W 74 //Text: L"Сброс скорости\tCtrl+R"
#define MenuText11W 78 //Text: L"Быстрые ноты\tShift+Up"
#define MenuText12W 97 //Text: L"Медленные ноты\tShift+Down"
#define MenuText13W 59 //Text: L"Сброс нот\tShift+R"
#define MenuText14W 33 //Text: L"Громче\tUp"
#define MenuText15W 35 //Text: L"Тише\tDown"
#define MenuText16W 55 //Text: L"Без звука\tCtrl+M"
#define MenuText17W 13 //Text: L"Вид"
#define MenuText18W 67 //Text: L"Панель управления"
#define MenuText19W 41 //Text: L"Клавиатура"
#define MenuText20W 43 //Text: L"Поверх окон"
#define MenuText21W 79 //Text: L"Полный экран\tAlt+Enter"
#define MenuText22W 65 //Text: L"Размер окна\tCtrl+W"
#define MenuText23W 65 //Text: L"Позиция и масштаб"
#define MenuText24W 49 //Text: L"Сброс позиции"
#define MenuText25W 36 //Text: L"Настройки"
#define MenuText26W 43 //Text: L"О программе"
#define MenuText27W 83 //Text: L"Открыть Piano-FX Studio"
#endif
#ifdef DRN
#define MainWindowTitle1W 113 //Text: L"ЖЩ1 ЯЭ4 ДЭ5 ГГ1 ЪМ2 ТЭ4 ЩС4"
#define MainWindowTitle2W 99 //Text: L"КБ1 ФА1 ЖЭ3: happy_mimimix"
#define MainWindowTitle3W 67 //Text: L"ЖЖ4 ЗБ4 БО1 ФГ4: "
#define MainWindowTitle4W 71 //Text: L"ЖЖ4 ЗБ4 ЩЩ4 РН3: "
#define MainWindowTitle5W 31 //Text: L"КК4 ЩП2"
#define MainWindowTitle6W 54 //Text: L"ХЩ1 ЯЫ2 MIDI+"
#ifdef SOFTWARE_RENDER_ONLY
#define MainWindowTitle7W 108 //Text: L"  (ЪВ2 ЖИ4 РЩ3 ЙП4 ЩЩ4 РН3)"
#else
#define MainWindowTitle7W 0 //Text: L""
#endif
#define WelcomeTextW 179 //Text: L"ХЩ1 ЯЫ2 ШИ3 ЯК4 ЖЩ1 ЯЭ4 ДЭ5 ГГ1 ЪМ2 ТЭ4 ЩС4"
#define StartupStage1TextW 55 //Text: L"ЖЬ3 БЙ4 ЖК1..."
#define StartupStage2TextW 82 //Text: L"ЗБ3 РЕ4 ХЩ1 ЯЫ2 MIDI+"
#define StartupStage3TextW 33 //Text: L"ЧЕ1 ФА1! "
#define OpenFileTitleW 181 //Text: L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩВ3 ЯУ4 БО1 ФГ4 ДЭ5 ВД2 ЙП4: "
#define OpenSplashFileTitleW 244 //Text: L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩИ1 ВГ4 ЯК4 ЗХ4 ХЩ1 ЯЫ2 ПЫ2 МЕ4 ДЭ5 ВД2 ЙП4: "
#define OpenBackgroundFileTitleW 241 //Text: L"ЪЫ3 ЩЩ3 ЪЕ3 НМ2 ЩИ1 ВГ4 ЯК4 ЗХ4 БЙ4 ЙЫ3 ТЕ2 ЩВ4 ДЭ5 ВД2 ЙП4: "
#define StatisticsText1W 101 //Text: "Piano-FX Pro (DoubleArinoglish)"
#define StatisticsText2W 99 //Text: "КБ1 ФА1 ЖЭ3: happy_mimimix"
#define StatisticsText3W 33 //Text: "ШИ2 ЧГ2:"
#define StatisticsText4W 16 //Text: "КЭ4:"
#define StatisticsText5W 31 //Text: "ВЙ1 МС3:"
#define StatisticsText6W 33 //Text: "ЖД1 ЛЁ4:"
#define StatisticsText7W 61 //Text: "ЯМ1 ЯЕ4 СЕ4 ЛЁ4:"
#define StatisticsText8W 31 //Text: "ЛП2 ЙИ1:"
#define StatisticsText9W 65 //Text: "МЙ3 МС3 ШФ3 СЕ4:"
#define StatisticsText10W 67 //Text: "ШФ3 ЖИ3 ГЭ4 ШЕ4:"
#define StatisticsText11W 49 //Text: "ЯМ1 ФЕ2 ШЕ4:"
#define StatisticsText12W 63 //Text: "МЙ3 МС3 ЯН3 ЗФ4:"
#define StatisticsText13W 63 //Text: "ТК2 ШИ2 ЯН3 ЗФ4:"
#define StatisticsText14W 51 //Text: "ЯИ3 ЩЩ4 РН3:"
#define StatisticsText15W 31 //Text: "ЯМ1 ЛВ4:"
#define StatisticsText16W 30 //Text: "ЙЫ4 ЯМ1"
#define StatisticsText17W 61 //Text: "БО1 ФГ4 СЕ4 ДЕ5:"
#define StatisticsText18W 62 //Text: "ЯМ1 ФЕ2 СЕ4 ДЕ5:"
#define StatisticsText19W 37 //Text: "X ПП1 ЯИ2:"
#define StatisticsText20W 37 //Text: "Y ПП1 ЯИ2:"
#define StatisticsText21W 31 //Text: "СХ1 ФГ4:"
#define StatisticsText22W 68 //Text: "ЧШ1 КФ3 ДА4 ЩС3:"
#define StatisticsText23W 63 //Text: "ЪМ2 ЙП4 ФН4 ВЙ2:"
#define StatisticsText24W 34 //Text: "ФД1 ШЕ4:"
#define StatisticsText25W 62 //Text: "ЪЕ3 МЕ4 НН2 ДЕ4:"
#define StatisticsText26W 62 //Text: "ЗИ4 ДК4 ЯН3 ЗФ4:"
#define StatisticsText27W 31 //Text: "КБ1 ЪИ3 "
#define StatisticsText28W 81 //Text: "GON1 ЩИ3 ЪЩ2 ЛП2!!! "
#define StatisticsText29W 89 //Text: "ЗИ4 ДК4 ЯН3 ШИ4 ЖК1... "
#define StatisticsText30W 72 //Text: "ЯФ2 ЩИ4 ЗН4 ТЫ2... "
#define StatisticsText31W 98 //Text: "ЦХ4 ВЕ4: ФД1 ШЕ4 ЯИ4 ЧЕ1! "
#define ZoomMoveMsgW 903 //Text: "- ЗХ3 ЙП4 ДН1 ЙИ1 БЫ4 ТХ1 ДК4 КЭ3 ЯИ2 ДК4 ПЫ2 МЕ4\n- ЯФ4 ЙП4 ДН1 ЙИ1 БЫ4 ТХ1 ДК1 КЭ3 ШЪ3 ПЫ2 СХ1 ФГ4\n- ЗБ4 ЦИ4 ДП3 ЙИ1 'ЧА2 КН4 -> ЯИ2 ДК4 ХЭ2 СХ1 ФГ4' КЭ3 ЯЫ4 ЯК4 ГЖ1 ГБ3\n- ДП3 ЙИ1 'ЧА2 КН4 -> ЧК2 ЖИ4 ЯИ2 ДК4 ХЭ2 СХ1 ФГ4' КЭ3 ЧЭ4 ЩС1 ГЖ1 ГБ3"
#define PropertyWindowTitleW 33 //Text: L"ШЭ4 ЖИ4"
#define Property1TitleW 30 //Text: L"ШИ4 ЙТ2"
#define Property1Text1W 68 //Text: L"ЪМ2 ЙП4 ЩП3 ШИ4:"
#define Property1Text2W 60 //Text: L"ЪЩ2 БЕ4 128 ЙП4"
#define Property1Text3W 99 //Text: L"ГД1 ЙЕ4 MIDI+ ЗИ4 ШИ4 ЯЫ4"
#define Property1Text4W 65 //Text: L"ЖИ3 ДЫ4 ФН4 ВЙ2:"
#define Property1Text5W 31 //Text: L"ЖИ2 ДУ4"
#define Property1Text6W 63 //Text: L"ЯМ1 ГЪ3 ЯН2 СЭ4:"
#define Property1Text7W 29 //Text: L"СЪ2 ЙИ1"
#define Property1Text8W 62 //Text: L"БЙ4 ЙЫ3 ЯН2 СЭ4:"
#define Property1Text9W 63 //Text: L"ХЖ2 ТС2 ЯН2 СЭ4:"
#define Property1Text10W 61 //Text: L"ЧК2 ЖИ4 ЯН2 СЭ4"
#define Property1Text11W 61 //Text: L"БЙ4 ЙЫ3 ТЕ2 ПП4:"
#define Property1Text12W 31 //Text: L"ЛЮ2 ЛН3"
#define Property1Text13W 31 //Text: L"ЧК2 ЖИ4"
#define Property1Text14W 261 //Text: L"ЪП2 ВГ3 'ЩЩ4 РН3' ЛЙ4 БЗ2 ЧА2 КН4 ГЖ4 ДХ1 ГУ1 ЙИ2 ЩЩ4 РН3 ШЭ4 ЖИ4."
#define Property2TitleW 30 //Text: L"ЯМ1 ПМ2"
#define Property2Text1W 95 //Text: L"БС1 ЖЬ3 WINMM+ ШЕ1 ЧЕ1:"
#define Property2Text2W 206 //Text: L"ШИ3 ЯК4 KDMAPI+ ДБ4 ТИ4 WINMM+ (ЩЕ1 ЯУ4 OMNI MIDI+)"
#define Property3TitleW 33 //Text: L"ЩЩ4 РН3"
#define Property3Text1W 131 //Text: L"ГУ1 ЙИ2 ТЕ2 ЩЫ2 ЩЩ4 РН3 ПЙ4 ЖИ4:"
#define Property3Text2W 79 //Text: L"ЙИ1 ЯЕ2 КЭ4 ЩЩ4 РН3"
#define Property3Text3W 77 //Text: L"КЭ3 ШИ4 ХЦ4 ВН1 ЯМ1"
#define Property3Text4W 65 //Text: L"ДЖ3 КЩ1 ЯМ1 ФЕ2"
#define Property3Text5W 63 //Text: L"ЩП3 ШИ4 БС1 ЙИ4"
#define Property3Text6W 94 //Text: L"ВД2 БД3 БП1 МА3 ГЭ2 ШИ4:"
#define Property3Text7W 107 //Text: L"СХ3 ДЫ4 ЖД1 ЛЁ4 ЖИ4 60 ЖД1"
#define Property3Text8W 62 //Text: L"ДУ3 ЧЕ1 ШИ4 ПМ2"
#define Property3Text9W 102 //Text: L"ЩП3 ШИ4 ТС2 ШИ4 ЩМ4 ЩИ1"
#define Property3Text10W 96 //Text: L"ЯМ3 ЦГ2 ТК3 ЙИ4 ЩМ4 ЩИ1"
#define Property4TitleW 31 //Text: L"КК4 ЖИ4"
#define Property4Text1W 101 //Text: L"КК4 ЖИ4 ЩЫ2 ВЙ2 ШЭ4 ЖИ4:"
#define Property4Text2W 90 //Text: L"ЗХ3 ЯФ4 ЙП4 ТФ2 ТС4 ГХ4:"
#define Property4Text3W 14 //Text: L"МС3"
#define Property4Text4W 96 //Text: L"ШГ4 ЩЯ4 ЙП4 ТФ2 ЙЯ1 СЕ4:"
#define Property4Text5W 46 //Text: L"ФД1 ЖИ1 ББ3"
#define Property4Text6W 174 //Text: L"ЪЩ2 ПЫ2 МО2 ШИ4 ЩЯ4 БЕ4 ЯМ3 ЦГ2 ГК1 ЙЕ4 ТС2"
#define Property4Text7W 133 //Text: L"PHIGROS+ ФЖ1 ГЭ2 ЙИ4 ФД1 ЩИ4 ТК3"
#define Property4Text8W 57 //Text: L"ХЩ1 ЯЫ2 MIDI+:"
#define TrackWindowTitleW 64 //Text: L"ЯМ1 ГЪ3 ШЭ4 ЖИ4"
#define TrackText1W 31 //Text: L"ВД3 ЙП4:"
#define TrackText2W 31 //Text: L"ЛЕ4 ЙЫ4:"
#define TrackText3W 49 //Text: L"ЯМ1 ФЕ2 ШЕ4:"
#define TrackText4W 33 //Text: L"ШИ1 ЧГ2:"
#define TrackText5W 105 //Text: L"ЙП3 СЕ4 ER2 БЕ2 ШИ4 КА3 ДЬ4"
#define TrackText6W 154 //Text: L"ЙВ1 СХ3 ЯФ3 ЯТ4 ЪИ4 ТИ4 ХЩ4 ЧЖ2 ГГ1 ЪМ2"
#define TrackText7W 29 //Text: L"БО1 ФГ4"
#define TrackText8W 33 //Text: L"ЖК1 ЖИ3"
#define AboutWindowTitleW 30 //Text: L"ГЩ1 ЯЕ2"
#define AboutText2W 29 //Text: L"ХУ3 ДЭ5"
#define LoadWindowTitleW 53 //Text: L"ЙЯ1 ЗБ3 ЖК1..."
#define LoadingTextW 62 //Text: L"ЖЖ4 ЗБ4 ДЕ2 ЪЕ3"
#define LoadingStage1W 164 //Text: L"ЖЖ4 ЗБ4 ЙВ1 ВД2 ЙП4 ФЕ4 ЖИ4 ДУ4 НЙ4 ЦЬ2..."
#define LoadingStage2W 84 //Text: L"ЖЖ4 ЗБ4 ЙЗ3 ЯА1 СХ1..."
#define LoadingStage3W 103 //Text: L"ЖЖ4 ЗБ4 ЙЗ3 ЩИ1 ЯМ1 ГЪ3..."
#define LoadingStage4W 101 //Text: L"ЖЖ4 ЗБ4 ЛП2 ЙИ1 ЯМ1 ФЕ2..."
#define LoadingStage5W 107 //Text: L"ЖЖ4 ЗБ4 ЖЖ3 ЛИ3 ШИ1 ЙП4..."
#define ResolutionWindowTitleW 79 //Text: L"ШЭ4 ЖИ4 ФД1 БП4 ЛЁ4"
#define ResolutionText1W 19 //Text: L"КЩ1:"
#define ResolutionText2W 15 //Text: L"ГУ1:"
#define ResolutionText3W 29 //Text: L"ЪТ4 РД4"
#define ResolutionText4W 31 //Text: L"ЪЕ3 ЩС1"
#define MenuText1W 29 //Text: L"ДА3 КБ1"
#define MenuText2W 30 //Text: L"ГЩ1 БИ4"
#define MenuText3W 29 //Text: L"ЯН3 ЗФ4"
#define MenuText4W 79 //Text: L"БО1 ФГ4/ЗН4 ТЫ2\tSpace"
#define MenuText5W 41 //Text: L"ТЫ2 ЖИ3\tEsc"
#define MenuText6W 53 //Text: L"KAUI4 ЙМ4\tRight"
#define MenuText7W 41 //Text: L"КЧ4 ТЪ4\tLeft"
#define MenuText8W 93 //Text: L"БО1 ФГ4 ЙЯ1 СЕ4\tCtrl+Down"
#define MenuText9W 84 //Text: L"БО1 ФГ4 ЙП3 СЕ4\tCtrl+Up"
#define MenuText10W 83 //Text: L"БО1 ФГ4 ЧК2 ЖИ4\tCtrl+R"
#define MenuText11W 88 //Text: L"ЯМ1 ФЕ2 ЙЯ1 СЕ4\tShift+Up"
#define MenuText12W 97 //Text: L"ЯМ1 ФЕ2 ЙП3 СЕ4\tShift+Down"
#define MenuText13W 87 //Text: L"ЧК2 ЖИ4 ЯМ1 ФЕ2\tShift+R"
#define MenuText14W 53 //Text: L"ЯМ1 ЛВ4 ЙЯ1\tUp"
#define MenuText15W 62 //Text: L"ЯМ1 ЛВ4 ЙП3\tDown"
#define MenuText16W 52 //Text: L"ЙЫ4 ЯМ1\tCtrl+M"
#define MenuText17W 29 //Text: L"ЧА2 КН4"
#define MenuText18W 42 //Text: L"ГК1 ЙЕ4 ТС2"
#define MenuText19W 29 //Text: L"ЙП4 ПН2"
#define MenuText20W 65 //Text: L"ЧШ1 КФ3 ЖИ4 ДЫ3"
#define MenuText21W 99 //Text: L"ЪЩ2 ПЫ2 ЩП3 ШИ4\tAlt+Enter"
#define MenuText22W 123 //Text: L"ШЭ4 ЖИ4 ЧШ1 КФ3 ДА4 ЩС3\tCtrl+W"
#define MenuText23W 74 //Text: L"ЯИ2 ДК4 ХЭ2 СХ1 ФГ4"
#define MenuText24W 107 //Text: L"ЧК2 ЖИ4 ЯИ2 ДК4 ХЭ2 СХ1 ФГ4"
#define MenuText25W 33 //Text: L"ШЭ4 ЖИ4"
#define MenuText26W 30 //Text: L"ГЩ1 ЯЕ2"
#define MenuText27W 107 //Text: L"ГГ1 ЪМ2 ТЭ4 ЩС4 БП1 ЙИ1 ЪИ4"
#endif
